
# Temas de salud mental y bienestar

## Salud mental y bienestar de la población

### ¿Cómo se encuentra, y cómo ha cambiado la salud mental y nivel de bienestar de la población?

```{r salud-bienestar-2021, fig.cap = 'Satisfacción con la vida y salud subjetiva (ola 2021)'}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & ola == 5 & !is_nsnr(s01, s02, s03)) %>% 
  prop_list(s01 %in% 4:5, s02 %in% 4:5, s03 %in% 4:5, na.rm = TRUE) %>% 
  mutate(name = factor(name,
                       levels = c('s01 %in% 4:5', 's02 %in% 4:5', 's03 %in% 4:5'),
                       labels = c('Esta satisfecho o muy\nsatisfecho con su vida',
                                  'Su vida se acerca o se acerca\ncompletamente a su ideal',
                                  'Su salud es muy buena\no Excelente'))) %>% 
  ggplot(aes(y = prop, x = name, fill = name,
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_col() +
  geom_text(position = position_dodge(.9), 
            vjust = -.5, size = 3) +
  scale_y_continuous(labels = scales::percent, limits = c(0,1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +  
  scale_fill_viridis_d(end = .75, option = 'viridis') +
  theme(legend.position = 'none') +
  ggtitle(NULL, 'Porcentaje que responde que...')

```

```{r salud-bienestar-olas, fig.cap = 'Satisfacción con la vida y salud subjetiva, según ola'}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & !is_nsnr(s01, s02, s03)) %>% 
  sjlabelled::as_label(ola) %>%
  prop_list(s01 %in% 4:5, s02 %in% 4:5, s03 %in% 4:5, by = ola, na.rm = TRUE) %>% 
  mutate(name = factor(name,
                       levels = c('s01 %in% 4:5', 's02 %in% 4:5', 's03 %in% 4:5'),
                       labels = c('Esta satisfecho o muy\nsatisfecho con su vida',
                                  'Su vida se acerca o se acerca\ncompletamente a su ideal',
                                  'Su salud es muy buena\no Excelente'))) %>% 
  ggplot(aes(y = prop, x = ola, group = name, color = name,
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_point(size = 1.75) + 
  geom_line() +
  geom_text_repel(nudge_y = .025, size = 3, color = 'black') +
  scale_y_continuous(labels = scales::percent, limits = c(0,1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +  
  scale_color_viridis_d(end = .75, option = 'viridis') +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle(NULL, 'Porcentaje que responde que...')

```

### Sintomatología depresiva

```{r depre-wave, fig.cap = 'Porcentaje que presenta síntomas de depresión (2021)'}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1, ola == 5) %>% 
  purrr::map_at(.at = vars(starts_with('s11_0')), 
                .f = function(s) car::recode(s, "1 = 0; 2 = 1; 3 = 2; c(4, 5) = 3; c(-888, -999) = NA")) %>%
  as.data.frame() %>%  
  mutate(phq9 = (s11_01 + s11_02 + s11_03 + s11_04 + s11_05 + s11_06 + s11_07 + s11_08 + s11_09),
         depr = factor(car::recode(phq9, "0:4 = 1; 5:9 = 2; 10:14 = 3; 15:27 = 4"), 
                       levels = c(1,2,3,4),
                       labels = c('Sin sintomas o síntomas\nde depresión mínima', 
                                  'Síntomas de\ndepresion media', 
                                  'Síntomas de\ndepresion moderada', 
                                  'Síntomas de depresion\nmoderada-severa o severa'))) %>%
  prop(depr, na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = depr, fill = depr, 
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent, limits = 0:1) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .85, direction = -1) +
  geom_text(position = position_dodge2(.9),
            size = 3, 
            vjust = -.5) +
  theme(legend.position = 'none')

```


```{r depre-bienestar, fig.cap = 'Satisfacción con la vida y salud subjetiva (ola 2021), según Sintomas de depresión'}

elsoc_long_2016_2021 %>% 
  purrr::map_at(.at = vars(starts_with('s11_0')), 
                .f = function(s) car::recode(s, "1 = 0; 2 = 1; 3 = 2; c(4, 5) = 3; c(-888, -999) = NA")) %>%
  as.data.frame() %>%  
  mutate(phq9 = (s11_01 + s11_02 + s11_03 + s11_04 + s11_05 + s11_06 + s11_07 + s11_08 + s11_09),
         depr = factor(car::recode(phq9, "0:4 = 1; 5:9 = 2; 10:14 = 3; 15:27 = 4"), 
                       levels = c(1,2,3,4),
                       labels = c('Sin sintomas o síntomas\nde depresión mínima', 
                                  'Síntomas de\ndepresion media', 
                                  'Síntomas de\ndepresion moderada', 
                                  'Síntomas de depresion\nmoderada-severa o severa'))) %>%
  filter(tipo_atricion == 1 & ola == 5, !is_nsnr(s01, s02, s03) & !is.na(depr)) %>%  
  prop_list(s01 %in% 4:5, s02 %in% 4:5, s03 %in% 4:5, by = depr, na.rm = TRUE) %>% 
  mutate(name = factor(name,
                       levels = c('s01 %in% 4:5', 's02 %in% 4:5', 's03 %in% 4:5'),
                       labels = c('Esta satisfecho o muy\nsatisfecho con su vida',
                                  'Su vida se acerca o se acerca\ncompletamente a su ideal',
                                  'Su salud es muy buena\no Excelente'))) %>% 
  ggplot(aes(y = prop, x = name, fill = depr, 
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent, limits = 0:1) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .85, direction = -1) +
  geom_text(position = position_dodge2(.9),
            size = 3, 
            vjust = -.5) +
  theme(legend.position = 'top',
        legend.title = element_blank())


```



```{r depre-wave2, fig.cap = 'Porcentaje que presenta síntomas de depresión, según ola'}

elsoc_long_2016_2021 %>% 
  purrr::map_at(.at = vars(starts_with('s11_0')), 
                .f = function(s) car::recode(s, "1 = 0; 2 = 1; 3 = 2; c(4, 5) = 3; c(-888, -999) = NA")) %>%
  as.data.frame() %>%  
  mutate(phq9 = (s11_01 + s11_02 + s11_03 + s11_04 + s11_05 + s11_06 + s11_07 + s11_08 + s11_09),
         depr = factor(car::recode(phq9, "0:4 = 1; 5:9 = 2; 10:14 = 3; 15:27 = 4"), 
                       levels = c(1,2,3,4),
                       labels = c('Sin sintomas o síntomas\nde depresión mínima', 
                                  'Síntomas de\ndepresion media', 
                                  'Síntomas de\ndepresion moderada', 
                                  'Síntomas de depresion\nmoderada-severa\no severa'))) %>%
  dplyr::filter(tipo_atricion == 1) %>% 
  prop(depr, by = c(ola), na.rm = TRUE) %>% 
  sjlabelled::as_label(depr, ola) %>% 
  ggplot(aes(y = prop, x = ola, fill = fct_rev(depr), 
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .85, option = 'viridis') +
  geom_text(position = position_stack(vjust = .5),
            size = 3, 
            color = rep(rep(c('black', 'white'), each = 2), 5)) + 
  theme(legend.position = 'top',
        legend.title = element_blank()) + 
  guides(fill = guide_legend(reverse = TRUE))

```


```{r depre-alluvial, fig.cap = 'Cambios en síntomas depresivos entre 2016 y 2021'}

elsoc_long_2016_2021 %>% 
  purrr::map_at(.at = vars(starts_with('s11_0')), 
                .f = function(s) car::recode(s, "1 = 0; 2 = 1; 3 = 2; c(4, 5) = 3; c(-888, -999) = NA")) %>%
  as.data.frame() %>%  
  dplyr::filter(tipo_atricion == 1) %>% 
  mutate(phq9 = (s11_01 + s11_02 + s11_03 + s11_04 + s11_05 + s11_06 + s11_07 + s11_08 + s11_09),
         depr = factor(car::recode(phq9, "0:4 = 1; 5:9 = 2; 10:14 = 3; 15:27 = 4"),
                       levels = c(1,2,3,4),
                       labels = c('Sin sintomas o síntomas\nde depresión mínima', 
                                  'Síntomas de\ndepresion media', 
                                  'Síntomas de\ndepresion moderada', 
                                  'Síntomas de depresion\nmoderada-severa o severa'))) %>% 
  as_label(ola) %>% 
  survey_design_elsoc() %>%
  svytable(~depr + ola + idencuesta, design = .) %>% 
  as.data.frame() %>% 
  group_by(ola) %>% 
  mutate(prop = Freq/sum(Freq)) %>%
  filter(Freq > 0) %>% 
  ggplot(aes(y = prop, x = ola, fill = fct_rev(depr), 
             stratum = fct_rev(depr), alluvium = idencuesta)) +
  theme_bw() +
  ggalluvial::geom_flow(alpha = .66) + 
  ggalluvial::geom_stratum(linetype = 0, width = .55) +
  scale_y_continuous(labels = scales::percent) + 
  ylab(label = NULL) +
  xlab(label = NULL) + 
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  scale_fill_viridis_d(direction = -1, end = .9) +
  geom_text(data = function(x) { group_by(.data = x, ola, depr) %>%
      summarise(prop = sum(prop, na.rm = TRUE), idencuesta = 1) %>%
      ungroup()}, 
      aes(label = scales::percent(prop, accuracy = .1)),
      position = position_stack(vjust = .5),
      show.legend = FALSE,
      color = rep(c('white', 'white', 'black', 'black'), 5),
            size = 3) + 
  guides(fill = guide_legend(reverse = TRUE))

```

```{r, results='hide'}

elsoc_depr_lca <- elsoc_wide_2016_2021 %>% 
  dplyr::filter(tipo_atricion == 1) %>% 
  purrr::map_at(.at = vars(starts_with('s11_0')), 
                .f = function(s) car::recode(s, "1 = 0; 2 = 1; 3 = 2; c(4, 5) = 3; c(-888, -999) = NA")) %>%
  as.data.frame() %>%
  mutate(
    phq9_w01 = (s11_01_w01 + s11_02_w01 + s11_03_w01 + s11_04_w01 + s11_05_w01 + s11_06_w01 + s11_07_w01 + s11_08_w01+ s11_09_w01),
    phq9_w02 = (s11_01_w02 + s11_02_w02 + s11_03_w02 + s11_04_w02 + s11_05_w02 + s11_06_w02 + s11_07_w02 + s11_08_w02+ s11_09_w02),
    phq9_w03 = (s11_01_w03 + s11_02_w03 + s11_03_w03 + s11_04_w03 + s11_05_w03 + s11_06_w03 + s11_07_w03 + s11_08_w03+ s11_09_w03),
    phq9_w04 = (s11_01_w04 + s11_02_w04 + s11_03_w04 + s11_04_w04 + s11_05_w04 + s11_06_w04 + s11_07_w04 + s11_08_w04+ s11_09_w04),
    phq9_w05 = (s11_01_w05 + s11_02_w05 + s11_03_w05 + s11_04_w05 + s11_05_w05 + s11_06_w05 + s11_07_w05 + s11_08_w05+ s11_09_w05),
    depr_w01 = car::recode(phq9_w01, "0:4 = 1; 5:9 = 2; 10:14 = 3; 15:27 = 4; else = NA"),
    depr_w02 = car::recode(phq9_w02, "0:4 = 1; 5:9 = 2; 10:14 = 3; 15:27 = 4; else = NA"),
    depr_w03 = car::recode(phq9_w03, "0:4 = 1; 5:9 = 2; 10:14 = 3; 15:27 = 4; else = NA"),
    depr_w04 = car::recode(phq9_w04, "0:4 = 1; 5:9 = 2; 10:14 = 3; 15:27 = 4; else = NA"),
    depr_w05 = car::recode(phq9_w05, "0:4 = 1; 5:9 = 2; 10:14 = 3; 15:27 = 4; else = NA")
    ) %>% 
  drop_na(starts_with('depr_'))

set.seed(1)
lca3 <- poLCA(cbind(depr_w01, depr_w02, depr_w03, depr_w04, depr_w05) ~ 1,
        data = elsoc_depr_lca , nclass = 3, na.rm = TRUE, maxiter = 5000, nrep = 30)
lca4 <- poLCA(cbind(depr_w01, depr_w02, depr_w03, depr_w04, depr_w05) ~ 1,
        data = elsoc_depr_lca , nclass = 4, na.rm = TRUE, maxiter = 5000, nrep = 30)
lca5 <- poLCA(cbind(depr_w01, depr_w02, depr_w03, depr_w04, depr_w05) ~ 1,
        data = elsoc_depr_lca , nclass = 5, na.rm = TRUE, maxiter = 5000, nrep = 30)

elsoc_depr_lca$class3 <- as.factor(lca3$predclass)
elsoc_depr_lca$class4 <- as.factor(lca4$predclass)
elsoc_depr_lca$class5 <- as.factor(lca5 $predclass)

indicadores_lca <- function(x) {
  purrr::map_df(.x = x, .f = function(k) {
    data.frame(Nclases = length(k$P), 
               AIC = k$aic, 
               BIC = k$bic, 
               Nobs = k$Nobs, 
               Chisq = k$Chisq)
  })
}
```


```{r}
indicadores_lca(list(lca3, lca4, lca5))
```


```{r, results = 'hide'}


# Agregar etiquetas (4 clases)
elsoc_depr_lca$class_depr <- factor(elsoc_depr_lca$class4,
                             levels = c('1', '3', '4', '2'),
                             labels = c('Prevalencia baja de\nsíntomas de depresión',
                                        'Prevalencia media-baja de\nsíntomas de depresión',
                                        'Prevalencia media-alta de\nsíntomas de depresión',
                                        'Prevalencia alta de\nsíntomas de depresión'))

```


```{r, fig.cap = 'Perfiles de sintomatología depresiva: 4 clases (2016-2021)'}
      
elsoc_depr_lca %>%
    survey_design_elsoc(weights = 'ponderador02_w05') %>% 
    prop_list(depr_w01, depr_w02, depr_w03, depr_w04, depr_w05, 
              by = class_depr, na.rm = TRUE) %>%
    mutate(name = factor(name,
                         levels = glue::glue('depr_w0{1:5}'),
                         labels = c(2016:2019, 2021)),
           sintomas = factor(value,
                             levels = 1:4,
                             labels = c('Sin sintomas o síntomas\nde depresión mínima', 
                                  'Síntomas de\ndepresion media', 
                                  'Síntomas de\ndepresion moderada', 
                                  'Síntomas de depresion\nmoderada-severa o severa')),
           class_depr = factor(class_depr,
                                    labels = glue::glue("{get_labels(elsoc_depr_lca$class_depr)}\n ({scales::percent(elsoc_depr_lca %>% survey_design_elsoc(weights = 'ponderador02_w05') %>%
                                    prop(class_depr, na.rm = TRUE) %>%
                                    pull(prop), .1)})"))
           ) %>% 
    ggplot(aes(x = prop, y = fct_rev(name), fill = fct_rev(sintomas))) + 
    geom_col(position = 'stack') + 
    facet_grid(~ class_depr) +
    labs(y = "Ola del estudio", 
         x = "Proporción",
         fill = "") +
    scale_x_continuous(breaks = seq(0, 1, .25),
                       labels = scales::percent) +
    guides(fill = guide_legend(reverse = TRUE)) +
    theme_bw() + 
    theme(legend.position = "top", 
          plot.title = element_text(size = 14),
          axis.text.x = element_text(size = 8)) + 
    scale_fill_viridis_d(end = .85)

```



```{r, fig.cap = 'Cambios en síntomas de depresión, según perfiles de sintomatología depresiva (2016-2021)'}

elsoc_long_2016_2021 %>%
  left_join(elsoc_depr_lca %>% select(idencuesta, class_depr), by = 'idencuesta') %>%
  purrr::map_at(.at = vars(starts_with('s11_0')), 
                .f = function(s) car::recode(s, "1 = 0; 2 = 1; 3 = 2; c(4, 5) = 3; c(-888, -999) = NA")) %>%
  as.data.frame() %>%  
  dplyr::filter(tipo_atricion == 1) %>% 
  mutate(phq9 = (s11_01 + s11_02 + s11_03 + s11_04 + s11_05 + s11_06 + s11_07 + s11_08 + s11_09),
         depr = factor(car::recode(phq9, "0:4 = 1; 5:9 = 2; 10:14 = 3; 15:27 = 4"),
                       levels = c(1,2,3,4),
                       labels = c('Sin sintomas o síntomas\nde depresión mínima', 
                                  'Síntomas de\ndepresion media', 
                                  'Síntomas de\ndepresion moderada', 
                                  'Síntomas de depresion\nmoderada-severa o severa'))) %>% 
  as_label(ola) %>% 
  survey_design_elsoc() %>%
  svytable(~depr + class_depr + ola + idencuesta, design = .) %>% 
  as.data.frame() %>% 
  group_by(ola, class_depr) %>% 
  mutate(prop = Freq/sum(Freq)) %>%
  filter(Freq > 0) %>% 
  ggplot(aes(y = prop, x = ola, fill = fct_rev(depr), 
             stratum = fct_rev(depr), alluvium = idencuesta)) +
  theme_bw() +
  facet_wrap(~class_depr) +
  ggalluvial::geom_flow(alpha = .66) + 
  ggalluvial::geom_stratum(linetype = 0, width = .55) +
  scale_y_continuous(labels = scales::percent) + 
  ylab(label = NULL) +
  xlab(label = NULL) + 
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  scale_fill_viridis_d(end = .8) +
  # geom_text(data = function(x) { group_by(.data = x, ola, depr) %>%
  #     summarise(prop = sum(prop, na.rm = TRUE), idencuesta = 1) %>%
  #     ungroup()}, 
  #     aes(label = scales::percent(prop, accuracy = .1)),
  #     position = position_stack(vjust = .5),
  #     show.legend = FALSE) +
  #     # color = rep(c('white', 'white', 'black', 'black'), 2),
  #     #       size = 3) + 
  guides(fill = guide_legend(reverse = TRUE))


```


```{r, fig.cap = 'Perfiles de sintomatología depresiva, según sexo'}

elsoc_depr_lca %>% 
  filter(tipo_atricion == 1) %>% 
  survey_design_elsoc(weights = 'ponderador02_w05') %>% 
  prop(class_depr, by = m0_sexo_w05, na.rm = TRUE) %>% 
  sjlabelled::as_label(class_depr, m0_sexo_w05) %>%
  ggplot(aes(x = prop, y = m0_sexo_w05, 
                   fill = fct_rev(class_depr),
              label = scales::percent(prop, accuracy = .1))) +
  theme_bw() +   
  geom_col() +
  geom_text(position = position_stack(vjust = .5), size = 3,
            color = rep(c('black', 'black', 'white', 'white'), 2)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_x_continuous(labels = scales::percent) +
  scale_fill_viridis_d(begin = .1, end = .8, direction = 1, option = 'viridis') +
  theme(legend.position = 'top',
        legend.title = element_blank())  + 
  guides(fill = guide_legend(reverse = TRUE))


```

```{r, fig.cap = 'Perfiles de sintomatología depresiva, según tramo de edad (en 2021)'}

elsoc_depr_lca %>% 
  filter(tipo_atricion == 1) %>% 
  survey_design_elsoc(weights = 'ponderador02_w05') %>% 
  mutate(edadt = factor(car::recode(m0_edad_w05, "18:29 = 1; 30:49 = 2; 50:64 = 3; 65:150 = 4"),
                        labels = c('18-29', '30-49', '50-64', '65 o más'))) %>% 
  prop(class_depr, by = edadt, na.rm = TRUE) %>% 
  sjlabelled::as_label(class_depr, edadt) %>%
  ggplot(aes(x = prop, y = edadt, 
                   fill = fct_rev(class_depr),
              label = scales::percent(prop, accuracy = .1))) +
  theme_bw() +   
  geom_col() +
  geom_text(position = position_stack(vjust = .5), size = 3,
            color = rep(c('black', 'black', 'white', 'white'), 4)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_x_continuous(labels = scales::percent) +
  scale_fill_viridis_d(begin = .1, end = .8, direction = 1, option = 'viridis') +
  theme(legend.position = 'top',
        legend.title = element_blank())  + 
  guides(fill = guide_legend(reverse = TRUE))

```



## Parte economía:

```{r}


elsoc_long_2016_2021 %>%
  filter(ola == 5, tipo_atricion == 1 & !is_nsnr(m02)) %>% 
  mutate(sit_ocup = factor(car::recode(m02, "1:3 = 1; 7 = 2; 6 = 3; 5 = 4; c(4, 8, 9) = 5"), 
                           levels = c(1, 2, 3, 4, 5),
                           labels = c("Trabajo remunerado", "Trabajo doméstico\nno remunerado", "Desempleado/a", "Jubilado/a o\npensionado/a", "Otros (inactivos)"))
         ) %>% 
  prop(sit_ocup, by = m0_sexo, na.rm = TRUE) %>% 
  as_label(m0_sexo) %>% 
  ggplot(aes(y = prop, x = m0_sexo, fill = fct_rev(sit_ocup),
             label = scales::percent(ifelse(prop>.01, prop, NA), accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'stack') +
  geom_text(position = position_stack(vjust = .5), size = 3,
            color = rep(c('white', 'white', 'white', 'black', 'black'), 2)) +
  scale_y_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
    guides(fill = guide_legend(reverse = TRUE))+
  scale_fill_viridis_d(end = .85, direction = -1)

```


```{r}

elsoc_long_2016_2021 %>%
  filter(ola %in% 4:5) %>% 
  mutate(sit_ocup = factor(car::recode(m02, "1:3 = 1; 7 = 2; 6 = 3; 5 = 4; c(4, 8, 9) = 5"), 
                           levels = c(1, 2, 3, 4, 5),
                           labels = c("Trabajo remunerado", "Trabajo doméstico\nno remunerado", "Desempleado/a", "Jubilado/a o\npensionado/a", "Otros (inactivos)"))
         ) %>% 
  as_label(ola, m0_sexo) %>% 
  dplyr::filter(tipo_atricion == 1 & !is_nsnr(m02)) %>% 
  survey_design_elsoc() %>%
  svytable(~sit_ocup + ola + m0_sexo + idencuesta, design = .) %>% 
  as.data.frame() %>% 
  group_by(ola, m0_sexo) %>% 
  mutate(prop = Freq/sum(Freq)) %>%
  filter(Freq > 0) %>% 
  ggplot(aes(y = prop, x = ola, fill = fct_rev(sit_ocup), 
             stratum = fct_rev(sit_ocup), alluvium = idencuesta)) +
  theme_bw() +
  facet_wrap(~m0_sexo) +
  ggalluvial::geom_flow(alpha = .66) + 
  ggalluvial::geom_stratum(linetype = 0, width = .55) +
  scale_y_continuous(labels = scales::percent) + 
  ylab(label = NULL) +
  xlab(label = NULL) + 
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  scale_fill_viridis_d(direction = -1, end = .9) +
  geom_text(data = function(x) { group_by(.data = x, ola, m0_sexo, sit_ocup) %>%
      summarise(prop = sum(prop, na.rm = TRUE), idencuesta = 1) %>%
      ungroup()}, 
      aes(label = scales::percent(ifelse(prop>.01, prop, NA), accuracy = .1)),
      position = position_stack(vjust = .5),
      show.legend = FALSE,
      color = rep(c('white', 'white', 'white', 'black', 'black'), 4),
            size = 3, na.rm = TRUE) +
  guides(fill = guide_legend(reverse = TRUE))


```



```{r}

elsoc_long_2016_2021 %>% 
  filter(ola == 5 & tipo_atricion == 1, !is_nsnr(m02, m60)) %>% 
  mutate(m60 = ifelse(m02 %in% 1:3, m60, 4)) %>% 
  prop(m60, by = m0_sexo, na.rm = TRUE) %>% 
  as_label(m0_sexo) %>% 
  mutate(m60 = factor(m60, levels = 1:4,
                      labels = c('Trabajo de manera\ncompleta desde el hogar',
                                 'Trabajo de manera\n parcial en el hogar',
                                 'Trabajo fuera del hogar',
                                 'Sin trabajo remunerado'))) %>% 
  ggplot(aes(y = prop, x = m60, fill = m0_sexo,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1, option = 'viridis') +
  geom_text(vjust = -0.5,
            position = position_dodge(width = .9),
            size = 3)  + 
  theme(legend.position = 'top', legend.title = element_blank()) + 
  ggtitle('Trabajo remoto (2021)',
          'Porcentaje que trabaja en modalidad...')

```


```{r}
elsoc_clase <- elsoc_long_2016_2021 %>% 
  mutate(m30 = as.numeric(car::recode(m30, "1 = 110000; 2 = 251000; 
  3 = 305000; 4 = 355000; 5 = 400000; 
  6 = 445000; 7 = 490000; 8 = 535000; 9 = 585000; 10 = 640000; 
  11 = 700000; 12 = 765000; 13 = 845000; 14 = 935000; 15 = 1040000;
  16 = 1180000; 17 = 1375000; 18 = 1670000; 19 = 2275000; 20 = 2700000; NA = NA")),
  m30b = as.numeric(car::recode(m30b, "1 = 170000; 2 = 300000; 3 = 400000; 4 = 600000; 5 = 1200000; NA = NA")),
  m29_imp = ifelse(!is.na(m29), m29, ifelse(ola == 5, m30b, m30))) %>% 
  group_by(ola) %>% 
  mutate(quintil = xtile(m29, n = 5, wt = ponderador02),
         quintil = factor(quintil, levels = 1:5, labels = glue::glue('Quintil {1:5}'))) %>%
  ungroup() %>% 
  mutate(clase_sub = 
           factor(car::recode(d01_01, "0:2 = 1; 3:4 = 2; 5 = 3; 6:7 = 4; 8:10 = 5"),
                  levels = 1:5,
                  labels = c('Baja', 'Media baja', 'Media', 'Media alta', 'Alta'))) %>% 
  left_join(elsoc_egp, by = c('idencuesta', 'ola')) %>% 
  select(idencuesta, ola, quintil, egp07, egp11, clase_sub)

```

```{r}
elsoc_long_2016_2021 %>% 
  left_join(elsoc_clase, by = c('idencuesta', 'ola')) %>% 
  filter(tipo_atricion == 1, ola == 5) %>% 
  mutate(egp07 = factor(egp07, levels = 1:7,
                        labels = c('Clase alta',
                                   'Clase gestión bajo',
                                   'Rutina no-manual',
                                   'Pequeños propietarios\ne independientes',
                                   'Técnicos y supervisores',
                                   'Trabajadores calificados',
                                   'Clase operarios'))) %>% 
  prop(egp07, na.rm = TRUE) %>% 
  as_label(egp07) %>%
  ggplot(aes(x = prop, y = fct_rev(egp07), 
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'dodge2', fill = viridis::viridis(1, begin = .66)) +
  scale_x_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  geom_text(hjust = -.1,
            position = position_dodge(width = .9),
            size = 3)
  
```

```{r}
elsoc_long_2016_2021 %>% 
  left_join(elsoc_clase, by = c('idencuesta', 'ola')) %>% 
  filter(tipo_atricion == 1, ola == 5, !is.na(egp07)) %>% 
  mutate(egp07 = factor(egp07, levels = 1:7,
                        labels = c('Clase alta',
                                   'Clase gestión bajo',
                                   'Rutina no-manual',
                                   'Pequeños propietarios\ne independientes',
                                   'Técnicos y supervisores',
                                   'Trabajadores calificados',
                                   'Clase operarios'))) %>% 
  prop(quintil, by = egp07, na.rm = TRUE) %>% 
  as_label(quintil, egp07) %>% 
  ggplot(aes(x = prop, y = fct_rev(egp07), fill = fct_rev(quintil), 
             label = ifelse(prop>.01, scales::percent(prop, accuracy = .1), ''))) + 
  theme_bw() + 
  geom_col(position = 'stack') +
  scale_x_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  geom_text(position = position_stack(vjust = .5),
            size = 3, 
            color = rep(c(rep('white', 3), rep('black', 2)), 7))  +
  scale_fill_viridis_d(end = .85, direction = -1) +
  guides(fill = guide_legend(reverse = TRUE)) +
  theme(legend.position = 'top',
        legend.title = element_blank())
  
```



```{r}
elsoc_long_2016_2021 %>% 
  left_join(elsoc_clase, by = c('idencuesta', 'ola')) %>% 
  filter(tipo_atricion == 1, ola == 5, !is.na(egp07), !is_nsnr(m01)) %>% 
  mutate(egp07 = factor(egp07, levels = 1:7,
                        labels = c('Clase alta',
                                   'Clase gestión bajo',
                                   'Rutina no-manual',
                                   'Pequeños propietarios\ne independientes',
                                   'Técnicos y supervisores',
                                   'Trabajadores calificados',
                                   'Clase operarios')),
         educ = factor(car::recode(m01, recodes = "1:3 = 1; 4:5 = 2; 6:7 = 3; 8:10 = 4"),
                       levels = 1:4,
                       labels = c("Basica", "Media", "Tecnica", "Universitaria"))) %>% 
  prop(educ, by = egp07, na.rm = TRUE) %>% 
  as_label(educ, egp07) %>% 
  ggplot(aes(x = prop, y = fct_rev(egp07), fill = fct_rev(educ), 
             label = ifelse(prop>.01, scales::percent(prop, accuracy = .1), ''))) + 
  theme_bw() + 
  geom_col(position = 'stack') +
  scale_x_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  geom_text(position = position_stack(vjust = .5),
            size = 3, 
            color = rep(c(rep('white', 2), rep('black', 2)), 7))  +
  scale_fill_viridis_d(end = .85, direction = -1) +
  guides(fill = guide_legend(reverse = TRUE)) +
  theme(legend.position = 'top',
        legend.title = element_blank())
  
```



```{r}
elsoc_long_2016_2021 %>% 
  left_join(elsoc_clase, by = c('idencuesta', 'ola')) %>% 
  filter(tipo_atricion == 1) %>% 
  mutate(egp07 = factor(egp07, levels = 1:7,
                        labels = c('Clase alta',
                                   'Clase gestión bajo',
                                   'Rutina no-manual',
                                   'Pequeños propietarios\ne independientes',
                                   'Técnicos y supervisores',
                                   'Trabajadores calificados',
                                   'Clase operarios'))) %>% 
  prop(egp07, by = ola, na.rm = TRUE) %>% 
  as_label(egp07, ola) %>%
  ggplot(aes(y = prop, x = ola, fill = egp07, 
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'stack') +
  scale_y_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  geom_text(position = position_stack(vjust = .5),
            size = 3,
            color = rep(c(rep('black', 3), rep('white', 4)), 3))  + 
  scale_fill_viridis_d(end = .85, direction = -1) +
  theme(legend.position = 'top',
        legend.title = element_blank())
  
```



```{r, fig.cap = 'Porcentaje que posee deudas con..., según ola'}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & ola %in% c(1, 3, 5),
         !is_nsnr(m42_01, m42_02, m42_03, m42_04)) %>% 
  pivot_longer(cols = c(m42_01, m42_02, m42_03, m42_04)) %>% 
  prop(value == 1, by = c(ola, name), na.rm = TRUE) %>% 
  as_label(ola) %>% 
  mutate(name = factor(name, 
                       levels = c('m42_01', 'm42_02', 'm42_03', 'm42_04'),
                       labels = c('Casa\ncomercial', 'Banco', 
                                  'Parientes', 'Otros'))) %>% 
  ggplot(aes(y = prop, x = name, fill = ola, 
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_col(position = "dodge2") +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(end = .85, direction = -1, option = 'viridis') + 
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75)  +
  theme(legend.position = 'top',
        legend.title = element_blank())

```


```{r clase.sub-benef.estatal, fig.cap = 'Porcentaje que accedió a beneficios y retiro del 10%'}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1, ola == 5, !is_nsnr(m63_01, m63_02, m63_03)) %>% 
  prop_list(m63_01 == 1, m63_02 == 1, m63_03 == 1, na.rm = TRUE) %>% 
  mutate(name = factor(name,
                       levels = glue::glue('m63_0{1:3} == 1'),
                       labels = c('Beneficios del Estado',
                                  'Primer retiro 10% AFP',
                                  'Segundo retiro 10% AFP'))) %>% 
  ggplot(aes(y = prop, x = name, fill = name,
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_col() +
  scale_y_continuous(labels = scales::percent, limits = 0:1) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .85, direction = -1) +
  geom_text(position = position_dodge(.9),
            vjust = -.5,
            size= 2.75) + 
  theme(legend.position = 'none')

```


```{r, fig.cap = 'Porcentaje que accedió a beneficios y retiro del 10%, según quintil'}

elsoc_long_2016_2021 %>% 
  left_join(elsoc_clase, by = c('idencuesta', 'ola')) %>% 
  filter(tipo_atricion == 1, ola == 5, !is_nsnr(m63_01, m63_02, m63_03), !is.na(quintil)) %>% 
  prop_list(m63_01 == 1, m63_02 == 1, m63_03 == 1, by = quintil, na.rm = TRUE) %>%  
  mutate(name = factor(name,
                       levels = glue::glue('m63_0{1:3} == 1'),
                       labels = c('Beneficios del Estado',
                                  'Primer retiro 10% AFP',
                                  'Segundo retiro 10% AFP'))) %>% 
  ggplot(aes(y = prop, x = name, fill = quintil,
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent, limits = 0:1) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(end = .85) +
  geom_text(position = position_dodge(.9),
            vjust = -.5,
            size= 2.75) + 
  theme(legend.position = 'top',
        legend.title = element_blank())

```


```{r}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & ola == 5,
         !is_nsnr(m42_01, m42_02, m42_03, m42_04),
         !is_nsnr(m63_01, m63_02, m63_03)) %>% 
  pivot_longer(cols = c(m63_01, m63_02, m63_03),
               names_to = 'retiro', values_to = 'si_retiro') %>% 
  prop_list(m42_01 == 1, m42_02 == 1, m42_03 == 1, m42_04 == 1,
            by = c(retiro, si_retiro), na.rm = TRUE) %>% 
  filter(!is.na(si_retiro)) %>% 
  mutate(retiro = factor(retiro,
                       levels = glue::glue('m63_0{1:3}'),
                       labels = c('Beneficios del Estado',
                                  'Primer retiro 10% AFP',
                                  'Segundo retiro 10% AFP')),
         name = factor(name, 
                       levels = glue::glue('m42_0{1:4} == 1'),
                       labels = c('Casa\ncomercial', 'Banco', 
                                  'Parientes', 'Otros')),
         si_retiro = factor(si_retiro, levels = 1:2,
                               labels = c('Realizó retiro/recibió beneficio', 'No realizó retiro/no recibió beneficio'))) %>% 
  ggplot(aes(y = prop, x = name, fill = si_retiro, 
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  facet_wrap(~retiro) + 
  geom_col(position = "dodge2") +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1, option = 'viridis') + 
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75)  +
  theme(legend.position = 'top',
        legend.title = element_blank())


```


## COVID - 19


```{r covid-sexo, fig.align='center'}

elsoc_long_2016_2021 %>% 
  dplyr::filter(ola == 5, tipo_atricion == 1 & !is_nsnr(s31) & !is_nsnr(r03_09)) %>%
  prop_list(s31 == 1, r03_09 > 1, na.rm = TRUE) %>% 
  mutate(name = factor(name, levels = c('s31 == 1', 'r03_09 > 1'),
                       labels = c('Fue diagnosticado con COVID-19',
                                  'Tiene al menos un conocido/a que\nfue diagnosticado con COVID-19'))) %>% 
  ggplot(aes(y = prop, x = name, fill = name,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1, option = 'viridis') +
  geom_text(vjust = -0.5,
            position = position_dodge(width = .9),
            size = 3)  + 
  theme(legend.position = 'none') + 
  ggtitle('Cercanía de contagio de covid',
          'Porcentaje que...')

```


```{r, fig.align='center'}

elsoc_long_2016_2021 %>% 
  dplyr::filter(ola == 5, tipo_atricion == 1 & !is_nsnr(r03_09)) %>%
  mutate(r03_09 = factor(car::recode(r03_09, "4:7 = 4"),
                         levels = 1:4,
                         labels = c('No conoce a nadie que haya\nsido diagnosticado con COVID-19', 
                                    'Conoce a 1', 'Conoce entre 2 y 4', 'Conoce a 5 o más'))) %>% 
  prop(r03_09, na.rm = TRUE) %>% 
  as_label(r03_09) %>% 
  ggplot(aes(y = prop, x = r03_09, fill = r03_09,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1, option = 'viridis') +
  geom_text(vjust = -0.5,
            position = position_dodge(width = .9),
            size = 3)  + 
  theme(legend.position = 'none') + 
  ggtitle('Distribución de los encuestados,\nsegún número de conocidos que han sido diagnosticados de covid (2021)')

```


```{r depre clase.sub, fig.cap = 'Cercanía de contagio de covid, según clase social (2021)'}

elsoc_long_2016_2021 %>% 
  left_join(elsoc_clase) %>% 
  dplyr::filter(ola == 5, tipo_atricion == 1,
                !is_nsnr(s31, r03_09, d01_01) & !is.na(quintil)) %>%
  prop_list(s31 == 1, r03_09 > 1, by = quintil, na.rm = TRUE) %>% 
  mutate(name = factor(name, levels = c('s31 == 1', 'r03_09 > 1'),
                       labels = c('Fue diagnosticado con COVID-19',
                                  'Tiene al menos un conocido/a que\nfue diagnosticado con COVID-19'))) %>%
  ggplot(aes(y = prop, x = name, fill = quintil,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .75, direction = -1, option = 'viridis') +
  geom_text(vjust = -0.5,
            position = position_dodge(width = .9),
            size = 3)  + 
  theme(legend.position = 'top',
        legend.title = element_blank())

```


```{r, fig.cap = 'Cercanía de contagio de covid, según clase social (2021)'}

elsoc_long_2016_2021 %>% 
  left_join(elsoc_clase, by = c('idencuesta', 'ola')) %>% 
  dplyr::filter(ola == 5, tipo_atricion == 1,
                !is_nsnr(s31, r03_09, d01_01) & !is.na(egp07)) %>%
  mutate(egp07 = factor(egp07, levels = 1:7,
                        labels = c('Clase alta',
                                   'Clase gestión bajo',
                                   'Rutina no-manual',
                                   'Pequeños propietarios\ne independientes',
                                   'Técnicos y supervisores',
                                   'Trabajadores calificados',
                                   'Clase operarios'))) %>% 
  prop_list(s31 == 1, r03_09 > 1, by = egp07, na.rm = TRUE) %>% 
  mutate(name = factor(name, levels = c('s31 == 1', 'r03_09 > 1'),
                       labels = c('Fue diagnosticado con COVID-19',
                                  'Tiene al menos un conocido/a que\nfue diagnosticado con COVID-19'))) %>%
  ggplot(aes(y = prop, x = name, fill = egp07,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() +
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .75, direction = -1, option = 'viridis') +
  geom_text(vjust = -0.5,
            position = position_dodge(width = .9),
            size = 3)  + 
  theme(legend.position = 'top',
        legend.title = element_blank())

```


```{r dist-total, fig.align='center', fig.cap='¿En qué medida usted ha seguido la recomendación de quedarse en su hogar, manteniendo el aislamiento social? (2021).'}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & ola == 5,
         !is_nsnr(c48)) %>% 
  mutate(c48 = factor(car::recode(c48, "1:2 = 1; 3 = 2; 4:5 = 3"),
                               levels = 1:3,
                               labels= c("Nunca o casi nunca", "A veces",
                                         "Frecuentemente o\nmuy frecuentemente"))) %>%
  prop(c48, na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = c48, fill = c48, 
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                      limits = 0:1) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .85, direction = -1, option = 'viridis') +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75) +
  theme(legend.position = 'none', 
        legend.title = element_blank())

```


```{r}


elsoc_long_2016_2021 %>% 
  left_join(elsoc_clase) %>% 
  dplyr::filter(ola == 5, tipo_atricion == 1, !is_nsnr(c48),
                !is_nsnr(s31, r03_09, d01_01) & !is.na(quintil)) %>%
  mutate(c48 = factor(car::recode(c48, "1:2 = 1; 3 = 2; 4:5 = 3"),
                               levels = 1:3,
                               labels= c("Nunca o casi nunca", "A veces",
                                         "Frecuentemente o\nmuy frecuentemente"))) %>%
  prop_list(s31 == 1, r03_09 > 1, by = c48, na.rm = TRUE) %>% 
  mutate(name = factor(name, levels = c('s31 == 1', 'r03_09 > 1'),
                       labels = c('Fue diagnosticado con COVID-19',
                                  'Tiene al menos un conocido/a que\nfue diagnosticado con COVID-19'))) %>%
  ggplot(aes(y = prop, x = name, fill = c48,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .75, direction = -1, option = 'viridis') +
  geom_text(vjust = -0.5,
            position = position_dodge(width = .9),
            size = 3)  + 
  theme(legend.position = 'top',
        legend.title = element_blank())



```

```{r, fig.cap='Cumplimiento de distaniamiento social (2021), según quintiles de ingreso'}

elsoc_long_2016_2021 %>% 
  left_join(elsoc_clase, by = c('idencuesta', 'ola')) %>% 
  filter(tipo_atricion == 1 & ola == 5,
         !is_nsnr(c48)) %>% 
  prop(c48 %in% 4:5, by = quintil, na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = quintil, fill = quintil, 
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                      limits = 0:1) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .85, direction = -1, option = 'viridis') +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75) +
  theme(legend.position = 'none', 
        legend.title = element_blank())

```

