---
editor_options: 
  markdown: 
    wrap: 72
---

# Principales hallazgos longitudinales

**Nota Explicativa**

A continuación, se presentan los principales resultados de la encuesta ELSOC elaborados por investigadores del Centro de Conflicto y Cohesión Social (COES). Dada la diversidad de temas que son abordados en la encuesta, los investigadores colaboradores utilizaron diversos enfoques teóricos y herramientas empíricas en su análisis. Sin embargo, en Radiografía del Cambio Social se han definido una serie de criterios comunes para el desarrollo de resultados empíricos:

- Foco en la evolución y cambio en las actitudes de la población, aún cuando en ocasiones se analizan preguntas incluidas en una o dos olas del estudio. 
- Uso de pruebas estadísticas específicas para el análisis longitudinal. 
- Utilización de submuestra de XXXX participantes del estudio presentes en las cinco mediciones (2016, 2017, 2018, 2019 y 2021). 
- Tamaños muestrales reportados menores se explican exclusivamente por no respuesta a ítemes específicos.
- Utilización del diseño muestral complejo (ponderador muestral ajustado a población regional y sexo, estrato y conglomerado muestral) en el desarrollo de figuras descriptivas y pruebas inferenciales. 


**Levantamiento durante COVID-19**


