# Referencias

Abascal M, Baldassarri D. Love Thy Neighbor? Ethnoracial Diversity and Trust Reexamined. AJS. 2015 Nov;121(3):722-82. doi: 10.1086/683144. PMID: 26900618.

Agostini, C, Hojman, D, Román, A, & Valenzuela, L. (2016). Segregación residencial de ingresos en el Gran Santiago, 1992-2002: una estimación robusta. EURE (Santiago), 42(127), 159-184. https://dx.doi.org/10.4067/S0250-71612016000300007

Akerlof, G. A., & Kranton, R. E. (2000). Economics and identity. The quarterly journal of economics, 115(3), 715-753.

Angst J, Gamma A, Rossler W, Ajdacic V, Klein DN. (2009) Long-term depression versus episodic major depression: results from the prospective Zurich study of a community sample. J Affect Disord, 115: 112-121.

Bavel JJ Van, Baicker K, Boggio PS, Capraro V, Cichocka A, Cikara M, et al. (2020) Using social and behavioural science to support COVID-19 pandemic response. Nature Human Behaviour, 4(5):460–471.

Brunoni A, Santosa I, Passosd I, Goulartc A, Koyanagi A, Carvalho A, Barreto S, Viana M, Lotufo P, Benseñor I (2020) Socio-demographic and psychiatric risk factors in incident and persistent depression: An analysis in the occupational cohort of ELSA-Brasil. Journal of Affective Disorders, 263: 252-257.
Curley, A. M. (2010). Relocating the poor: Social capital and neighborhood resources. Journal of urban affairs, 32(1), 79-103.

Delaney, J. M., & Devereux, P. J. (2019). More education, less volatility? The effect of education on earnings volatility over the life cycle. Journal of Labor Economics, 37(1), 101-137.

Delhey, J., & Newton, K. (2003). Who Trusts? The Origins of Social Trust in Seven Societies. European Societies, 5(2), 93-137

Di Tella, R., Galiani, S., & Schargrodsky, E. (2010). 5. Crime Distribution and Victim Behavior during a Crime Wave. In The Economics of Crime (pp. 175-206). University of Chicago Press.

Dincer, O. C., & Uslaner, E. M. (2010). Trust and growth. Public Choice, 142(1–2), 59. https://doi.org/10.1007/s11127-009-9473-4

Donnelly R, Farina M.P. (2021) How do state policies shape experiences of household income shocks and mental health during the COVID-19 pandemic? Social Science & Medicine, 269: 113557.

Downs, A. (1981). Neighborhoods and urban development. Washington, DC: Brookings Institute

Duarte F, Jiménez-Molina A (2021) Psychological distress during the COVID-19 epidemic in Chile: the role of economic uncertainty. PLoS ONE, 16(11): e0251683.

Duarte F. and Jiménez A (en evaluación) Psychosocial and economic dimensions related to mental health during the COVID-19 pandemic in Chile: Challenges for social policy.
Easton, D. (1975). A Re-Assessment of the Concept of Political Support. British Journal of Political Science, 5(4), 435-457.

Ettman C, Abdalla S, Cohen G, Sampson L, Vivier P, Galea S (2020) Prevalence of depression symptoms in US adults before and during the COVID-19 pandemic. JAMA 3(9): e2019686.

Flores, B. (2021). La importancia de las interacciones entre vecinos con lazos sociales débiles para incrementar la participación laboral femenina en Chile. Estudios Públicos, (163), 7-47.

Fukuyama, F. (1996). Trust: Human nature and the reconstitution of social order. Simon and Schuster.

Gabriel M Leung (2020) Depression and post-traumatic stress during major social unrest in Hong Kong: a 10-year prospective cohort study. Lancet, 395(10220): 273-284.

Garcia-Toro M, Rubio J, Gili M, Roca M, Jin C, Liu S, Bastianoni C, Blanco C (2013) Persistence of chronic major depression: A national prospective study. Journal of Affective Disorders, 151: 306-312.

Garretón, M. (2017) City profile: Actually existing neoliberalism in Greater Santiago. Cities 65, 32-50

Granovetter, M. S. (1973). The strength of weak ties. American journal of sociology, 78(6), 1360-1380.

Hammarström A, Lehti A, Danielsson U, Bengs C, Johansson E. (2009) Gender-related explanatory models of depression: A critical evaluation of medical articles. Public Health, 123: 689-693.

Hardeveld F, Spijker J, De Graaf R, Nolen W, Beekman A (2010) Prevalence and predictors of recurrence of major depressive disorder in the adult population. Acta Psychiatrica Scandinavica, 122(3): 184-191.

Hojman D, Miranda A, Ruiz-Tagle J (2016) Debt trajectories and mental health. Social Science & Medicine, 167: 54-62.

Hyland P, Shevlin M, Murphy J et al. (2021) A longitudinal assessment of depression and anxiety in the Republic of 

Ireland during the COVID-19 pandemic. Psychiatry Research 300: 113905.

Jiménez A, Reyes P, Rojas G (2021) Determinantes socioeconómicos y brechas de género de la sintomatología depresiva en Chile. Revista Médica de Chile, 149: 533-542.

Kahneman D & Deaton A (2010) High income improves evaluation of life but not emotional well-being. PNAS, 107(38): 16489-16493.

Kessler R, Berglund P, Demler O, Jin R, Koretz D, Merikangas K, et al. (2003) The epidemiology of major depressive disorder: results from the National Comorbidity Survey Replication (NCS-R). JAMA, 289(23): 3095-105.

Kinderman P, Tai S, Pontin E, Schwannauer M, Jarman I, Lisboa P. (2015) Causal and mediating factors for anxiety, depression and well-being. Br J Psychiatry, 206 (6): 456-60.

Kroenke K, Spitzer R, Williams J. (2001) The PHQ-9: Validity of a brief depression severity measure. J Gen Intern Med, 16(9): 606–613.

Krosnick, J. A., & Alwin, D. F. (1989). Aging and susceptibility to attitude change. Journal of personality and social psychology, 57(3), 416.

Levis B, Benedetti A, Thombs B, and DEPRESSD Collaboration (2019) Accuracy of Patient Health Questionnaire-9 (PHQ-9) for screening to detect major depression: individual participant data meta-analysis. BMJ, 365: 1476.

Link, F, Valenzuela, F, & Fuentes, L. (2015). Segregación, estructura y composición social del territorio metropolitano en Santiago de Chile: Complejidades metodológicas en el análisis de la diferenciación social en el espacio. Revista de geografía Norte Grande, (62), 151-168. https://dx.doi.org/10.4067/S0718-34022015000300009

Link, F. & Valenzuela, F. 2018. La estructura de la densidad sociorresidencial en el área metropolitana de Santiago. Proyecto Fondecyt N° 1161550. Instituto de Estudios Urbanos y Territoriales UC, Documentos de Trabajo del IEUT 3.

Lorant V, Deliege D, Eaton W, Robert A, Philippot P, Ansseau M. (2003) Socioeconomic inequalities in depression: a meta-analysis. Am J Epidemiol, 157(2): 98-112.

Lund C, Brooke-Summer C, Baingana F, Baron E, Breuer E, Chandra P, et al. (2018) Social determinants of mental disorders and the Sustainable Development Goals: a systematic review of reviews. Lancet Psychiatry, 5: 357-69.

Lund C, Carrie Brooke-Sumner, Florence Baingana, Emily Claire Baron, Erica Breuer, Prabha Chandra, Johannes Haushofer, et al. (2018) Social determinants of mental disorders and the Sustainable Development Goals: a systematic review of reviews. Lancet Psychiatry, 5: 357-369.

Magaña I, Martínez P, Loyola M (2020) Health outcomes of unpaid caregivers in low- and middle-income countries: a systematic review and meta-analysis. Journal of Clinical Nursing, 29(21-22): 3950-3965.

Marsden, P. V., & Campbell, K. E. (1984). Measuring tie strength. Social forces, 63(2), 482-501.

McCue, C. P., & Norris‐Tirrell, D. (2002). The impact of immigration policy on communities: An introduction to the symposium. Policy Studies Journal, 30(1), 53-57.

McGinty E, Presskreischer R, Anderson K, Han H, Barry C (2020) Psychological distress and COVID-19–related stressors reported in a longitudinal cohort of US adults in April and July 2020. JAMA 324(24): 2555-2557.

Méndez, M. L., Otero, G., Link, F., López Morales, E., & Gayo, M. (2021). Neighbourhood cohesion as a form of privilege. Urban Studies, 58(8), 1691-1711.

Michael Y Ni, Xiaoxin I Yao, Kathy S M Leung, Cynthia Yau, Candi M C Leung, Phyllis Lun, Francis P Flores, Wing Chung Chang, Benjamin J Cowling,

MINSAL (2018) Encuesta Nacional de Salud 2016-2017. Santiago: MINSAL.

Musliner K, Munk-Olsen T, Eaton W, and Zandi P (2016) Heterogeneity in long-term trajectories of depressive symptoms: Patterns, predictors and outcomes. J Affect Disord, 192: 199-211.

Newton, K., & Norris, P. (1999). Confidence in Public Institutions: Faith, Culture or Performance? Annual Meeting of the American Political Science Association, Atlanta, 1-5th (pp. 1-33). Atlanta: Harvard University. John F. Kennedy School of Government.

Newton, K., & Zmerli, S. (2011). Three forms of trust and their association. European Political Science Review: EPSR, 3(2), 169. https://doi.org/10.1017/S1755773910000330

Ni MY, Kim Y, McDowell I, Wong S, Qiu H, Wong IO, Galea S, Leung GM. (2020) Mental health during and after protests, riots and revolutions: A systematic review. Aust N Z J Psychiatry, 54(3): 232-243.

Norris, P. (1999). Introduction: The Growth of Critical Citizens?. In P. Norris (Ed.), Critical Citizens: Global Support for Democratic Government. Oxford University Press.

Nübe J, Guhn A, Müllender S, Le H-D, Cohrdes C and Köhle S (2020) Persistent depressive disorder across the adult lifespan: results from clinical and population-based surveys in Germany. BMC Psychiatry, 20: 58.

O’Connor R, Wetherall K, Cleare S et al. (2020) Mental health and well-being during the COVID-19 pandemic: longitudinal analyses of adults in the UK COVID-19 Mental Health & Wellbeing study. British Journal of Psychiatry: 1-8.

Owen, A., Videras, J., & Wu, S. (2010). Identity and environmentalism: the influence of community characteristics. Review of social economy, 68(4), 465-486.

Perez-Roa L. (2020) Consumo, endeudamiento y economía doméstica: una historia en tres tiempos para entender el estallido social. En Hilos tensados, Para leer el octubre chileno (37-82). Chile: Colección IDEA y USACH.

Pierce M, Hope H, Ford T et al. (2020) Mental health before and during the COVID-19 pandemic: A longitudinal probability sample survey of the UK population. Lancet Psychiatry 7: 883-892.

Putnam, R. D., Leonardi, R., & Nanetti, R. Y. (1994). Making democracy work: Civic traditions in modern Italy. Princeton university press.

Rojas-Navarro S, Energici M, Schöngut-Grollmus N, Alarcón-Arcos S (2021) Im-posibilidades del cuidado: reconstrucciones del cuidar en la pandemia de la covid-19 a partir de la experiencia de mujeres en Chile. Antípoda, 45: 101-123.

Rosenthal L, Carroll-Scott A, Earnshaw V, Santilli A, and Ickovics J. (2012) The importance of full-time work for urban adults’ mental and physical health. Social Science & Medicine, 75(9): 1692-6.

Rubio JM, Markowitz JC, Alegria A, Perez-Fuentes G, Liu SM, Lin KH, et al. (2011) Epidemiology of chronic and nonchronic major depressive disorder: results from the national epidemiologic survey on alcohol and related conditions. Depress Anxiety, 28: 622-631.

Salk R, Hyde J, Abramson L. (2017) Gender differences in depression in representative national samples: meta-analyses of diagnoses and symptoms. Psychol Bulletin, 143(8): 783.

Schramm E, Klein D, Elsaesser M, Furukawa T, Domschke K (2020) Review of dysthymia and persistent depressive disorder: history, correlates, and clinical implications. Lancet Psychiatry, 7: 801-812.

Sehnbruch, K., & Donoso, S. (2020). Social Protests in Chile: Inequalities and other Inconvenient Truths about Latin America’s Poster Child. Global Labour Journal, 11(1). https://doi.org/10.15173/glj.v11i1.4217

Silver, B. D., Anderson, B. A., & Abramson, P. R. (1986). Who Overreports Voting? The American Political Science Review, 80(2), 613–624. https://doi.org/10.2307/1958277

Stuckler D & Basu S. (2013) The body economic: Why austerity kills. New York: Basic Books; 2013.

Sweet E, Nandi A, Adam E, McDade T. (2013) The high price of debt: household financial debt and its impact on mental and physical health. Social Science & Medicine, 91: 94-100.

United Nations (2020) Policy Brief: The Impact of COVID-19 on Women. Available on https://www.un.org/sexualviolenceinconflict/wp-content/uploads/2020/06/report/policy-brief-the-impact-of-covid-19-on-women/policy-brief-the-impact-of-covid-19-on-women-en-1.pdf.

Uslaner, E. M. (2002). The moral foundations of trust. Cambridge University Press.

Varady, D. P. (1986). Neighborhood confidence: A critical factor in neighborhood revitalization? Environment and Behavior, 18(4), 480-501.

Verba, S., Schlozman, K. L., & Brady, H. E. (1995). Voice and equality: Civic voluntarism in American politics. Harvard University Press.

Vicente B, Saldivia S, Pihán R (2016) Prevalencias y brechas hoy; salud mental mañana. Acta Bioethica 22(1): 51-61.

Wahlbeck K, McDaid D. (2012) Actions to alleviate the mental health impact of the economic crisis. World Psychiatry, 11: 139-145.

Wenham C, Smith J, Davies S, Feng H, Grépin K, Harman S, Herten-Crabb A, Morgan R (2020) Women are most affected by pandemics - lessons from past outbreaks. Nature 583: 194-198.

Westerhof GJ, Keyes CLM. (2010) Mental Illness and Mental Health: The Two Continua Model Across the Lifespan. J Adult Dev, 17 (2): 110-119.

Wu T, Jia X, Shi H, Niu J, Yin X, Xie J, Wang X (2021) Prevalence of mental health problems during the COVID-19 pandemic: A systematic review and meta-analysis. Journal of Affective Disorders, 281: 91-98.

Xiong J, Lipsitzc O, Nasric F, Luic L, Gillc H, Phanc L, Chen-Lic D, Iacobuccic M, Hoe R, Majeedc A, McIntyre R (2020) Impact of COVID-19 pandemic on mental health in the general population: A systematic review. Journal of Affective Disorders 277: 55-64.


# Como citar este informe: {-}

:::{.blue-box}
> COES (2021) Radiografía del Cambio Social: Análisis de Resultados Longitudinales ELSOC 2016-2021. Presentación de Resultados COES. Septiembre, Santiago de Chile.
:::

**Entrada Bibtex:**

```{r,echo=TRUE,eval=FALSE}
@techreport{coes_Radiografia_2021,
  title = {Radiograf\'ia Del {{Cambio Social}}: {{An\'alisis}} de {{Resultados Longitudinales ELSOC}} 2016-2021.},
  author = {COES},
  year = {2021},
  month = sep,
  address = {{Santiago de Chile, Chile}},
  institution = {{Centro de Estudios de Conflicto y Cohesi\'on Social}}
}
```
