---
editor_options: 
  markdown: 
    wrap: 72
---

# Movimientos Sociales y Acciones Colectivas



## Ciclo de movilización política y estallido social


<!-- ### 1.1 ¿Cuál es el movimiento social que usted más valora de esta lista? Según ola del estudio  -->

```{r diseno, include=FALSE}
elsoc_diseno <- svydesign(ids = ~segmento, #muestreo por conglomerado a nivel de manzanas (segmento)
                          strata = ~estrato, #muestreo estratificado a nivel ciudad (estato)
                          weights = ~ponderador02, #ponderador de corte transversal
                          nest = TRUE,
                          data = elsoc_panel_m1)
```

```{r include=FALSE}
datos.grafico1 <- data.frame((svytable(~mov + ola, elsoc_diseno, round = F))) %>%
  group_by(ola) %>% mutate(porcentaje=Freq/sum(Freq)) %>%
  na.omit()

datos.subset <- droplevels(subset(datos.grafico1, datos.grafico1$ola == '2019' | datos.grafico1$ola == '2021'))

```


```{r echo=FALSE}
graf.mov <-datos.subset %>% 
  ggplot(aes(y = porcentaje, x = mov, fill = ola, 
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0,0.3)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .85, direction = -1, option = 'viridis') +
  coord_flip() +
  theme(axis.text.x = element_text(size=rel(.9))) +
  scale_x_discrete(labels = waiver( ))

graf.mov

```



<!-- ### 1.2 Frecuencia de participación en movimientos sociales, según Ola de encuesta. Porcentaje que responde A veces, Frecuentemente o Muy frecuentemente  -->

```{r include=FALSE}
elsoc_panel_m1$freq_part <- car::recode(as.numeric(elsoc_panel_m1$c22), recodes = "c(1)=1; c(2,3,4,5)=2; else=NA", as.factor = TRUE)

elsoc_diseno <- svydesign(ids = ~segmento, #muestreo por conglomerado a nivel de manzanas (segmento)
                          strata = ~estrato, #muestreo estratificado a nivel ciudad (estato)
                          weights = ~ponderador02, #ponderador de corte transversal
                          nest = TRUE,
                          data = elsoc_panel_m1)
```

```{r include=FALSE}
datos.grafico2 <- data.frame((svytable(~freq_part + ola, elsoc_diseno, round = F))) %>%
  group_by(ola) %>% mutate(porcentaje=Freq/sum(Freq)) %>%
  na.omit()
datos.subset2 <- droplevels(subset(datos.grafico2, datos.grafico2$freq_part == '2'))

```


```{r echo=FALSE}
g_frqmov <- datos.subset2 %>% 
    ggplot(aes(y = porcentaje, x = ola, fill = freq_part, 
               label = as.character(scales::percent(porcentaje, accuracy = .1)))) +
  theme_bw() + 
    geom_col() +
    scale_y_continuous(labels = scales::percent,
                       limits = c(0, 1)) +
    ylab(label = NULL) +
    xlab(label = NULL) +
    scale_fill_viridis_d(begin = 0, end = .85, direction = -1, option = 'viridis') +
    geom_text(vjust = -0.8,
              position = position_dodge(width = .9),
              size= 2.75) +
    theme(legend.position = 'none',   ## Eliminar leyenda al no ser necesaria
          legend.title = element_blank())

g_frqmov
```


## Confianza en instituciones


<!-- ### 1.3 Confianza en el gobierno según ola 2018, 2019 y 2021 -->

```{r}
elsoc_panel_m1$conf_gob
elsoc_panel_m1$conf_gob <- car::recode(as.numeric(elsoc_panel_m1$c05_01), 
                                      recodes = "c(1)='Nada'; 
                                      c(2)='Poca'; c(3)='Algo'; 
                                      c(4)='Bastante';c(5)='Mucha'; 
                                      else=NA", as.factor = TRUE) 
```


```{r include=FALSE}
datos.grafico3 <- data.frame((svytable(~conf_gob + ola, elsoc_diseno, round = F))) %>%
  group_by(ola) %>% mutate(porcentaje=Freq/sum(Freq)) %>%
  na.omit()

```

```{r}
datos.subset2 <- droplevels(subset(datos.grafico3, datos.grafico3$ola == '2018' |datos.grafico3$ola == '2019' | datos.grafico3$ola == '2021'))
```


```{r}
graf.conf_gob <-datos.subset2 %>% 
  ggplot(aes(y = porcentaje, x = ola, fill = conf_gob, 
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1, option = 'viridis') +
  #cambiar geom_text tal que: Stack y cambio colores
  geom_text(position = position_stack(vjust = .5),
            size= 2.75, color = rep.int(c('black', 'white', 'white', 'white', 'white'), 15)) + 
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Confianza en el Presidente(a) de la República cada año')

graf.conf_gob 
```

<!-- ### 1.4 Confianza en el presidente según ola 2018, 2019 y 2021 -->

```{r}
elsoc_panel_m1$conf_pres
elsoc_panel_m1$conf_pres <- car::recode(as.numeric(elsoc_panel_m1$c05_08), 
                                      recodes = "c(1)='Nada'; 
                                      c(2)='Poca'; c(3)='Algo'; 
                                      c(4)='Bastante';c(5)='Mucha'; 
                                      else=NA", as.factor = TRUE) 
```


```{r include=FALSE}
datos.grafico4 <- data.frame((svytable(~conf_pres + ola, elsoc_diseno, round = F))) %>%
  group_by(ola) %>% mutate(porcentaje=Freq/sum(Freq)) %>%
  na.omit()

```

```{r}
datos.subset3 <- droplevels(subset(datos.grafico4, datos.grafico4$ola == '2018' |datos.grafico4$ola == '2019' | datos.grafico4$ola == '2021'))
```


```{r}
graf.conf_pres<-datos.subset3 %>% 
  ggplot(aes(y = porcentaje, x = ola, fill = conf_pres, 
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .85, direction = -1, option = 'viridis') +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75) +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
ggtitle('Confianza en el presidente según año')

graf.conf_pres
```


<!-- ### 1.6 Cambio en Frecuencia de participación en movimientos sociales entre 2018 y 2019, según posición ideológica del entrevistado (de año previo) -->
```{r include=FALSE}

```


