---
editor_options: 
  markdown: 
    wrap: 72
---

# Identificación Política



## Identificación política

### 2.1 Identificación política por ola

<!-- ### 2.1 Identificación política por ola -->

```{r echo=FALSE}
datos.2.1 <- data.frame((svytable(~pos_id + ola, elsoc_diseno, round = F))) %>%
  group_by(ola) %>% mutate(porcentaje=Freq/sum(Freq)) %>%
  na.omit()
```

```{r echo=FALSE}
g.2.1 <- datos.2.1 %>% 
    ggplot(aes(y = porcentaje, x = pos_id, fill = ola, 
               label = as.character(scales::percent(porcentaje, accuracy = .1)))) +
    theme_bw() + 
    geom_col(position= 'dodge2') +
    #escala del eje y en porcentajes del 0 al 100%
    scale_y_continuous(labels = scales::percent,
                       limits = c(0, 1)) +
    #Nombres de los ejes se eliminan
    ylab(label = NULL) +
    xlab(label = NULL) +
    #colores oficiales por ola: degradé 'viridis'
    scale_fill_viridis_d(begin = 0, end = .85, direction = -1, option = 'viridis') +
    #etiquetas por sobre cada barra
    geom_text(vjust = -0.8,
              position = position_dodge(width = .9),
              size= 2.75) +
    #posicionamiento de leyenda arriba
    theme(legend.position = 'top',
          legend.title = element_blank())

g.2.1
```
### 2.2 Alluvial de cambios de Identificación política

<!-- ### 2.2 Alluvial de cambios de Identificación política (+o-) -->

```{r include=FALSE}
datos.2.2 <- data.frame((svytable(~pos_id + ola + idencuesta, elsoc_diseno, round = F))) %>% dplyr::filter(Freq>0)  %>% group_by(ola) %>% mutate(porcentaje=Freq/sum(Freq)) %>% na.omit()

etiquetas.2.2 <- data.frame((svytable(~pos_id + ola, elsoc_diseno, round = F))) %>% group_by(ola) %>% mutate(porcentaje=Freq/sum(Freq)) %>% na.omit() %>% 
  mutate(idencuesta = 1)

elsoc_panel_m1$pos_id <- na.replace(elsoc_panel_m1$pos_id, "NS/NR") #recode NA en categoría "NS/NR"

elsoc_diseno <- svydesign(ids = ~segmento, #muestreo por conglomerado a nivel de manzanas (segmento)
                          strata = ~estrato, #muestreo estratificado a nivel ciudad (estato)
                          weights = ~ponderador02, #ponderador de corte transversal
                          nest = TRUE,
                          data = elsoc_panel_m1)
```

```{r echo=FALSE}

g.2.2 <- ggplot(datos.2.2, aes(x = ola, fill = pos_id, stratum = pos_id,
                             alluvium = idencuesta, y = porcentaje))+
    ggalluvial::geom_flow(alpha = .66) + 
    ggalluvial::geom_stratum(linetype = 0) +
    scale_y_continuous(labels = scales::percent) + 
    ylab(label = NULL) +
    xlab(label = NULL) + 
    theme(legend.position = 'top',
          legend.title = element_blank()) +
    scale_fill_viridis_d(begin = 0, end = .95, direction = -1, option = 'viridis') +
    geom_text(data = etiquetas.2.2, 
              aes(label = ifelse(porcentaje > 0.03 , scales::percent(porcentaje, accuracy = .1),"")),
              position = position_stack(vjust = .5),
              show.legend = FALSE,
              size = 2,
              color = rep('white'))

g.2.2
```

### 2.3 Grado de acuerdo con la cuarentena según identificación política

<!-- ### 2.3 Grado de acuerdo con la cuarentena según identificación política -->

```{r include=FALSE}
elsoc_panel_m1$ac_cuar <- car::recode(as.numeric(elsoc_panel_m1$c37_10), 
                                      recodes = "c(1,2)='Totalmente en desacuerdo y En desacuerdo';
                                      c(3)='Ni de acuerdo ni en desacuerdo'; 
                                      c(4,5)='De acuerdo y Totalmente de acuerdo';
                                      else=NA", as.factor = TRUE) 

elsoc_diseno <- svydesign(ids = ~segmento, #muestreo por conglomerado a nivel de manzanas (segmento)
                          strata = ~estrato, #muestreo estratificado a nivel ciudad (estato)
                          weights = ~ponderador02, #ponderador de corte transversal
                          nest = TRUE,
                          data = elsoc_panel_m1)
```

```{r}
datos.2.3 <- data.frame((svytable(~pos_id + ac_cuar + ola, elsoc_diseno, round = F))) %>%
  group_by(pos_id) %>% mutate(porcentaje=Freq/sum(Freq)) %>%
  filter(ola == '2021') %>%
  na.omit()
view(datos.2.3)
```


```{r echo=FALSE}
g.2.3 <-datos.2.3 %>% 
  ggplot(aes(y = porcentaje, x = pos_id, fill = ac_cuar, 
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 0.3)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1, option = 'viridis') +
  #cambiar geom_text tal que: Stack y cambio colores
  geom_text(position = position_stack(vjust = .5),
            size= 2.75, color = rep.int(c('white', 'white', 'white'), 4)) + 
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Grado de acuerdo con la cuarentena según identificación política')

g.2.3
```

### 2.4 Grado de acuerdo con actividad económica versus salud pública según identificación política

<!-- ### 2.4 Grado de acuerdo con la frase "Es más importante darle prioridad a la actividad económica que a la salud de la población" según identificación política -->

```{r include=FALSE}
elsoc_panel_m1$salud_ac <- car::recode(as.numeric(elsoc_panel_m1$c37_09), 
                                      recodes = "c(1,2)='Totalmente en desacuerdo y En desacuerdo';
                                      c(3)='Ni de acuerdo ni en desacuerdo'; 
                                      c(4,5)='De acuerdo y Totalmente de acuerdo';
                                      else=NA", as.factor = TRUE)

elsoc_diseno <- svydesign(ids = ~segmento, #muestreo por conglomerado a nivel de manzanas (segmento)
                          strata = ~estrato, #muestreo estratificado a nivel ciudad (estato)
                          weights = ~ponderador02, #ponderador de corte transversal
                          nest = TRUE,
                          data = elsoc_panel_m1)
```

```{r}
datos.2.4 <- data.frame((svytable(~pos_id + salud_ac + ola, elsoc_diseno, round = F))) %>%
  group_by(pos_id) %>% mutate(porcentaje=Freq/sum(Freq)) %>%
  filter(ola == '2021') %>%
  na.omit()
```


```{r echo=FALSE}
g.2.4 <-datos.2.4 %>% 
  ggplot(aes(y = porcentaje, x = pos_id, fill = salud_ac, 
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 0.3)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1, option = 'viridis') +
  #cambiar geom_text tal que: Stack y cambio colores
  geom_text(position = position_stack(vjust = .5),
            size= 2.75, color = rep.int(c('white', 'white', 'white'), 4)) + 
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Grado de acuerdo con la frase "Es más importante darle prioridad a 
          la actividad económica que a la salud de la población"')

g.2.4
```

### 2.5 Intención de voto según identificación política

<!-- ### 2.5 Intención de voto según identificación política -->

```{r include=FALSE}
datos.2.5 <- data.frame((svytable(~intencion_voto + pos_id + ola, elsoc_diseno, round = F))) %>%
  group_by(pos_id , ola) %>% mutate(porcentaje=Freq/sum(Freq)) %>%
  filter(ola == '2021') %>%
  na.omit()
```

```{r echo=FALSE}
g.2.5 <-datos.2.5 %>% 
  ggplot(aes(y = porcentaje, x = pos_id, fill = intencion_voto, 
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1, option = 'viridis') +
  #cambiar geom_text tal que: Stack y cambio colores
  geom_text(position = position_stack(vjust = .5),
            size= 2.75, color = rep.int(c('black', 'white', 'white'), 4)) + 
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Intención de voto según identificación política')

g.2.5
```

