
## Justificación de la Violencia


### Justificación de la violencia para el control social – a manos de ciudadanos

```{r just-vio-ola, fig.aligN='center', fig.cap='Justificación de la violencia en relación a delincuencia, según ola de encuesta'}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & ola %in% 1:4 &
           !f05_01 %in% c(-888, -999) & !f05_02 %in% c(-888, -999)) %>%  
  select(f05_01, f05_02, ola, ponderador02, segmento_disenno, estrato_disenno) %>% 
  pivot_longer(cols = c(f05_01, f05_02)) %>% 
  prop(value %in% 4:5, by = c(ola, name), na.rm = TRUE) %>% 
  mutate(name = factor(name,
                       levels = c('f05_01', 'f05_02'),
                       labels = c('Personas persigan y golpeen a un delincuente\n que acaba de cometer un asalto','Personas amarren a un poste y desnuden a un\n delincuente que acaba de cometer un asalto'))) %>% 
sjlabelled::as_label(ola) %>% 
  ggplot(aes(y = prop, x = ola, color = name, group = name,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, .5)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .33, end = .66, option = 'viridis') + 
  geom_text_repel(size = 3, nudge_y = .02) +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Justificación de la violencia, según ola',
          subtitle = 'Porcentaje que responde que Muchas veces o Siempre se justifica' )


```


### Justificación de la violencia para el control social – a manos de carabineros

```{r just-carab-ola, fig.align='center',fig.cap="Justificación de la violencia en relación al actuar de Carabineros, según ola"}
elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & 
           !f05_03 %in% c(-888, -999) & !f05_04 %in% c(-888, -999) & !f05_07 %in% c(-888, -999)) %>%  
  select(f05_03, f05_04, f05_07, ola, ponderador02, segmento_disenno, estrato_disenno) %>% 
  pivot_longer(cols = c(f05_03, f05_04, f05_07)) %>% 
  prop(value %in% 4:5, by = c(ola, name), na.rm = TRUE) %>% 
  mutate(name = factor(name,
                       levels = c('f05_03', 'f05_04', 'f05_07'),
                       labels = c('Carabineros use la fuerza para\n reprimir manifestación pacífica',
                                  'Carabineros desaloje a la fuerza\na estudiantes de liceo en toma',
                                  'Estudiantes tiren piedras a Carabi-\nneros en marcha por la educación'))) %>% 
sjlabelled::as_label(ola) %>% 
  ggplot(aes(y = prop, x = ola, color = name, group = name,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_point(size = 1.75) + 
  geom_line() +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, .5)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = 0, end = .7, option = 'viridis') + 
  ggrepel::geom_text_repel(size = 3, nudge_y = .02) +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Justificación de la violencia, según ola',
        subtitle = 'Porcentaje que responde que Muchas veces o Siempre se justifica' )

```


