
## Confianza interpersonal y en instituciones

### Confianza interpersonal

```{r}

elsoc_long_2016_2021 %>%
  filter(tipo_atricion == 1 & !is_nsnr(c02, c04)) %>% 
  as_label(ola) %>% 
  prop_list(c02 == 1, c04 == 2, by = ola, na.rm = TRUE) %>% 
  mutate(name = factor(name, 
                       levels = c('c02 == 1', 'c04 == 2'),
                       labels = c('Casi siempre se puede\nconfiar en las personas',
                                  'La mayoría de las personas\ntratan de ser justas'))) %>% 
  ggplot(aes(y = prop, x = ola, color = name, group = name,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_text_repel(nudge_y = .025, size = 3, color = 'black') +
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent, limits = c(0,.5)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .33, end = .66, option = 'viridis') +
  theme(axis.text.x = element_text(size = rel(.9)),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Confianza interpersonal, según ola',
          subtitle = 'Porcentaje que responde que...')

```


```{r}

elsoc_long_2016_2021 %>%
  filter(tipo_atricion == 1, ola == 5, !is_nsnr(c02, c04, m01)) %>% 
  mutate(educ = factor(car::recode(m01, recodes = "1:3 = 1; 4:5 = 2; 6:7 = 3; 8:10 = 4"),
                       levels = 1:4,
                       labels = c("Basica", "Media", "Tecnica", "Universitaria"))) %>% 
  prop_list(c02 == 1, c04 == 2, by = educ, na.rm = TRUE) %>% 
  mutate(name = factor(name, 
                       levels = c('c02 == 1', 'c04 == 2'),
                       labels = c('Casi siempre se puede\nconfiar en las personas',
                                  'La mayoría de las personas\ntratan de ser justas'))) %>% 
  ggplot(aes(y = prop, fill = educ, x = name,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_col(position = 'dodge2') + 
  geom_text(position = position_dodge(.9),
            vjust = -.5,
            size = 3) +
  scale_y_continuous(labels = scales::percent, limits = c(0,.5)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(end = .85, option = 'viridis') +
  theme(axis.text.x = element_text(size = rel(.9)),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Confianza interpersonal (2021), según nivel educacional',
          subtitle = 'Porcentaje que responde que...')

```

```{r}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & !is_nsnr(c05_01, c05_07, c05_08)) %>% 
  as_label(ola) %>% 
  prop_list(c05_01 %in% 4:5, c05_07 %in% 4:5, c05_08 %in% 4:5, by = ola, na.rm = TRUE) %>% 
  mutate(name = factor(name, 
                       levels = c('c05_01 %in% 4:5', 'c05_07 %in% 4:5', 'c05_08 %in% 4:5'),
                       labels = c('Presidente/a de la Republica', 'Congreso Nacional', 'Gobierno de Chile'))) %>% 
  ggplot(aes(y = prop, x = ola, color = name, group = name,
               label = scales::percent(prop, accuracy = .1))) +
    theme_bw() +  
    geom_line() +
    geom_point(size = 1.75) +
    scale_y_continuous(labels = scales::percent,
                       limits = c(0,.5)) +
    ylab(label = NULL) +
    xlab(label = NULL) +
    scale_color_viridis_d(begin = .1, end = .66, option = 'viridis') +
    geom_text_repel(size = 3, nudge_y = .02, color = 'black') +
    theme(legend.position = 'top',
          legend.title = element_blank())  + 
  ggtitle('Grado de confianza en instituciones, según ola',
          subtitle = 'Porcentaje que Confía Bastante o Mucho')

```

```{r}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & !is_nsnr(c05_02, c05_03, c05_05)) %>% 
  as_label(ola) %>% 
  prop_list(c05_02 %in% 4:5, c05_03 %in% 4:5, c05_05 %in% 4:5, by = ola, na.rm = TRUE) %>% 
  mutate(name = factor(name, 
                       levels = c('c05_02 %in% 4:5', 'c05_03 %in% 4:5', 'c05_05 %in% 4:5'),
                       labels = c('Partidos Políticos', 
                                  'Carabineros de Chile', 
                                  'Poder Judicial'))) %>%
  ggplot(aes(y = prop, x = ola, color = name, group = name,
               label = scales::percent(prop, accuracy = .1))) +
    theme_bw() +  
    geom_line() +
    geom_point(size = 1.75) +
    scale_y_continuous(labels = scales::percent,
                       limits = c(0,.5)) +
    ylab(label = NULL) +
    xlab(label = NULL) +
    scale_color_viridis_d(begin = .1, end = .66, option = 'viridis') +
    geom_text_repel(size = 3, nudge_y = .02, color = 'black') +
    theme(legend.position = 'top',
          legend.title = element_blank()) + 
    ggtitle('Grado de confianza en instituciones, según ola',
          subtitle = 'Porcentaje que Confía Bastante o Mucho')


```


```{r}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & !is_nsnr(c05_01, c05_02, c05_03, c05_05, c05_07, c05_08),
         ola %in% c(1, 5)) %>% 
  as_label(ola) %>% 
  prop_list(c05_01 %in% 4:5, c05_02 %in% 4:5, c05_03 %in% 4:5, c05_05 %in% 4:5, c05_07 %in% 4:5, c05_08 %in% 4:5, by = ola, na.rm = TRUE) %>%
  mutate(name = factor(name, 
                       levels = c('c05_01 %in% 4:5', 'c05_02 %in% 4:5', 
                                  'c05_03 %in% 4:5', 'c05_05 %in% 4:5',
                                  'c05_07 %in% 4:5', 'c05_08 %in% 4:5'),
                       labels = c('Presidente/a de\nla Republica', 'Partidos Políticos', 
                                  'Carabineros de Chile', 'Poder Judicial',
                                  'Congreso Nacional', 'Gobierno de Chile'))) %>%
  group_by(name) %>% 
  mutate(orden = mean(ifelse(ola == '2021', prop, NA), na.rm = TRUE)) %>% 
  ungroup() %>% 
  ggplot(aes(y = prop, x = reorder(name, orden), 
             label = scales::percent(prop, .1))) +
  geom_line(size = .7, color = viridis(1, begin = .44, end = .44)) +
  geom_point(aes(color = ola), size = 4) + 
  geom_point(color = 'black', size = 4, shape = 1) + 
  geom_text_repel(size= 3, nudge_x = .02) +
  coord_flip() +
  theme_bw() +
  scale_y_continuous(labels = scales::percent, limits = c(0,.5)) +
  ylab(label = NULL) +
  xlab(label = NULL) + 
  scale_color_viridis_d(begin = .33, end = .66, direction = -1, option = 'viridis') +
  theme(legend.position = 'right',
        legend.title = element_blank()) + 
  guides(color = guide_legend(reverse = TRUE)) +
  ggtitle('Cambio en grado de confianza en instituciones (2016-2021)',
          subtitle = 'Porcentaje que Confía Bastante o Mucho')

```

