
## Cambio constitucional



```{r particip-elect-olas, fig.align='center'}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & ola %in% c(1,3,5) & !is_nsnr(c15, c11, c43, values = c(3, -888, -999))) %>% 
  mutate(particip_electoral = ifelse(ola == 5, c43, c11)) %>% 
  prop(particip_electoral == 1, by = ola, na.rm = TRUE) %>%
  mutate(ola = factor(ola, 
                      levels = c(1,3,5), 
                      labels = c('Elecciones Presidenciales\nde 2013', 
                                 'Elecciones Presidenciales\nde 2017', 
                                 'Plebiscito cambio\nconstitucional'))) %>% 
  ggplot(aes(y = prop, x = ola, label = scales::percent(prop, accuracy = .1))) +
  theme_bw() +   
  geom_col(fill = viridis(1, begin = .33)) +
  geom_text(position = position_dodge(.9), vjust = -.5, size = 3) +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0,1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(end = .66, direction = 1, option = 'viridis') +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Participación electoral, según elección',
          subtitle = 'Porcentaje que votó en...')

```


```{r servel-apruebo, fig.align='center', fig.cap='Voto retrospectivo Plebiscito Nueva Constitucion'}

elsoc_long_2016_2021 %>% 
  dplyr::filter(ola == 5 & tipo_atricion == 1 & !c44 %in% c(3, 4, -888, -999)& !is.na(c44)) %>% 
  prop(c44, na.rm = TRUE) %>% 
  sjlabelled::as_label(c44) %>%
  mutate(datos = 'Datos ELSOC') %>%
  add_row(c44 = c('Apruebo', 'Rechazo'), 
          prop = c(.7828, .2172), 
          datos = c('Datos servel', 'Datos servel')) %>%
  ggplot(aes(y = prop, x = c44, fill = datos, 
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1, option = 'viridis') +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75)  + 
  theme(legend.position = 'top',
        legend.title = element_blank())

```


```{r particip-elect-olas-edad, fig.align='center'}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & ola %in% c(1,3,5) & !is_nsnr(c15, c11, c43, values = c(3, -888, -999))) %>% 
  mutate(particip_electoral = ifelse(ola == 5, c43, c11),
         edadt = factor(car::recode(m0_edad, "18:29 = 1; 30:49 = 2; 50:64 = 3; 65:150 = 4"),
                        levels = 1:4,
                        labels = c('18-29', '30-49', '50-64', '65 o más'))) %>% 
  prop(particip_electoral == 1, by = c(ola, edadt), na.rm = TRUE) %>%
  mutate(ola = factor(ola, 
                      levels = c(1,3,5), 
                      labels = c('Elecciones Presidenciales\nde 2013', 
                                 'Elecciones Presidenciales\nde 2017', 
                                 'Plebiscito cambio\nconstitucional'))) %>%  
  ggplot(aes(y = prop, x = ola, color = edadt, group = edadt,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() +
  geom_point(size = 1.75) +
  geom_line() +
  geom_text_repel(size = 3) +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0,1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(end = .66, direction = 1, option = 'viridis') +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Participación electoral, según tramo de edad',
          subtitle = 'Porcentaje que votó en...')

```


```{r voto-posid}

elsoc_long_2016_2021 %>% 
  dplyr::filter(tipo_atricion == 1 & !is_nsnr(c15, c43, c44)) %>% 
  mutate(pos_id = factor(car::recode(c15, "0:4 = 1; 5 = 2; 6:10 = 3; 11:12 = 4"),
                         levels = c(1, 2, 3, 4),
                         labels = c('Izquierda', "Centro", "Derecha", "No se identifica")),
         voto2020 = case_when(c43 %in% 2:3 ~ 5,
                              TRUE ~ c44),
         voto2020 = factor(car::recode(voto2020, '3:4 = 5'),
                          levels = c(1:2, 5),
                          labels = c('Apruebo', 'Rechazo', 'No votó o votó\nBlanco o Nulo'))) %>% 
  prop(voto2020, by = pos_id, na.rm = TRUE) %>%
  ggplot(aes(y = prop, x = pos_id, fill = fct_rev(voto2020),
             label = scales::percent(ifelse(prop < .02, NA, prop), accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'stack') +
  scale_y_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(end = .7, direction = 1, option = 'viridis') +
  geom_text(position = position_stack(vjust = .5),
            size = 3, na.rm = TRUE,
            color = rep(c('black', 'white', 'white'), 4)) +
  guides(fill = guide_legend(reverse = TRUE)) +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Voto en plebiscito de 2020, según posición ideológica',
          subtitle = 'Porcentaje que voto...')

```

```{r voto-votoprevio}

elsoc_wide_2016_2021 %>% 
  filter(tipo_atricion == 1, !is_nsnr(c11_w01, c11_w03, c43_w05, values = c(3, -888, -999))) %>% 
  mutate(votos = factor(case_when(c11_w01 != 1 & c11_w03 != 1 ~ 1,
                                  c11_w01 == 1 & c11_w03 != 1 ~ 2,
                                  c11_w01 != 1 & c11_w03 == 1 ~ 3,
                                  c11_w01 == 1 & c11_w03 == 1 ~ 4),
                        labels = c('No votó en elecciones\nde 2013 ni de 2017',
                                   'Votó en 2013,\npero no en 2017',
                                   'Votó en 2017,\npero no en 2013',
                                   'Votó en 2013 y 2017')),
         voto2020 = case_when(c43_w05 %in% 2:3 ~ 5,
                              TRUE ~ c44_w05),
         voto2020 = factor(car::recode(voto2020, '3:4 = 5'),
                          levels = c(1:2, 5),
                          labels = c('Apruebo', 'Rechazo', 'No votó o votó\nBlanco o Nulo'))) %>% 
  survey_design_elsoc(weights = 'ponderador02_w05') %>% 
  prop(voto2020, by = votos, na.rm = TRUE) %>%
  ggplot(aes(y = prop, x = votos, fill = fct_rev(voto2020),
             label = scales::percent(ifelse(prop < .02, NA, prop), accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'stack') +
  scale_y_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(end = .7, direction = 1, option = 'viridis') +
  geom_text(position = position_stack(vjust = .5),
            size = 3, na.rm = TRUE,
            color = rep(c('black', 'white', 'white'), 4)) +
  guides(fill = guide_legend(reverse = TRUE)) +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Voto en plebiscito de 2020, según voto en elecciones previas')

```



```{r voto-votopresi, fig.align='center', fig.cap= "Voto Retrospectivo Plebicito, según Posición Ideológica"}

elsoc_wide_2016_2021 %>% 
  dplyr::filter(tipo_atricion == 1 & !is_nsnr(c11_w03, c39_w03, c43_w05, c44_w05)) %>% 
  mutate(voto2017 = case_when(c11_w03 %in% 2:3 ~ 11,
                               TRUE ~ c39_w03),
         voto2017 = factor(car::recode(voto2017, '9:10 = 9'),
                           levels = c(1:9, 11),
                           labels = c('Goic', 'Kast', 'Piñera', 'Guillier', 'Sánchez', 'Enríquez-\nOminami', 'Artés', 'Navarro', 'Blanco\no Nulo', 'No votó')),
         voto2020 = case_when(c43_w05 %in% 2:3 ~ 5,
                              TRUE ~ c44_w05),
         voto2020 = factor(car::recode(voto2020, '3:4 = 3'),
                          levels = c(1:3, 5),
                          labels = c('Apruebo', 'Rechazo', 'Blanco\no Nulo', 'No votó'))) %>%
  survey_design_elsoc(weights = 'ponderador02_w05') %>% 
  prop(voto2020, by = voto2017, na.rm = TRUE) %>%
  dplyr::right_join(tidyr::expand(., voto2020, voto2017)) %>% 
  mutate(prop = ifelse(is.na(prop), 0, prop)) %>% 
  group_by(voto2017) %>% 
  mutate(orden = max(ifelse(voto2020 == 'Apruebo', prop, 0))) %>% 
  arrange(voto2017, voto2020) %>% 
  ggplot(aes(y = prop, x = reorder(voto2017, desc(orden)), fill = fct_rev(voto2020), 
             label = scales::percent(ifelse(prop < .02, NA, prop), accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'stack') +
  scale_y_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = 'Voto en elección presidencial de 2017') +
  scale_fill_viridis_d(end = .7, direction = 1, option = 'viridis') +
  geom_text(position = position_stack(vjust = .5),
            size = 3, na.rm = TRUE,
            color = rep(c('black', 'white', 'white', 'white'), 10)) + 
  guides(fill = guide_legend(reverse = TRUE)) +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Voto en plebiscito de 2020, según voto en elección presidencial de 2017')

```

## Optimismo constitucional

```{r}
elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1, ola == 5, !is_nsnr(c46_01, c46_02, c46_03, c46_04)) %>% 
  prop_list(c46_01 %in% 4:5, c46_02 %in% 4:5, c46_03 %in% 4:5, c46_04 %in% 4:5, na.rm = TRUE) %>% 
  mutate(name  =factor(name,
                     levels = c('c46_01 %in% 4:5', 'c46_03 %in% 4:5', 'c46_04 %in% 4:5', 'c46_02 %in% 4:5'),
                     labels = c('Reducirá la desigualdad\n en salud y educación',
                                'Reducirá la corrupción',
                                'Tendrá poco impacto en\nla calidad de vida',
                                'Empeorará condiciones\n económicas'))) %>%
  ggplot(aes(x = name, y = prop,
             label = scales::percent(ifelse(prop>.01, prop, NA), accuracy = .1))) +
  theme_bw() +
  geom_col(fill = viridis::viridis(1, begin = .33)) +
  geom_text(position = position_dodge(.9), vjust = -.5, size = 3) +
  theme_bw()+
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .85, direction = -1, option = 'viridis') +
  ggtitle('Optimismo constitucional',
        subtitle = 'Porcentaje De acuerdo o Muy de acuerdo con: "La nueva constitución..."')

```

```{r}
elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1, ola == 5, 
         !is_nsnr(c46_01, c46_02, c46_03, c46_04),
         !is_nsnr(c43, c44)) %>% 
  mutate(voto2020 = case_when(c43 %in% 2:3 ~ 3,
                              TRUE ~ c44),
         voto2020 = factor(car::recode(voto2020, '3:4 = 3'),
                          levels = 1:3,
                          labels = c('Apruebo', 'Rechazo', 'No votó o votó\nblanco/nulo')),
         c46_02 = 6 - c46_02,
         c46_04 = 6 - c46_04) %>% 
  rowwise() %>% 
  mutate(optimismo = mean(c46_01 , c46_02, c46_03, c46_04, na.rm = TRUE)) %>% 
  ungroup() %>% 
  prop(optimismo >= 4, by = voto2020, na.rm = TRUE) %>% 
  ggplot(aes(x = voto2020, y = prop,
             label = scales::percent(ifelse(prop>.01, prop, NA), accuracy = .1))) +
  theme_bw() +
  geom_col(position = 'dodge2', fill = viridis(1, begin = .33)) +
  geom_text(position = position_dodge(.9), vjust = -.5, size = 3) +
  theme_bw()+
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  theme(legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Optimismo constitucional, según voto en plebiscito de 2020',
        subtitle = 'Porcentaje de acuerdo o muy de acuerdo en promedio con atributos positivos')

```

```{r}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1, ola == 5, 
         !is_nsnr(c46_01, c46_02, c46_03, c46_04),
         !is_nsnr(m01)) %>% 
  mutate(educ = factor(car::recode(m01, recodes = "1:3 = 1; 4:5 = 2; 6:7 = 3; 8:10 = 4"),
                   levels = 1:4,
                   labels = c("Basica", "Media", "Tecnica", "Universitaria")),
         c46_02 = 6 - c46_02,
         c46_04 = 6 - c46_04) %>% 
  rowwise() %>% 
  mutate(optimismo = mean(c46_01 , c46_02, c46_03, c46_04, na.rm = TRUE)) %>% 
  ungroup() %>% 
  prop(optimismo >= 4, by = educ, na.rm = TRUE) %>% 
  ggplot(aes(x = educ, y = prop,
             label = scales::percent(ifelse(prop>.01, prop, NA), accuracy = .1))) +
  theme_bw() +
  geom_col(position = 'dodge2', fill = viridis(1, begin = .33)) +
  geom_text(position = position_dodge(.9), vjust = -.5, size = 3) +
  theme_bw()+
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  theme(legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Optimismo constitucional, según nivel educacional',
        subtitle = 'Porcentaje de acuerdo o muy de acuerdo en promedio con atributos positivos')


```


```{r}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1, ola == 5, 
         !is_nsnr(c46_01, c46_02, c46_03, c46_04),
         !is_nsnr(c15)) %>% 
    mutate(pos_id = factor(car::recode(c15, "0:4 = 1; 5 = 2; 6:10 = 3; 11:12 = 4"),
                       levels = 1:4,
                       labels = c('Izquierda', "Centro", "Derecha", "No se identifica")),
         c46_02 = 6 - c46_02,
         c46_04 = 6 - c46_04) %>% 
  rowwise() %>% 
  mutate(optimismo = mean(c46_01 , c46_02, c46_03, c46_04, na.rm = TRUE)) %>% 
  ungroup() %>% 
  prop(optimismo >= 4, by = pos_id, na.rm = TRUE) %>% 
  ggplot(aes(x = pos_id, y = prop,
             label = scales::percent(ifelse(prop>.01, prop, NA), accuracy = .1))) +
  theme_bw() +
  geom_col(position = 'dodge2', fill = viridis(1, begin = .33)) +
  geom_text(position = position_dodge(.9), vjust = -.5, size = 3) +
  theme_bw()+
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  theme(legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Optimismo constitucional, según voto en plebiscito de 2020',
        subtitle = 'Porcentaje de acuerdo o muy de acuerdo en promedio con atributos positivos')

```


