---
editor_options: 
  markdown: 
    wrap: 72
---

# Justificación de la Violencia


## Justificación de la violencia para el control social – a manos de ciudadanos

```{r just-vio-ola, fig.aligN='center', fig.cap='Justificación de la violencia en relación a delincuencia, según ola de encuesta'}
datos.alta <- data.frame((svytable(~f05_01_rec + ola, elsoc_diseno, round = F))) %>% group_by( ola) %>% mutate(p_alta=Freq/sum(Freq))
datos.alta$ola <- NULL
datos.baja <- data.frame((svytable(~f05_02_rec + ola, elsoc_diseno, round = F))) %>% group_by(ola) %>% mutate(p_baja=Freq/sum(Freq))

datos.grafico1<- cbind(datos.alta, datos.baja)

#trasponer según variable
datos.grafico <- datos.grafico1 %>% 
  pivot_longer(cols = starts_with('f05_'))  %>%
  mutate(variable = factor(name, labels = c('Personas persigan y golpeen a un delincuente\n que acaba de cometer un asalto', 'Personas amarren a un poste y desnuden a un\n delincuente que acaba de cometer un asalto'))) %>% 
  drop_na()

datos.grafico$porcentaje <- with(datos.grafico, case_when(
  variable == 'Personas persigan y golpeen a un delincuente\n que acaba de cometer un asalto' ~ p_alta,
  variable == 'Personas amarren a un poste y desnuden a un\n delincuente que acaba de cometer un asalto' ~ p_baja))

#graficamos

g10.1 <-datos.grafico %>% 
  ggplot(aes(y = porcentaje, x = ola, fill = value, 
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) +
  theme_bw() + 
  geom_col(position = "Stack") +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  facet_wrap(datos.grafico$variable) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1, option = 'viridis') + 
  geom_text(position = position_stack(vjust = .5),
            size= 2.75) +
  theme(legend.position = 'top',
        legend.title = element_blank())

g10.1
```


## Justificación de la violencia para el control social – a manos de carabineros

```{r just-carab-ola, fig.align='center',fig.cap="Justificación de la violencia en relación al actuar de Carabineros, según ola"}
datos.alta <- data.frame((svytable(~f05_03_rec + ola, elsoc_diseno, round = F))) %>% group_by( ola) %>% mutate(p_alta=Freq/sum(Freq))
datos.alta$ola <- NULL
datos.baja <- data.frame((svytable(~f05_04_rec + ola, elsoc_diseno, round = F))) %>% group_by(ola) %>% mutate(p_baja=Freq/sum(Freq))
datos.alta$ola <- NULL
datos.media <- data.frame((svytable(~f05_07_rec + ola, elsoc_diseno, round = F))) %>% group_by(ola) %>% mutate(p_media=Freq/sum(Freq))
datos.grafico1<- cbind(datos.alta, datos.baja, datos.media)

#trasponer según variable
datos.grafico <- datos.grafico1 %>% 
  pivot_longer(cols = starts_with('f05_'))  %>%
  mutate(variable = factor(name, labels = c('Carabineros use la fuerza para\n reprimir manifestación pacífica',
                                 'Carabineros desaloje a la fuerza\na estudiantes de liceo en toma',
                                 'Estudiantes tiren piedras a Carabi-\nneros en marcha por la educación'))) %>% 
  drop_na()

datos.grafico$porcentaje <- with(datos.grafico, case_when(
  variable == 'Carabineros use la fuerza para\n reprimir manifestación pacífica' ~ p_alta,
  variable == 'Carabineros desaloje a la fuerza\na estudiantes de liceo en toma' ~ p_baja,
  variable == 'Estudiantes tiren piedras a Carabi-\nneros en marcha por la educación' ~ p_media))

#graficamos

g10.2 <-datos.grafico %>% 
  ggplot(aes(y = porcentaje, x = ola, fill = value, 
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) +
  theme_bw() + 
  geom_col(position = "Stack") +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  facet_wrap(datos.grafico$variable) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1, option = 'viridis') + 
  geom_text(position = position_stack(vjust = .5),
            size= 2.75) +
  theme(legend.position = 'top',
        legend.title = element_blank())

g10.2
```


