---
editor_options: 
  markdown: 
    wrap: 72
---

# Cambio Constitucional

```{r particip-edad, fig.align='center', fig.cap='Participación en Plebiscito Nueva Constitucion'}
datos.g11.1 <- elsoc_long_2016_2021 %>% 
  dplyr::filter(ola == 5 & tipo_atricion == 1 & !c43 %in% c(3, -888, -999)) %>% 
  mutate(edadt = factor(car::recode(m0_edad, "18:29 = 1; 30:49 = 2; 50:64 = 3; 65:150 = 4"),
                           labels = c('18-29', '30-49', '50-64', '65 o más'))) %>%
  prop(c43, by = edadt, na.rm = TRUE) %>% 
  sjlabelled::as_label(c43, edadt)
  
g11.1 <- datos.g11.1 %>% 
  ggplot(aes(y = prop, x = edadt, fill = c43, 
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .85, direction = -1, option = 'viridis') +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75)  + 
  theme(legend.position = 'top',
        legend.title = element_blank()) 

g11.1
```

```{r servel-apruebo, fig.align='center', fig.cap='Voto retrospectivo Plebiscito Nueva Constitucion'}

datos.g11.2 <- elsoc_long_2016_2021 %>% 
  dplyr::filter(ola == 5 & tipo_atricion == 1 & !c44 %in% c(3, 4, -888, -999)& !is.na(c44)) %>% 
  prop(c44, na.rm = TRUE, vartype = NULL) %>% 
  sjlabelled::as_label(c44) %>% 
  mutate(datos = 'Datos ELSOC') %>%
  add_row(c44 = c('Apruebo', 'Rechazo'), prop = c(.7828, .2172), datos = c('Datos servel', 'Datos servel'))

g11.2 <- datos.g11.2 %>% 
  ggplot(aes(y = prop, x = datos, fill = c44, 
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .85, direction = -1, option = 'viridis') +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75)  + 
  theme(legend.position = 'top',
        legend.title = element_blank())

g11.2
```

```{r servel-cc, fig.align='center', fig.cap= 'Voto Retrospectivo Plebiscito Nueva Constitucion'}
datos.g11.3 <- elsoc_long_2016_2021 %>% 
  dplyr::filter(ola == 5 & tipo_atricion == 1 & !c45 %in% c(3, 4, -888, -999) & !is.na(c45)) %>% 
  prop(c45, na.rm = TRUE, vartype = NULL) %>% 
  sjlabelled::as_label(c45) %>% 
  mutate(datos = 'Datos ELSOC') %>%
  add_row(c45 = c('Convención Mixta', 'Convención Constitucional'), prop = c(.2101, .7899), datos = c('Datos servel', 'Datos servel'))

g11.3 <- datos.g11.3 %>% 
  ggplot(aes(y = prop, x = datos, fill = c45, 
             label = as.character(scales::percent(prop, accuracy = .1)))) +
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .85, direction = -1, option = 'viridis') +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75)  + 
  theme(legend.position = 'top',
        legend.title = element_blank())

g11.3
```

```{r particip-elect-id, fig.align='center', fig.cap= 'Sí Participa en Elecciones según Identificación Política'}

datos.g11.4 <- elsoc_long_2016_2021 %>% 
  mutate(c11 = car::recode(c11, '1=2;2=1'), # en c11 1 = no participa, a diferencia de c43
         particip_electoral = ifelse(ola == 5, c43, c11),
         pos_id = factor(car::recode(c15, "c(11,12) = 'No se identifica'; c(0,1,2,3,4) = 'Izquierda'; c(5) = 'Centro'; c(6,7,8,9,10) = 'Derecha'"), levels = c('Izquierda', 'Centro', 'Derecha', 'No se identifica'))) %>%
  filter(tipo_atricion == 1 & !particip_electoral %in% c(3, -888, -999) & 
           ola %in% c(1,3,5) & !is.na(pos_id)) %>% 
  prop(particip_electoral == 1, by = c(ola, pos_id), na.rm = TRUE) %>%
  sjlabelled::as_label(pos_id) %>% 
  mutate(ola = factor(ola, levels = c(1,3,5), labels = c('Elecciones Presidenciales\nde 2013', 'Elecciones Presidenciales\nde 2017', 'Plebiscito cambio\nconstitucional')))


g11.4 <- datos.g11.4 %>% 
  ggplot(aes(y = prop, x = ola, color = pos_id, group = pos_id,
              label = scales::percent(prop, accuracy = .1))) +
  theme_bw() +   
  geom_line(size = 1) +
  geom_point(size = 1.8) +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0,1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = 0.22, end = .66, direction = 1, option = 'viridis') +
  ggrepel::geom_text_repel(size= 2.25) + 
  theme(legend.position = 'top',
        legend.title = element_blank())

g11.4
```

```{r id-pol-voto, fig.align='center', fig.cap= "Voto Retrospectivo Plebicito, según Posición Ideológica"}
datos.g11.5 <- elsoc_long_2016_2021 %>% 
  mutate(pos_id = factor(car::recode(c15, "c(11,12) = 'No se identifica'; c(0,1,2,3,4) = 'Izquierda'; c(5) = 'Centro'; c(6,7,8,9,10) = 'Derecha'"), levels = c('Izquierda', 'Centro', 'Derecha', 'No se identifica'))) %>%
  dplyr::filter(ola == 5 & tipo_atricion == 1 
                & !c44 %in% c(3,4, -888, -999) & !is.na(c44) & !is.na(pos_id)) %>% 
  prop(c44, by = c(pos_id), na.rm = TRUE, vartype = NULL) %>% 
  sjlabelled::as_label(c44, pos_id) 

  
g11.5 <- datos.g11.5 %>% 
  ggplot(aes(y = prop, x = pos_id, fill = c44, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = "Stack") +
  scale_y_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1, option = 'viridis') +
  geom_text(position = position_stack(vjust = .5),
            size= 2.75, color = rep.int(c('black', 'black'), 4)) + 
  theme(legend.position = 'top',
        legend.title = element_blank())

g11.5
```

## Patrones de Votación

```{r presi-voto-c44, fig.align='center', fig.cap= "Voto Retrospectivo Plebicito, según Posición Ideológica"}
datos.g11.6 <- elsoc_wide_2016_2021 %>% 
  dplyr::filter(tipo_atricion == 1 
                & !c44_w05 %in% c(3,4, -888, -999)
                & !c39_w03 %in% c(-888, -999) & !is.na(c44_w05) & !is.na(c39_w03)) %>% 
  survey_design_elsoc(weights = 'ponderador02_w05') %>% 
  prop(c44_w05, by = c39_w03, na.rm = TRUE, vartype = NULL) %>% 
  sjlabelled::as_label(c44_w05, c39_w03) 

g11.6 <- datos.g11.6 %>% 
  ggplot(aes(x = prop, y = c39_w03, fill = c44_w05, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = "Stack") +
  scale_x_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1, option = 'viridis') +
  geom_text(aes(label = ifelse(prop > 0.04 , scales::percent(prop, accuracy = .1),"")),
            position = position_stack(vjust = .5),
            show.legend = FALSE,
            size = 2.75) + 
  theme(legend.position = 'top',
        legend.title = element_blank()) 

g11.6
```

```{r presi-voto-c45, fig.align='center', fig.cap="Voto Retrospectivo Plebicito, según Posición Ideológica"}
datos.g11.7 <- elsoc_wide_2016_2021 %>% 
  dplyr::filter(tipo_atricion == 1 
                & !c45_w05 %in% c(3,4, -888, -999)
                & !c39_w03 %in% c(-888, -999) & !is.na(c45_w05) & !is.na(c39_w03)) %>% 
  survey_design_elsoc(weights = 'ponderador02_w05') %>% 
  prop(c45_w05, by = c39_w03, na.rm = TRUE, vartype = NULL) %>% 
  sjlabelled::as_label(c45_w05, c39_w03) 

g11.7 <- datos.g11.7 %>% 
  ggplot(aes(x = prop, y = c39_w03, fill = c45_w05, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = "Stack") +
  scale_x_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1, option = 'viridis') +
  geom_text(aes(label = ifelse(prop > 0.04 , scales::percent(prop, accuracy = .1),"")),
            position = position_stack(vjust = .5),
            show.legend = FALSE,
            size = 2.75,
            color = rep.int(c('black', 'white'), 10)) + 
  theme(legend.position = 'top',
        legend.title = element_blank()) 

g11.7
```

```{r 2020-vs-2021, fig.align='center', fig.cap= "Participación Electoral 2021, según la Participación en 2017"}
datos.g11.7 <- elsoc_wide_2016_2021 %>% 
  filter(tipo_atricion == 1 & !c43_w05 %in% c(3, -888, -999) & 
           !c11_w03 %in% c(3, -888, -999)) %>% 
  survey_design_elsoc(weights = 'ponderador02_w05') %>% 
  prop(c43_w05, by = c11_w03) %>% 
  sjlabelled::as_label(c43_w05, c11_w03)

datos.11.7 %>% 
  ggplot(aes(y = prop, x = c11_w03, fill = c43_w05, 
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = "Stack") +
  scale_y_continuous(labels = scales::percent) + 
  ylab(label = NULL) +
  xlab(label = "Participación Electoral en 2017") +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1, option = 'viridis') + 
  geom_text(position = position_stack(vjust = .5),
            show.legend = FALSE,
            size = 2.75,
            color = rep(c('black', 'white'), 2)) + 
  theme(legend.position = 'top',
        legend.title = element_blank()) 
```

```{r cambio_participa}
#grafico y caracterización pendiente
elsoc_wide_2016_2021$cambio_participa_w05 <- factor(with(elsoc_wide_2016_2021, case_when(
  (c11_w03 == 2) & (c43_w05 == 2) ~ 1 ,
  (c11_w03 == 2) & (c43_w05 == 1) ~ 2 ,
  (c11_w03 == 1) & (c43_w05 == 2) ~ 3 ,
  (c11_w03 == 1) & (c43_w05 == 1) ~ 4)),
  labels = c('Se mantiene no votando',
             'Cambia a votar',
             'Cambia a No Votar',
             'Se mantiene votando'))

sjmisc::frq(elsoc_wide_2016_2021$cambio_participa_w05)
```

