
# Temas de salud mental y bienestar

## Salud mental y bienestar de la población

### ¿Cómo ha cambiado la salud mental y nivel de bienestar de la población?

```{r}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & !is_nsnr(s01, s02, s03)) %>% 
  sjlabelled::as_label(ola) %>%
  prop_list(s01 %in% 4:5, s02 %in% 4:5, s03 %in% 4:5, by = ola, na.rm = TRUE) %>% 
  mutate(name = factor(name,
                       levels = c('s01 %in% 4:5', 's02 %in% 4:5', 's03 %in% 4:5'),
                       labels = c('Esta satisfecho o muy\nsatisfecho con su vida',
                                  'Su vida se acerca o se acerca\ncompletamente a su ideal',
                                  'Su salud es muy buena\no Excelente'))) %>% 
  ggplot(aes(y = prop, x = ola, group = name, color = name,
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_point(size = 1.75) + 
  geom_line() +
  geom_text_repel(nudge_y = .025, size = 3, color = 'black') +
  scale_y_continuous(labels = scales::percent, limits = c(0,1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +  
  scale_color_viridis_d(end = .75, option = 'viridis') +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Satisfacción con la vida y salud subjetiva, según ola',
          'Porcentaje que responde que...')

```

```{r}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & ola %in% c(1, 3, 5) & !is_nsnr(s04, s08, s09)) %>% 
  sjlabelled::as_label(ola) %>%
  prop_list(s04 %in% 1:4, s08 == 0, s09 == 2, by = ola, na.rm = TRUE) %>% 
  mutate(name = factor(name,
                       levels = c('s04 %in% 1:4', 's08 == 0', 's09 == 2'),
                       labels = c('Practica deporte o actividad física\nmás de 1 o 2 veces por semana',
                                  'No fuma regularmente',
                                  'No consume alcohol\nregularmente'))) %>% 
  ggplot(aes(y = prop, x = ola, group = name, color = name,
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_point(size = 1.75) + 
  geom_line() +
  geom_text_repel(nudge_y = .025, size = 3, color = 'black') +
  scale_y_continuous(labels = scales::percent, limits = c(0,1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +  
  scale_color_viridis_d(end = .75, option = 'viridis') +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Conducta saludable, según ola',
          'Porcentaje que responde que...')

```


```{r}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & ola %in% c(1, 3, 5) & !is_nsnr(s04, s08, s09)) %>% 
  sjlabelled::as_label(ola) %>%
  mutate(suma = 4 - (s04 %in% 1:4) - (s08 == 0) - (s09 == 2)) %>% 
  prop(suma, by = ola, na.rm = TRUE) %>% 
  mutate(conducta_saludable = 
           factor(suma, levels = 1:4,
                  labels = c('Practica deporte, y\nno fuma, ni consume\nalcohol regularmente',
                             'Realiza 1 de 3\nconductas no\nsaludables',
                             'Realiza 2 de 3\nconductas no\nsaludables',
                             'No practica deporte,\nfuma y consume\nalcohol regularmente'))) %>% 
  ggplot(aes(y = prop, x = ola, fill = fct_rev(conducta_saludable),
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_col() +
  geom_text(position = position_stack(vjust = .5), 
            color = rep(rep(c('black', 'white'), each = 2), 3),
            size = 3) +
  scale_y_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +  
  scale_fill_viridis_d(end = .75, option = 'viridis') +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Conducta saludable, según ola',
          'Porcentaje que responde que...') +
  guides(fill = guide_legend(reverse = TRUE))

```


```{r}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1,
         !is_nsnr(s01, s02, s03) & !is_nsnr(s04, s08, s09),
         ola == 5) %>% 
  sjlabelled::as_label(ola) %>%
  mutate(suma = 4 - (s04 %in% 1:4) - (s08 == 0) - (s09 == 2),
         conducta_saludable = 
           factor(suma, levels = 1:4,
                  labels = c('Practica deporte, y\nno fuma, ni consume\nalcohol regularmente',
                             'Realiza 1 de 3\nconductas no\nsaludables',
                             'Realiza 2 de 3\nconductas no\nsaludables',
                             'No practica deporte,\nfuma y consume\nalcohol regularmente'))) %>% 
  prop_list(s01 %in% 4:5, s02 %in% 4:5, s03 %in% 4:5, 
            by = conducta_saludable, na.rm = TRUE) %>% 
  mutate(name = factor(name,
                       levels = c('s01 %in% 4:5', 's02 %in% 4:5', 's03 %in% 4:5'),
                       labels = c('Esta satisfecho o muy\nsatisfecho con su vida',
                                  'Su vida se acerca o se acerca\ncompletamente a su ideal',
                                  'Su salud es muy buena\no Excelente'))) %>% 
  ggplot(aes(y = prop, x = conducta_saludable, group = name, color = name,
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_point(size = 1.75) + 
  geom_line() +
  geom_text_repel(nudge_y = .025, size = 3, color = 'black') +
  scale_y_continuous(labels = scales::percent, limits = c(0,1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +  
  scale_color_viridis_d(end = .75, option = 'viridis') +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Satisfacción con la vida y salud subjetiva, según conducta saludable (2021)',
          'Porcentaje que responde que...')

```

### Sintomatología depresiva

```{r depre-wave, echo=FALSE, fig.align='center'}
elsoc_long_2016_2021 %>% 
  purrr::map_at(.at = vars(starts_with('s11_0')), 
                .f = function(s) car::recode(s, "1 = 0; 2 = 1; 3 = 2; c(4, 5) = 3; c(-888, -999) = NA")) %>%
  as.data.frame() %>%  
  mutate(phq9 = (s11_01 + s11_02 + s11_03 + s11_04 + s11_05 + s11_06 + s11_07 + s11_08 + s11_09),
         depr = factor(car::recode(phq9, "0:4 = 1; 5:9 = 2; 10:14 = 3; 15:27 = 4"), 
                       levels = c(1,2,3,4),
                       labels = c('Sin sintomas o Minima', 'Depresion Media', 'Depresion Moderada', 'Depresion Moderada-Severa\na Severa'))) %>%
  dplyr::filter(tipo_atricion == 1) %>% 
  prop(depr, by = c(ola), na.rm = TRUE) %>% 
  sjlabelled::as_label(depr, ola) %>% 
  ggplot(aes(y = prop, x = ola, fill = fct_rev(depr), 
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .85, option = 'viridis') +
  geom_text(position = position_stack(vjust = .5),
            size = 3, 
            color = rep(rep(c('black', 'white'), each = 2), 5)) + 
  theme(legend.position = 'top',
        legend.title = element_blank()) + 
  guides(fill = guide_legend(reverse = TRUE)) +
  ggtitle('Síntomas de depresión, según ola')

```


```{r depre-sexo, echo=FALSE, fig.align='center'}

elsoc_long_2016_2021 %>% 
  purrr::map_at(.at = vars(starts_with('s11_0')), 
                .f = function(s) car::recode(s, "1 = 0; 2 = 1; 3 = 2; c(4, 5) = 3; c(-888, -999) = NA")) %>%
  as.data.frame() %>%  
  dplyr::filter(tipo_atricion == 1 & ola %in% c(1, 5)) %>% 
  mutate(phq9 = (s11_01 + s11_02 + s11_03 + s11_04 + s11_05 + s11_06 + s11_07 + s11_08 + s11_09),
         depr = factor(car::recode(phq9, "0:4 = 1; 5:9 = 2; 10:14 = 3; 15:27 = 4"),
                       levels = c(1,2,3,4),
                       labels = c('Sin sintomas o\nmínima', 'Depresion media', 
                                  'Depresion moderada', 'Depresion moderada-severa\no Depresión severa'))) %>% 
  as_label(ola) %>% 
  survey_design_elsoc() %>%
  svytable(~depr + ola + idencuesta, design = .) %>% 
  as.data.frame() %>% 
  group_by(ola) %>% 
  mutate(prop = Freq/sum(Freq)) %>%
  filter(Freq > 0) %>% 
  ggplot(aes(y = prop, x = ola, fill = fct_rev(depr), 
             stratum = fct_rev(depr), alluvium = idencuesta)) +
  ggalluvial::geom_flow(alpha = .66) + 
  ggalluvial::geom_stratum(linetype = 0, width = .55) +
  scale_y_continuous(labels = scales::percent) + 
  ylab(label = NULL) +
  xlab(label = NULL) + 
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  scale_fill_viridis_d(direction = -1, end = .9) +
  geom_text(data = function(x) { group_by(.data = x, ola, depr) %>%
      summarise(prop = sum(prop, na.rm = TRUE), idencuesta = 1) %>%
      ungroup()}, 
      aes(label = scales::percent(prop, accuracy = .1)),
      position = position_stack(vjust = .5),
      show.legend = FALSE,
      color = rep(c('white', 'white', 'black', 'black'), 2),
            size = 3) + 
  guides(fill = guide_legend(reverse = TRUE)) + 
  ggtitle(label = 'Cambios en síntomas depresivos entre 2016 y 2021')

            
```


```{r depre-year-sexo, echo=FALSE, fig.align='center'}

elsoc_long_2016_2021 %>% 
  purrr::map_at(.at = vars(starts_with('s11_0')), 
                .f = function(s) car::recode(s, "1 = 0; 2 = 1; 3 = 2; c(4, 5) = 3; c(-888, -999) = NA")) %>%
  as.data.frame() %>%  
  mutate(phq9 = (s11_01 + s11_02 + s11_03 + s11_04 + s11_05 + s11_06 + s11_07 + s11_08 + s11_09)) %>% 
  dplyr::filter(tipo_atricion == 1 & muestra == 1) %>% 
  prop(phq9>=10, by = c(ola, m0_sexo), na.rm = TRUE) %>% 
  sjlabelled::as_label(ola, m0_sexo) %>% 
  ggplot(aes(y = prop, x = ola, 
                   color = m0_sexo, group = m0_sexo,
              label = scales::percent(prop, accuracy = .1))) +
  theme_bw() +   
  geom_line() +
  geom_point(size = 1.75) +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0,0.5)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .33, end = .66, direction = 1, option = 'viridis') +
  ggrepel::geom_text_repel(size = 3, nudge_y = .025) + 
  theme(legend.position = 'top',
        legend.title = element_blank())  + 
  ggtitle(label = 'Síntomas depresivos, según sexo', 
          'Porcentaje con sintomas de depresión moderada, moderada-severa o severa')
 
```

```{r depre-edad-sexo, echo=FALSE, fig.align='center'}

elsoc_long_2016_2021 %>% 
  purrr::map_at(.at = vars(starts_with('s11_0')), 
                .f = function(s) car::recode(s, "1 = 0; 2 = 1; 3 = 2; c(4, 5) = 3; c(-888, -999) = NA")) %>%
  as.data.frame() %>%  
  mutate(phq9 = (s11_01 + s11_02 + s11_03 + s11_04 + s11_05 + s11_06 + s11_07 + s11_08 + s11_09),
         edadt = factor(car::recode(m0_edad, "18:29 = 1; 30:49 = 2; 50:64 = 3; 65:150 = 4"),
                           labels = c('18-29', '30-49', '50-64', '65 o más'))) %>% 
  dplyr::filter(ola %in% c(1, 5) & tipo_atricion == 1 & muestra == 1) %>% 
  prop(phq9 >= 10, by = c(ola, edadt), na.rm = TRUE) %>% 
  sjlabelled::as_label(ola, edadt) %>% 
  ggplot(aes(y = prop, x = edadt, 
                   group = ola, color = ola,
                   label = scales::percent(prop, accuracy = .1))) +
  theme_bw() +   
  geom_line() +
  geom_point(size = 1.75) +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0,0.5)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .33, end = .66, direction = 1, option = 'viridis') +
  ggrepel::geom_text_repel(size = 3) + 
  theme(legend.position = 'top',
        legend.title = element_blank())  + 
  ggtitle(label = 'Síntomas depresivos, según tramo de edad y ola del estudio', 
          'Porcentaje con sintomas de depresión moderada, moderada-severa o severa')

```


```{r}


elsoc_long_2016_2021 %>% 
  purrr::map_at(.at = vars(starts_with('s11_0')), 
                .f = function(s) car::recode(s, "1 = 0; 2 = 1; 3 = 2; c(4, 5) = 3; c(-888, -999) = NA")) %>%
  as.data.frame() %>%  
  mutate(phq9 = (s11_01 + s11_02 + s11_03 + s11_04 + s11_05 + s11_06 + s11_07 + s11_08 + s11_09)) %>% 
  dplyr::filter(tipo_atricion == 1 & muestra == 1 & ola == 5,
                !is_nsnr(s01, s02, s03) & !is_nsnr(s04, s08, s09)) %>% 
  mutate(suma = 4 - (s04 %in% 1:4) - (s08 == 0) - (s09 == 2),
         conducta_saludable = 
           factor(suma, levels = 1:4,
                  labels = c('Practica deporte, y\nno fuma, ni consume\nalcohol regularmente',
                             'Realiza 1 de 3\nconductas no\nsaludables',
                             'Realiza 2 de 3\nconductas no\nsaludables',
                             'No practica deporte,\nfuma y consume\nalcohol regularmente'))) %>% 
  prop(phq9 >= 10, by = conducta_saludable, na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = conducta_saludable,
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'dodge2', fill = viridis(1, begin =.33)) +
  geom_text(position = position_dodge(.9), vjust = -.5, size = 3) +
  scale_y_continuous(labels = scales::percent, limits = c(0,1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +  
  scale_color_viridis_d(end = .75, option = 'viridis') +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle(label = 'Síntomas depresivos, según conducta saludable (2021)', 
          'Porcentaje con sintomas de depresión moderada, moderada-severa o severa')

```

```{r depre-labstat, echo=FALSE, fig.align='center'}

elsoc_long_2016_2021 %>%
  purrr::map_at(.at = vars(starts_with('s11_0')), 
                .f = function(s) car::recode(s, "1 = 0; 2 = 1; 3 = 2; c(4, 5) = 3; c(-888, -999) = NA")) %>%
  as.data.frame() %>%  
  mutate(phq9 = (s11_01 + s11_02 + s11_03 + s11_04 + s11_05 + s11_06 + s11_07 + s11_08 + s11_09),
         sit_ocup = factor(car::recode(m02, "1:3 = 1; 7 = 2; 6 = 3; 5 = 4; c(4, 8, 9) = 5"), 
                           levels = c(1, 2, 3, 4, 5),
                           labels = c("Trabajo remunerado", "Trabajo doméstico\nno remunerado", "Desempleado/a", "Jubilado/a o\npensionado/a", "Otras categorías"))
         ) %>% 
  dplyr::filter(ola == 5 & tipo_atricion == 1 & muestra == 1 & !m02 %in% c(-888, -999)) %>% 
  prop(phq9 >= 10, by = sit_ocup) %>% 
  ggplot(aes(y = prop, x = sit_ocup, 
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'dodge2', fill = viridis(1, begin =.33)) +
  geom_text(position = position_dodge(.9), vjust = -.5, size = 3) +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  theme(legend.position = 'top',
        legend.title = element_blank())  +
  ggtitle(label = 'Síntomas depresivos, según categoría ocupacional (2021)', 
          'Porcentaje con sintomas de depresión moderada, moderada-severa o severa')

```

En 2021 no hay hombres en la categoría Trabajo doméstico no remunerado $^{*}$


