


## COVID - 19


```{r covid-sexo, fig.align='center'}

elsoc_long_2016_2021 %>% 
  dplyr::filter(ola == 5, tipo_atricion == 1 & !is_nsnr(s31) & !is_nsnr(r03_09)) %>%
  prop_list(s31 == 1, r03_09 > 1, na.rm = TRUE) %>% 
  mutate(name = factor(name, levels = c('s31 == 1', 'r03_09 > 1'),
                       labels = c('Fue diagnosticado con COVID-19',
                                  'Tiene al menos un conocido/a que\nfue diagnosticado con COVID-19'))) %>% 
  ggplot(aes(y = prop, x = name, fill = name,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1, option = 'viridis') +
  geom_text(vjust = -0.5,
            position = position_dodge(width = .9),
            size = 3)  + 
  theme(legend.position = 'none') + 
  ggtitle('Cercanía de contagio de covid',
          'Porcentaje que...')

```

```{r depre clase.sub, echo=FALSE, fig.align='center'}

elsoc_long_2016_2021 %>% 
  dplyr::filter(ola == 5, tipo_atricion == 1,
                !is_nsnr(s31, r03_09, d01_01) & !is.na(d01_01)) %>%
  mutate(clase.sub = factor(car::recode(d01_01, "0:4 = 1; 5 = 2; 6:10 = 3"),
                            levels = 1:3,
                            labels = c('Baja y Media baja', 'Media', 'Media y Media alta'))) %>% 
  prop_list(s31 == 1, r03_09 > 1, by = clase.sub, na.rm = TRUE) %>% 
  mutate(name = factor(name, levels = c('s31 == 1', 'r03_09 > 1'),
                       labels = c('Fue diagnosticado con COVID-19',
                                  'Tiene al menos un conocido/a que\nfue diagnosticado con COVID-19'))) %>%
  ggplot(aes(y = prop, x = name, fill = clase.sub,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .75, direction = -1, option = 'viridis') +
  geom_text(vjust = -0.5,
            position = position_dodge(width = .9),
            size = 3)  + 
  theme(legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Cercanía de contagio de covid, según clase social subjetiva (2021)',
          'Porcentaje que...')

```


```{r, fig.align='center'}

elsoc_long_2016_2021 %>% 
  dplyr::filter(ola == 5, tipo_atricion == 1 & !is_nsnr(r03_09)) %>%
  mutate(r03_09 = factor(car::recode(r03_09, "4:7 = 4"),
                         levels = 1:4,
                         labels = c('No conoce a nadie que haya\nsido diagnosticado con COVID-19', 
                                    'Conoce a 1', 'Conoce entre 2 y 4', 'Conoce a 5 o más'))) %>% 
  prop(r03_09, na.rm = TRUE) %>% 
  as_label(r03_09) %>% 
  ggplot(aes(y = prop, x = r03_09, fill = r03_09,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1, option = 'viridis') +
  geom_text(vjust = -0.5,
            position = position_dodge(width = .9),
            size = 3)  + 
  theme(legend.position = 'none') + 
  ggtitle('Distribución de los encuestados,\nsegún número de conocidos que han sido diagnosticados de covid (2021)')

```

### Cuarentenas

```{r hist-fecha-2021, fig.align='center'}
elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & ola == 5) %>% 
  mutate(fecha = make_date(year = annio_entr, month = mes_entr, day = dia_entr),
         semana = lubridate::week(fecha)) %>% 
  group_by(semana) %>% 
  summarise(n = n()) %>%
  mutate(fecha = make_date(year = 2021, month = 1, day = 1) + 7*semana) %>% 
  ggplot(mapping = aes(y = n, x = fecha)) +
  theme_bw() +
  geom_col(fill = viridis(1, begin = .33)) +
  scale_y_continuous(limits = c(0,400)) + 
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_x_date(date_labels = "%d-%m",
               date_breaks = '2 weeks') +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggtitle('¿Cuándo fueron encuestados los entrevistado? (2021)',
          'Frecuencia de encuestas, según fecha')

```

```{r}
elsoc_long_2016_2021 %>% 
  filter(ola == 5 & tipo_atricion == 1) %>% 
  left_join(elsoc_long_cuarentenas, by = c('idencuesta', 'ola')) %>% 
  mutate(cuarentenas30t = factor(car::recode(cuarentenas30, "0 = 1; 1:14 = 2; 15:21 = 3; 22:30 = 4"),
                                 levels = 1:4,
                                 labels = c('0 días', '1-14 días', '15-21 días', '22-30 días'))) %>% 
  prop(cuarentenas30t) %>% 
  ggplot(aes(y = prop, x = cuarentenas30t, fill = cuarentenas30t,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(end = .66, direction = -1, option = 'viridis') +
  geom_text(vjust = -0.5,
            position = position_dodge(width = .9),
            size = 3)  + 
  theme(legend.position = 'none') + 
  ggtitle('Días acumulados en cuarentena, el mes previo a la encuesta',
          'Distribución de los encuestados, según días en cuarentena')

```

```{r}

elsoc_long_2016_2021 %>% 
  filter(ola == 5 & tipo_atricion == 1, !is_nsnr(m60)) %>% 
  prop(m60, na.rm = TRUE) %>% 
  mutate(m60 = factor(m60, levels = 1:3,
                      labels = c('Trabajo de manera\ncompleta desde el hogar',
                                 'Trabajo de manera\n parcial en el hogar',
                                 'Trabajo fuera del hogar'))) %>% 
  ggplot(aes(y = prop, x = m60, fill = m60,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(end = .66, direction = -1, option = 'viridis') +
  geom_text(vjust = -0.5,
            position = position_dodge(width = .9),
            size = 3)  + 
  theme(legend.position = 'none') + 
  ggtitle('Trabajo remoto (2021)',
          'Porcentaje que trabaja en modalidad...')

```


```{r}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1, ola == 5) %>%
  left_join(elsoc_long_cuarentenas, by = c('idencuesta', 'ola')) %>%
  mutate(cuarentenas30t = factor(car::recode(cuarentenas30, "0 = 1; 1:14 = 2; 15:21 = 3; 22:30 = 4"),
                                 levels = 1:4,
                                 labels = c('0 días', '1-14 días', '15-21 días', '22-30 días'))) %>% 
  purrr::map_at(.at = vars(starts_with('s11_0')), 
                .f = function(s) car::recode(s, "1 = 0; 2 = 1; 3 = 2; c(4, 5) = 3; c(-888, -999) = NA")) %>%
  as.data.frame() %>%  
  mutate(phq9 = (s11_01 + s11_02 + s11_03 + s11_04 + s11_05 + s11_06 + s11_07 + s11_08 + s11_09)) %>%
  prop(phq9 >= 10, by = cuarentenas30t, na.rm = TRUE) %>% 
  as_label(ola) %>% 
  ggplot(aes(y = prop, x = cuarentenas30t, fill = cuarentenas30t,
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent, limits = c(0,1)) +
  scale_fill_viridis_d(begin = 0, end = .85, option = 'viridis') +
  ylab(label = NULL) +
  xlab(label = NULL) +
  geom_text(position = position_dodge(.9),
            vjust = -.5,
            size = 3) +
  theme(legend.position = 'none') +
  ggtitle(label = 'Síntomas depresivos, según días de cuarentena', 
          'Porcentaje con sintomas de depresión moderada, moderada-severa o severa')

```

```{r}
elsoc_long_2016_2021 %>% 
  filter(ola == 5 & tipo_atricion == 1, !is_nsnr(m60) & !is.na(m60)) %>% 
  mutate(m60 = factor(m60, levels = 1:3,
                      labels = c('Trabajo de manera\ncompleta desde el hogar',
                                 'Trabajo de manera\n parcial en el hogar',
                                 'Trabajo fuera del hogar'))) %>%
  purrr::map_at(.at = vars(starts_with('s11_0')), 
                .f = function(s) car::recode(s, "1 = 0; 2 = 1; 3 = 2; c(4, 5) = 3; c(-888, -999) = NA")) %>%
  as.data.frame() %>%  
  mutate(phq9 = (s11_01 + s11_02 + s11_03 + s11_04 + s11_05 + s11_06 + s11_07 + s11_08 + s11_09)) %>%
  prop(phq9 >= 10, by = m60, na.rm = TRUE) %>% 
  as_label(ola) %>% 
  ggplot(aes(y = prop, x = m60, fill = m60,
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent, limits = c(0,1)) +
  scale_fill_viridis_d(begin = 0, end = .85, option = 'viridis') +
  ylab(label = NULL) +
  xlab(label = NULL) +
  geom_text(position = position_dodge(.9),
            vjust = -.5,
            size = 3) +
  theme(legend.position = 'none') +
  ggtitle(label = 'Síntomas depresivos, según modalidad de trabajo', 
          'Porcentaje con sintomas de depresión moderada, moderada-severa o severa')

```



### Grado de acuerdo con actividad económica versus salud pública según identificación política el año 2021

```{r}

elsoc_long_2016_2021 %>% 
  filter(ola == 5 & tipo_atricion == 1 & 
           !c37_09 %in% c(-888, -999) & !c15 %in% c(-888, -999)) %>% 
    mutate(pos_id = factor(car::recode(c15, recodes = "0:4 = 1; 5 = 2; 6:10 = 3; 11:12 = 4"),
                         levels = c(1, 2, 3, 4),
                         labels = c('Izquierda', "Centro", "Derecha", "No se identifica"))) %>%
  prop(c37_09 %in% 4:5, pos_id, na.rm = TRUE) %>% 
  sjlabelled::as_label(c37_09, pos_id) %>% 
  ggplot(aes(y = prop, x = pos_id, fill = pos_id, 
               label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
    geom_col() +
    scale_y_continuous(labels = scales::percent, limits = c(0,1)) + 
    ylab(label = NULL) +
    xlab(label = NULL) +
    scale_fill_viridis_d(begin = 0, end = .85, direction = -1, option = 'viridis') +
    geom_text(vjust = -0.8,
              position = position_dodge(width = .9),
              size= 2.75) +
    theme(legend.position = 'none',   
          legend.title = element_blank())

```


```{r}

elsoc_long_2016_2021 %>% 
  filter(ola == 5 & tipo_atricion == 1 & 
           !c37_10 %in% c(-888, -999) & !c15 %in% c(-888, -999)) %>% 
    mutate(pos_id = factor(car::recode(c15, recodes = "0:4 = 1; 5 = 2; 6:10 = 3; 11:12 = 4"),
                         levels = c(1, 2, 3, 4),
                         labels = c('Izquierda', "Centro", "Derecha", "No se identifica"))) %>%
  prop(c37_10 %in% 4:5, pos_id, na.rm = TRUE) %>% 
  sjlabelled::as_label(pos_id) %>% 
  ggplot(aes(y = prop, x = pos_id, fill = pos_id,
               label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
    geom_col() +
    scale_y_continuous(labels = scales::percent,
                       limits = c(0, 1)) +
    ylab(label = NULL) +
    xlab(label = NULL) +
    scale_fill_viridis_d(begin = 0, end = .85, direction = -1, option = 'viridis') +
    geom_text(vjust = -0.8,
              position = position_dodge(width = .9),
              size= 2.75) +
    theme(legend.position = 'none',   
          legend.title = element_blank())

```

## Estrés Financiero

```{r satisfaccion-wave, echo=FALSE, fig.align='center'}

elsoc_long_2016_2021 %>% 
  dplyr::filter(muestra == 1 & tipo_atricion == 1 & !m43 %in% c(-888, -999, NA)) %>% 
  prop(m43, by = ola, na.rm = TRUE) %>% 
  sjlabelled::as_label(m43, ola) %>% 
  ggplot(aes(y = prop, x = ola, fill = m43, 
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .85, direction = -1, option = 'viridis') +
  geom_text(position = position_stack(vjust = .5),
            size= 2.75) + 
  theme(legend.position = 'top',
        legend.title = element_blank()) 

```

```{r satisfaccion-retiro, echo=FALSE, fig.align='center'}
datos.g19.11 <- elsoc_long_2016_2021 %>% 
  dplyr::filter(muestra == 1 & tipo_atricion == 1
                & !m16 %in% c(-888, -999, NA) & !m63_02 %in% c(-888, -999, NA)) %>% 
  prop(m16, by = c(m63_02), na.rm = TRUE) %>% 
  sjlabelled::as_label(m16, m63_02) 


g19.11 <- datos.g19.11 %>% 
  ggplot(aes(y = prop, x = m63_02, fill = m16, 
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .85, direction = -1, option = 'viridis') +
  #cambiar geom_text tal que: Stack y cambio colores
  geom_text(position = position_stack(vjust = .5),
            size= 2.75) + 
  theme(legend.position = 'top',
        legend.title = element_blank()) 

g19.11
```

```{r clase.sub-benef.estatal, echo=FALSE, fig.align='center'}

datos.g19.12 <- elsoc_long_2016_2021 %>% 
  mutate(clase.sub = factor(car::recode(d01_01, "c(0,1,2,3)='Baja y media baja'; c(4, 5)='Media'; c(6,7,8,9,10)='Alta y media alta'"),
                           levels = c("Baja y media baja", "Media", "Alta y media alta"))) %>%
  dplyr::filter(muestra == 1 & tipo_atricion == 1
                & !clase.sub %in% c(-888, -999, NA) & !m63_01 %in% c(-888, -999, NA)) %>% 
  prop(clase.sub, by = c(m63_01), na.rm = TRUE) %>% 
  sjlabelled::as_label(clase.sub, m63_01) 

g19.12 <- datos.g19.12 %>% 
  ggplot(aes(y = prop, x = m63_01, fill = clase.sub, 
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .85, direction = -1, option = 'viridis') +
  #cambiar geom_text tal que: Stack y cambio colores
  geom_text(position = position_stack(vjust = .5),
            size= 2.75) + 
  theme(legend.position = 'top',
        legend.title = element_blank()) 

g19.12
```

```{r clase.sub.hij-1erretiro, echo=FALSE, fig.align='center'}
datos.g19.13 <- elsoc_long_2016_2021 %>% 
  mutate(clase.sub.hijos = factor(car::recode(d01_03, "c(0,1,2,3)='Baja y media baja'; c(4, 5,6)='Media'; c(7,8,9,10)='Alta y media alta'"),
                           levels = c("Baja y media baja", "Media", "Alta y media alta"))) %>%
  dplyr::filter(muestra == 1 & tipo_atricion == 1
                & !clase.sub.hijos %in% c(-888, -999, NA) & !m63_01 %in% c(-888, -999, NA)) %>% 
  prop(clase.sub.hijos, by = c(m63_02), na.rm = TRUE) %>% 
  sjlabelled::as_label(clase.sub.hijos, m63_02) 

g19.13 <- datos.g19.13 %>% 
  ggplot(aes(y = prop, x = m63_02, fill = clase.sub.hijos, 
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .85, direction = -1, option = 'viridis') +
  #cambiar geom_text tal que: Stack y cambio colores
  geom_text(position = position_stack(vjust = .5),
            size= 2.75) + 
  theme(legend.position = 'top',
        legend.title = element_blank())

g19.13
```

```{r endeud-1retiro, echo=FALSE, fig.align='center'}
datos.g19.14 <- elsoc_long_2016_2021 %>% 
  dplyr::filter(muestra == 1 & tipo_atricion == 1
                & !m43 %in% c(-888, -999, NA) & !is.na(m43) & !m63_02 %in% c(-888, -999, NA)) %>% 
  prop(m43, by = c(m63_02), na.rm = TRUE) %>% 
  sjlabelled::as_label(m43, m63_02) 

g19.14 <- datos.g19.14  %>% 
  ggplot(aes(y = prop, x = m63_02, fill = m43, 
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .85, direction = -1, option = 'viridis') +
  #cambiar geom_text tal que: Stack y cambio colores
  geom_text(position = position_stack(vjust = .5),
            size= 2.75) + 
  theme(legend.position = 'top',
        legend.title = element_blank())

g19.14
```

```{r endeud-2retiro, echo=FALSE, fig.align='center'}
datos.g19.15 <- elsoc_long_2016_2021 %>% 
  dplyr::filter(muestra == 1 & tipo_atricion == 1
                & !m43 %in% c(-888, -999, NA) & !is.na(m43) & !m63_03 %in% c(-888, -999, NA)) %>% 
  prop(m43, by = c(m63_03), na.rm = TRUE) %>% 
  sjlabelled::as_label(m43, m63_03) 

g19.15 <- datos.g19.15  %>% 
  ggplot(aes(y = prop, x = m63_03, fill = m43, 
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .85, direction = -1, option = 'viridis') +
  #cambiar geom_text tal que: Stack y cambio colores
  geom_text(position = position_stack(vjust = .5),
            size= 2.75) + 
  theme(legend.position = 'top',
        legend.title = element_blank()) 
g19.15
```

```{r deuda-retiro1, fig.align='center'}
elsoc_long_2016_2021 %>% 
  left_join(elsoc_wide_2016_2021 %>% 
              filter(!m63_02_w05 %in% c(-888, -999) & !m63_03_w05 %in% c(-888, -999)) %>%
              mutate(retiros = factor(case_when(m63_02_w05 == 1 & m63_03_w05 == 1 ~ 1,
                                                m63_02_w05 == 1 ~ 2,
                                                TRUE ~ 3),
                                      levels = c(3, 2, 1),
                                      labels = c('Ningún retiro', 
                                                 'Primer retiro', 
                                                 'Primer y segundo\n retiro'))) %>%
              select(idencuesta, retiros), by = 'idencuesta') %>% 
  filter(tipo_atricion == 1 & ola %in% c(3, 5) & !is.na(retiros) &
           !m42_01 %in% c(-888, -999) & !m42_02 %in% c(-888, -999) & 
           !m42_03 %in% c(-888, -999) & !m42_04 %in% c(-888, -999)) %>% 
  pivot_longer(cols = c(m42_01, m42_02, m42_03, m42_04)) %>% 
  prop(value, by = c(ola, retiros, name), na.rm = TRUE) %>% 
  as_label(value, ola) %>% 
  filter(value == 1) %>% 
  mutate(name = factor(name, 
                       levels = c('m42_01', 'm42_02', 'm42_03', 'm42_04'),
                       labels = c('Casa\ncomercial', 'Banco', 
                                  'Parientes', 'Otros'))) %>% 
  ggplot(aes(y = prop, x = name, fill = ola, 
             label = scales::percent(prop, accuracy = .1))) +
  facet_wrap(.~retiros) +
  theme_bw() + 
  geom_col(position = "dodge2") +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1, option = 'viridis') + 
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75)  +
  theme(legend.position = 'top',
        legend.title = element_blank())

```



