# Conflicto y cohesión territorial en pandemia

```{r library-12, include=FALSE}
knitr::opts_chunk$set(cache=FALSE, 
                      warning = FALSE, 
                      message = FALSE) 
Sys.setlocale("LC_ALL","ES_ES.UTF-8")

#devtools::install_github('edgardo-cerda/elsoc', force = TRUE)
library(elsoc)
library(tidyverse)
library(sjlabelled)
library(ggrepel)

load(file.path('1_input', 'ELSOC_Long_2016_2021_v1.00_R.RData'))

library(survey)
load("1_input/datos_elsoc.RData")
elsoc_diseno <- svydesign(ids = ~segmento, strata = ~estrato, weights = ~ponderador02, 
                          nest = TRUE, data = elsoc_panel_m1)
```

## Conflicto barrial
<!-- ### 8.1 ¿Con qué frecuencia usted/alguien de su hogar se ha molestado o incomodado por problemas con sus vecinos? según ola de estudio -->
```{r confli-olas, fig.align='center', fig.cap='¿Con qué frecuencia usted/alguien de su hogar se ha molestado o incomodado por problemas con sus vecinos? según ola de estudio '}
datos.8.1 <- elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & ola %in% c(1,2,3,4,5) & !t11_01 %in% c(-888, -999) &
           !t11_02 %in% c(-888, -999) & !t11_03 %in% c(-888, -999) & !t11_04 %in% c(-888, -999)) %>% 
  mutate(barrio_confli = (t11_01 + t11_03 + t11_03 + t11_04)/4) %>%
  mutate(barrio_confli_rec = factor(cut(barrio_confli, breaks = c(0,1,2.75,5)),
         labels = c("Nunca","Pocas o algunas veces","Muchas veces o siempre"))) %>%
  sjlabelled::as_label(ola) %>% 
  prop(x = barrio_confli_rec, by = ola, na.rm = TRUE)

g8.1 <- datos.8.1 %>% 
  ggplot(aes(y = prop, x = ola, fill = barrio_confli_rec, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .11, end = .88, direction = -1, option = 'viridis') +
  geom_text(position = position_stack(vjust = .5),
            size= 2.75, color = rep.int(c('black', 'white', 'white'), 5)) + 
  theme(legend.position = 'top', legend.title = element_blank())
g8.1
```

<!-- ### 8.2 Cambios en frecuencia de conflictos barriales -->
```{r confli-cambio, fig.align='center', fig.cap='Cambios en frecuencia de conflictos barriales'}
datos.g8.2 <- data.frame((svytable(~confli_barrial_rec + ola + idencuesta, elsoc_diseno, round = F))) %>% 
  dplyr::filter(Freq>0)  %>% 
  group_by(ola) %>% mutate(porcentaje=Freq/sum(Freq)) %>%  
  dplyr::filter(ola == '2019' | ola == '2021') %>% 
  drop_na()

etiquetas.g8.2 <- data.frame((svytable(~confli_barrial_rec + ola, elsoc_diseno, round = F))) %>% 
  group_by(ola) %>% mutate(porcentaje=Freq/sum(Freq)) %>% mutate(idencuesta = 1) %>% 
  dplyr::filter(ola == '2019' | ola == '2021') %>% 
  drop_na()

g8.2 <- 
  ggplot(datos.g8.2, aes(x = ola, fill = confli_barrial_rec, stratum = confli_barrial_rec, 
                           alluvium = idencuesta, y = porcentaje)) +
  ggalluvial::geom_flow(alpha = .66) + 
  ggalluvial::geom_stratum(linetype = 0) +
  scale_y_continuous(labels = scales::percent) + 
  ylab(label = NULL) +
  xlab(label = NULL) + 
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  scale_fill_viridis_d(begin = .11, end = .88, direction = -1, option = 'viridis') +
  geom_text(data = etiquetas.g8.2, 
            aes(label = ifelse(porcentaje > 0.03 , scales::percent(porcentaje, accuracy = .1),"")),
            position = position_stack(vjust = .5),
            show.legend = FALSE,
            size = 2.75,
            color = rep.int(c('black', 'white', 'white'),2))
g8.2
```

<!-- ### 8.3 Porcentaje con alta frecuencia de conflictos barriales, según ola del estudio y zona geográfica. Porcentaje con conflictos barriales "Siempre" o "Muchas veces".  -->
```{r confli-zona, fig.align='center', fig.cap='Porcentaje con alta frecuencia de conflictos barriales, según ola del estudio y zona geográfica. Porcentaje con conflictos barriales "Siempre" o "Muchas veces"'}
datos.8.3 <- elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & ola %in% c(4,5) & !t11_01 %in% c(-888, -999) &
           !t11_02 %in% c(-888, -999) & !t11_03 %in% c(-888, -999) & !t11_04 %in% c(-888, -999)) %>% 
  mutate(barrio_confli = (t11_01 + t11_03 + t11_03 + t11_04)/4) %>%
  mutate(barrio_confli_rec = factor(cut(barrio_confli, breaks = c(0,1,2.75,5)),
                                    labels = c("Nunca","Pocas o algunas veces","Muchas veces o siempre")),
         zona1 = factor(car::recode(region_cod, "c(1,2,3,4,15)=1; c(5,6,7,8,16)=2; c(9,10,11,12,14)=3; 13=4"),
                        levels = c(1,2,3,4), labels = c("Norte","Centro","Sur","Metropolitana"))) %>%
  sjlabelled::as_label(ola) %>% 
  prop(x = barrio_confli_rec, by = c(ola, zona1), na.rm = TRUE) %>% 
  filter(barrio_confli_rec == 'Muchas veces o siempre')

g8.3 <- datos.8.3 %>% 
  ggplot(aes(y = prop, x = zona1, fill = ola, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Dodge') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, .3)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .85, direction = -1, option = 'viridis') +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75)
g8.3
```
<!-- ### 8.4 Porcentaje con alta frecuencia de conflictos barriales, según ola del estudio y zona de residencia. Porcentaje con conflictos barriales "Siempre" o "Muchas veces".  -->
```{r confli-estrato, fig.align='center', fig.cap='Porcentaje con alta frecuencia de conflictos barriales, según ola del estudio y zona de residencia. Porcentaje con conflictos barriales "Siempre" o "Muchas veces".'}
datos.8.4 <- elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & ola %in% c(4,5) & !t11_01 %in% c(-888, -999) &
           !t11_02 %in% c(-888, -999) & !t11_03 %in% c(-888, -999) & !t11_04 %in% c(-888, -999)) %>% 
  mutate(barrio_confli = (t11_01 + t11_03 + t11_03 + t11_04)/4) %>%
  mutate(barrio_confli_rec = factor(cut(barrio_confli, breaks = c(0,1,2.75,5)),
         labels = c("Nunca","Pocas o algunas veces","Muchas veces o siempre")),
         estrato = factor(estrato, levels = c(1,2,3,4,5,6),
         labels = c('Gran\nSantiago', 'Gran\nValparaíso', 'Gran\nConcepción', 
                    'Ciudades\ngrandes', 'Ciudades\nmedianas', 'Ciudades\npequeñas'))) %>%
  sjlabelled::as_label(ola) %>% 
  prop(x = barrio_confli_rec, by = c(ola, estrato), na.rm = TRUE) %>% 
  filter(barrio_confli_rec == 'Muchas veces o siempre')

g8.4 <- datos.8.4 %>% 
  ggplot(aes(y = prop, x = estrato, fill = ola, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Dodge') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, .3)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .85, direction = -1, option = 'viridis') +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75)
g8.4
```


<!-- ### 8.5 Porcentaje con alta frecuencia de conflictos barriales, según ola del estudio y quintil de ingreso. Porcentaje con conflictos barriales "Siempre" o "Muchas veces".  -->
```{r confli-quintil, fig.align='center', fig.cap='Porcentaje con alta frecuencia de conflictos barriales, según ola del estudio y quintil de ingreso. Porcentaje con conflictos barriales "Siempre" o "Muchas veces".'}
datos.g8.5 <- data.frame(svytable(~confli_barrial_rec + ola + quintil, elsoc_diseno, round = F)) %>% 
  group_by(ola, quintil) %>% mutate(porcentaje = Freq/sum(Freq)) %>%
  filter(confli_barrial_rec == 'Muchas veces o siempre', ola == '2019' | ola == '2021')

g8.5 <- datos.g8.5 %>% 
  ggplot(aes(y = porcentaje, x = quintil, fill = ola, 
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Dodge') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, .3)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .85, direction = -1, option = 'viridis') +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75)
g8.5
```

## Conflicto barrial agregrado

```{r recode-mapas ,include=FALSE}

## library 
library(sf)
library(chilemapas)
library(rgdal)
        
## mapa comunas 

elsoc_comuna <- elsoc_panel_m1 %>% 
  filter(region_cod == 13, ola == '2021') %>% 
  group_by(comuna, comuna_cod) %>% 
  summarise(m_confli = weighted.mean(confli_barrial, ponderador02, na.rm = T),
            sd_confli = sd(confli_barrial, na.rm = T),
            m_crimen = weighted.mean(frec_crimen, ponderador02, na.rm = T),
            sd_crimen = sd(frec_crimen, na.rm = T),
            n = n())

comunas_rm <- mapa_comunas[mapa_comunas$codigo_region==13,]
comunas_rm <- merge(comunas_rm,elsoc_comuna, by.x="codigo_comuna",by.y="comuna_cod",all.x=TRUE,sort=F)

#comunas_rm <- comunas_rm %>% drop_na()

## mapa_region 

elsoc_region <- elsoc_panel_m1 %>% 
  filter(ola == '2021') %>% 
  group_by(region, region_cod) %>% 
  summarise(m_confli = weighted.mean(confli_barrial, ponderador02, na.rm = T),
            sd_confli = sd(confli_barrial, na.rm = T),
            m_crimen = weighted.mean(frec_crimen, ponderador02, na.rm = T),
            sd_crimen = sd(frec_crimen, na.rm = T),
            n = n())

elsoc_region$region_cod <- factor(elsoc_region$region_cod,
                                  labels = c('01','02','03','04','05','06','07','08',
                                            '09','10','11','13','14','15','16'))

regiones <- generar_regiones()
regiones <- merge(regiones,elsoc_region, by.x="codigo_region",by.y="region_cod",all.x=TRUE,sort=F)

regiones$mitad <- c('1','1','1','1','1','1','1','2','2','2','2','1','2','1','2','2')

#recode datos magallanes
regiones$region[is.na(regiones$region)] <- 'Magallanes'

#renombrando regiones con nombre muy largo
regiones$region[regiones$region == 'Metropolitana de santiago'] <- 'Metropolitana'
regiones$region[regiones$region == 'Libertador general bernardo ohiggins'] <- 'Ohiggins'
regiones$region[regiones$region == 'Aysen del general carlos ibannez del campo'] <- 'Aysen'
regiones$region[regiones$region == 'Arica y parinacota'] <- 'Arica'
```

```{r confli-comuna, fig.align='center', fig.cap='Frecuencia promedio de problemas con vecinos, según comuna de residencia en la región metropolitana (2021).'}
g.confli.rm <- 
  ggplot(comunas_rm) + 
  geom_sf(aes(fill = m_confli, geometry = geometry)) +
  labs(y = NULL, x = NULL, fill = "Conflictividad barrial\npromedio por comuna") +
  scale_fill_viridis_c(begin = .11, end = .88, direction = -1, option = 'viridis') +
  theme_minimal(base_size = 11)
g.confli.rm
```

```{r confli-region, fig.align='center', fig.cap='Frecuencia promedio de problemas con vecinos, según región de residencia en Chile (2021).'}
g.confli.region <- regiones %>% 
  ggplot(aes(fill = m_confli, geometry = geometry, label = region)) + 
  geom_sf() +
  coord_sf(xlim = c(-90, -65)) +
  labs(y = NULL, x = NULL, fill = "Conflictividad barrial\npromedio por región") +
  scale_fill_viridis_c(begin = .11, end = .88, direction = -1, option = 'viridis', na.value = 'white') +
  geom_sf_text(size= 3, axis.x=element_blank()) +
  theme_bw()
g.confli.region
```

## Confianza en vecinos

<!-- ### 8.6 En términos generales, ¿cuánto confía usted en sus vecinos? según ola de estudio -->
```{r vecinos-ola, fig.align='center', fig.cap='En términos generales, ¿cuánto confía usted en sus vecinos? según ola de estudio.'}
datos.8.6 <- elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & ola %in% c(1,2,3,4,5) & !t01 %in% c(-888, -999)) %>% 
  mutate(barrio_conf = factor(car::recode(t01, "c(1,2) = 1; c(3) = 2; c(4,5) = 3"),
                               levels = c(1,2,3),
                               labels = c('Muy poco o poco', 'Algo', 'Bastante o mucho'))) %>%
  sjlabelled::as_label(ola) %>%
  prop(x = barrio_conf, by = ola, na.rm = TRUE)

g8.6 <- datos.8.6 %>% 
  ggplot(aes(y = prop, x = ola, fill = barrio_conf, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .11, end = .88, direction = 1, option = 'viridis') +
  geom_text(position = position_stack(vjust = .5),
            size= 2.75, color = rep.int(c('white', 'black', 'black'), 5)) + 
  theme(legend.position = 'top',
        legend.title = element_blank())
g8.6
```

<!-- ### 8.7 En términos generales, ¿cuánto confía usted en sus vecinos? Según ola del estudio y zona geográfica. Suma de Respuestas “Bastante” y “Mucho”.  -->
```{r vecinos-zona, fig.align='center', fig.cap='En términos generales, ¿cuánto confía usted en sus vecinos? Según ola del estudio y zona geográfica. Suma de Respuestas “Bastante” y “Mucho”.'}
datos.8.7 <- elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & ola %in% c(4,5) & !t01 %in% c(-888, -999)) %>% 
  mutate(barrio_conf = factor(car::recode(t01, "c(1,2) = 1; c(3) = 2; c(4,5) = 3"),
                               levels = c(1,2,3), labels = c('Muy poco o poco','Algo','Bastante o mucho')),
         zona1 = factor(car::recode(region_cod, "c(1,2,3,4,15)=1; c(5,6,7,8,16)=2; c(9,10,11,12,14)=3; 13=4"),
                        levels = c(1,2,3,4), labels = c("Norte","Centro","Sur","Metropolitana")))%>%
  sjlabelled::as_label(ola) %>%
  prop(x = barrio_conf, by = c(ola, zona1), na.rm = TRUE) %>% 
  filter(barrio_conf == 'Bastante o mucho') %>% 
  drop_na()

g8.7 <- datos.8.7 %>% 
  ggplot(aes(y = prop, x = zona1, fill = ola, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Dodge') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .85, direction = -1, option = 'viridis') +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75)
g8.7
```

<!-- ### 8.8 En términos generales, ¿cuánto confía usted en sus vecinos? Según ola del estudio y quintil de ingreso. Suma de Respuestas “Bastante” y “Mucho”. -->
```{r vecinos-quinti, fig.align='center', fig.cap='En términos generales, ¿cuánto confía usted en sus vecinos? Según ola del estudio y quintil de ingreso. Suma de Respuestas “Bastante” y “Mucho”.'}
datos.g8.8 <- data.frame(svytable(~conf_vecinos + ola + quintil, elsoc_diseno, round = F)) %>% 
  group_by(ola, quintil) %>% mutate(porcentaje = Freq/sum(Freq)) %>%
  filter(conf_vecinos == 'Bastante o mucho', ola == '2019' | ola == '2021')

g8.8 <- datos.g8.8 %>% 
  ggplot(aes(y = porcentaje, x = quintil, fill = ola, 
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Dodge') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .85, direction = -1, option = 'viridis') +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75)
g8.8
```


## Seguridad barrial

<!-- ### 8.9 ¿Qué tan seguro o inseguro se siente en el barrio o vecindario donde usted vive? Según ola del estudio. -->
```{r seguri-ola, fig.align='center', fig.cap='¿Qué tan seguro o inseguro se siente en el barrio o vecindario donde usted vive? Según ola del estudio.'}
datos.8.9 <- elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & ola %in% c(1,2,3,4,5) & !t10 %in% c(-888, -999)) %>% 
  mutate(barrio_segur = factor(car::recode(t10, "c(1,2)=1; c(3)=2; c(4,5)=3"), levels = c(1,2,3),
                               labels = c('Muy inseguro o inseguro', 'Ni seguro ni inseguro',
                                          'Seguro o Muy seguro'))) %>%
  sjlabelled::as_label(ola) %>%
  prop(x = barrio_segur, by = ola, na.rm = TRUE)

g8.9 <- datos.8.9 %>% 
  ggplot(aes(y = prop, x = ola, fill = barrio_segur, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .11, end = .88, direction = 1, option = 'viridis') +
  geom_text(position = position_stack(vjust = .5),
            size= 2.75, color = rep.int(c('white', 'black', 'black'), 5)) + 
  theme(legend.position = 'top',
        legend.title = element_blank())
g8.9
```

<!-- ### 8.10 ¿Qué tan seguro o inseguro se siente en el barrio o vecindario donde usted vive? Según ola del estudio y zona geográfica. Suma de Respuestas "Inseguro" o ”Muy Inseguro".  -->

```{r seguri-zona, fig.align='center',fig.cap='¿Qué tan seguro o inseguro se siente en el barrio o vecindario donde usted vive? Según ola del estudio y zona geográfica. Suma de Respuestas "Inseguro" o ”Muy Inseguro".'}

datos.8.10 <- elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & ola %in% c(1,2,3,4,5) & !t10 %in% c(-888, -999)) %>% 
  mutate(barrio_segur = factor(car::recode(t10, "c(1,2)=1; c(3)=2; c(4,5)=3"), levels = c(1,2,3),
                               labels = c('Muy inseguro o inseguro', 'Ni seguro ni inseguro',
                                          'Seguro o Muy seguro')),
         zona1 = factor(car::recode(region_cod, "c(1,2,3,4,15)=1; c(5,6,7,8,16)=2; c(9,10,11,12,14)=3; 13=4"),
                        levels = c(1,2,3,4), labels = c("Norte","Centro","Sur","Metropolitana")))%>%
  sjlabelled::as_label(ola) %>%
  prop(x = barrio_segur, by = c(ola, zona1), na.rm = TRUE) %>% 
  filter(barrio_segur == 'Muy inseguro o inseguro') %>% 
  drop_na()

g8.10 <- datos.8.10 %>% 
  ggplot(aes(y = prop, x = ola, color = zona1, group = zona1,
             label = as.character(scales::percent(prop, accuracy = .1)))) +
  theme_bw() +   
  geom_line(size = 1) +
  geom_point(size = 1.8) +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0,.5)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = 0, end = .77, direction = -1, option = 'viridis') +
  ggrepel::geom_text_repel(size = 3) +
  theme(legend.position = 'top',
        legend.title = element_blank())
g8.10
```

<!-- ### 8.11 ¿Qué tan seguro o inseguro se siente en el barrio o vecindario donde usted vive? Según ola del estudio y nivel educacional. Suma de Respuestas "Inseguro" o ”Muy Inseguro". -->
```{r seguri-educ, fig.align='center',fig.cap='¿Qué tan seguro o inseguro se siente en el barrio o vecindario donde usted vive? Según ola del estudio y nivel educacional. Suma de Respuestas "Inseguro" o ”Muy Inseguro".'}

datos.8.11 <- elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & ola %in% c(1,2,3,4,5) & !t10 %in% c(-888, -999)) %>% 
  mutate(barrio_segur = factor(car::recode(t10, "c(1,2)=1; c(3)=2; c(4,5)=3"), levels = c(1,2,3),
                               labels = c('Muy inseguro o inseguro', 'Ni seguro ni inseguro',
                                          'Seguro o Muy seguro')),
         educ = factor(car::recode(m01,"c(1,2,3)=1; c(4,5)=2; c(6,7)=3; c(8,9,10)=4"),
                        levels = c(1,2,3,4), labels = c("Basica","Media","Tecnica","Universitaria"))) %>%
  sjlabelled::as_label(ola) %>%
  prop(x = barrio_segur, by = c(ola, educ), na.rm = TRUE) %>% 
  filter(barrio_segur == 'Muy inseguro o inseguro') %>% 
  drop_na()

g8.11 <- datos.8.11 %>% 
  ggplot(aes(y = prop, x = ola, color = educ, group = educ,
             label = as.character(scales::percent(prop, accuracy = .1)))) +
  theme_bw() +   
  geom_line(size = 1) +
  geom_point(size = 1.8) +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0,.5)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = 0, end = .77, direction = -1, option = 'viridis') +
  ggrepel::geom_text_repel(size = 3) +
  theme(legend.position = 'top',
        legend.title = element_blank())
g8.11
```

<!-- ### 8.12 ¿Qué tan seguro o inseguro se siente en el barrio o vecindario donde usted vive? Según ola del estudio y tramos de edad. Suma de Respuestas "Inseguro" o ”Muy Inseguro". -->
```{r seguri-edad, fig.align='center',fig.cap='¿Qué tan seguro o inseguro se siente en el barrio o vecindario donde usted vive? Según ola del estudio y tramos de edad. Suma de Respuestas "Inseguro" o ”Muy Inseguro".'}
datos.8.12 <- elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & ola %in% c(1,2,3,4,5) & !t10 %in% c(-888, -999)) %>% 
  mutate(barrio_segur = factor(car::recode(t10, "c(1,2)=1; c(3)=2; c(4,5)=3"), levels = c(1,2,3),
                               labels = c('Muy inseguro o inseguro', 'Ni seguro ni inseguro',
                                          'Seguro o Muy seguro')),
         edadt = factor(car::recode(m0_edad, "18:29=1;30:49=2;50:64=3;65:150=4"),
                        levels = c(1,2,3,4), labels = c('18-29', '30-49', '50-64', '65 o más'))) %>%
  sjlabelled::as_label(ola) %>%
  prop(x = barrio_segur, by = c(ola, edadt), na.rm = TRUE) %>% 
  filter(barrio_segur == 'Muy inseguro o inseguro') %>% 
  drop_na()

g8.12 <- datos.8.12 %>% 
  ggplot(aes(y = prop, x = ola, color = edadt, group = edadt,
             label = as.character(scales::percent(prop, accuracy = .1)))) +
  theme_bw() +   
  geom_line(size = 1) +
  geom_point(size = 1.8) +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0,.5)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = 0, end = .77, direction = -1, option = 'viridis') +
  ggrepel::geom_text_repel(size = 3) +
  theme(legend.position = 'top',
        legend.title = element_blank())
g8.12
```

<!-- ### 8.13 ¿Qué tan seguro o inseguro se siente en el barrio o vecindario donde usted vive? Según ola del estudio y quintil de ingreso per capita. Suma de Respuestas "Seguro" o ”Muy Seguro". -->
```{r seguri-quintil, fig.align='center',fig.cap='¿Qué tan seguro o inseguro se siente en el barrio o vecindario donde usted vive? Según ola del estudio y quintil de ingreso per capita. Suma de Respuestas "Seguro" o ”Muy Seguro".'}

datos.g8.13 <- data.frame((svytable(~quintil + ola + segur_barrio, elsoc_diseno, round = F))) %>% 
  group_by(ola, quintil) %>% mutate(porcentaje=Freq/sum(Freq)) %>% 
  filter(segur_barrio == "Seguro o Muy seguro", quintil == "Q1" | quintil == "Q5") 

g8.13 <- 
  ggplot(datos.g8.13, aes(y = porcentaje, x = ola, color = quintil, group = quintil,
                          label = as.character(scales::percent(porcentaje, accuracy = .1)))) +
  theme_bw() +   
  geom_line(size = 1) +
  geom_point(size = 1.8) +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0,1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .22, end = .77, direction = -1, option = 'viridis') +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75) +
  theme(legend.position = 'top',
        legend.title = element_blank())
g8.13
```

## Empeligrosamiento barrial

<!-- ### 8.14 ¿Con qué frecuencia se han producido crímenes (riñas, robos y tráfico de drogas) en su barrio?, según ola de estudio. -->
```{r crim-olas, fig.align='center', fig.cap='¿Con qué frecuencia se han producido crímenes (riñas, robos y tráfico de drogas) en su barrio?, según ola de estudio.'}
datos.8.14 <- elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & ola %in% c(1,2,3,4,5) &
           !t09_01 %in% c(-888, -999) & !t09_02 %in% c(-888, -999) & !t09_03 %in% c(-888, -999)) %>% 
  mutate(barrio_crim = (t09_01 + t09_02 + t09_03)/3) %>% 
  mutate(barrio_crim_rec = factor(cut(barrio_crim, breaks = c(0,1,2.67,5)),
                                  labels = c("Nunca","Pocas o algunas veces","Muchas veces o siempre"))) %>%
  sjlabelled::as_label(ola) %>% 
  prop(x = barrio_crim_rec, by = ola, na.rm = TRUE)

g8.14 <- datos.8.14 %>% 
  ggplot(aes(y = prop, x = ola, fill = barrio_crim_rec, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .11, end = .88, direction = -1, option = 'viridis') +
  geom_text(position = position_stack(vjust = .5),
            size= 2.75, color = rep.int(c('black', 'white', 'white'), 5)) + 
  theme(legend.position = 'top', legend.title = element_blank())
g8.14
```

<!-- ### 8.15 ¿Con qué frecuencia se han producido crímenes (riñas, robos y tráfico de drogas) en su barrio?, según ola del estudio y zona geográfica. Porcentaje de experiencias de criminalidad "Siempre" o "Muchas veces".  -->
```{r crim-zona, fig.align='center', fig.cap='¿Con qué frecuencia se han producido crímenes (riñas, robos y tráfico de drogas) en su barrio?, según ola del estudio y zona geográfica. Porcentaje de experiencias de criminalidad "Siempre" o "Muchas veces".'}
datos.8.15 <- elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & ola %in% c(4,5) &
           !t09_01 %in% c(-888, -999) & !t09_02 %in% c(-888, -999) & !t09_03 %in% c(-888, -999)) %>% 
  mutate(barrio_crim = (t09_01 + t09_02 + t09_03)/3) %>% 
  mutate(barrio_crim_rec = factor(cut(barrio_crim, breaks = c(0,1,2.67,5)),
                                  labels = c("Nunca","Pocas o algunas veces","Muchas veces o siempre")),
         zona1 = factor(car::recode(region_cod, "c(1,2,3,4,15)=1; c(5,6,7,8,16)=2; c(9,10,11,12,14)=3; 13=4"),
                        levels = c(1,2,3,4), labels = c("Norte","Centro","Sur","Metropolitana"))) %>%
  sjlabelled::as_label(ola) %>% 
  prop(x = barrio_crim_rec, by = c(ola, zona1), na.rm = TRUE) %>% 
  filter(barrio_crim_rec == 'Muchas veces o siempre')

g8.15 <- datos.8.15 %>% 
  ggplot(aes(y = prop, x = zona1, fill = ola, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Dodge') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, .5)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .85, direction = -1, option = 'viridis') +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75)
g8.15
```

<!-- ### 8.16 ¿Con qué frecuencia se han producido crímenes (riñas, robos y tráfico de drogas) en su barrio?, según ola del estudio y tipo de ciudad. Porcentaje de experiencias de criminalidad "Siempre" o "Muchas veces".  -->
```{r crim-estrato, fig.align='center', fig.cap='¿Con qué frecuencia se han producido crímenes (riñas, robos y tráfico de drogas) en su barrio?, según ola del estudio y tipo de ciudad. Porcentaje de experiencias de criminalidad "Siempre" o "Muchas veces".'}
datos.8.16 <- elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & ola %in% c(4,5) &
           !t09_01 %in% c(-888, -999) & !t09_02 %in% c(-888, -999) & !t09_03 %in% c(-888, -999)) %>% 
  mutate(barrio_crim = (t09_01 + t09_02 + t09_03)/3) %>% 
  mutate(barrio_crim_rec = factor(cut(barrio_crim, breaks = c(0,1,2.67,5)),
                                  labels = c("Nunca","Pocas o algunas veces","Muchas veces o siempre")),
         estrato = factor(estrato, levels = c(1,2,3,4,5,6),
                          labels = c('Gran\nSantiago', 'Gran\nValparaíso', 'Gran\nConcepción',
                                     'Ciudades\ngrandes', 'Ciudades\nmedianas', 'Ciudades\npequeñas'))) %>%
  sjlabelled::as_label(ola) %>% 
  prop(x = barrio_crim_rec, by = c(ola, estrato), na.rm = TRUE) %>% 
  filter(barrio_crim_rec == 'Muchas veces o siempre')

g8.16 <- datos.8.16 %>% 
  ggplot(aes(y = prop, x = estrato, fill = ola, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Dodge') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, .5)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .85, direction = -1, option = 'viridis') +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75)
g8.16
```


<!-- ### 8.17 ¿Con qué frecuencia se han producido crímenes (riñas, robos y tráfico de drogas) en su barrio?, según ola del estudio y quintil de ingreso. Porcentaje de experiencias de criminalidad "Siempre" o "Muchas veces".  -->
```{r crim-quintil, fig.align='center', fig.cap='¿Con qué frecuencia se han producido crímenes (riñas, robos y tráfico de drogas) en su barrio?, según ola del estudio y quintil de ingreso. Porcentaje de experiencias de criminalidad "Siempre" o "Muchas veces".'}

datos.g8.17 <- data.frame(svytable(~frec_crimen_rec + ola + quintil, elsoc_diseno, round = F)) %>% 
  group_by(ola, quintil) %>% mutate(porcentaje = Freq/sum(Freq)) %>%
  filter(frec_crimen_rec == 'Muchas veces o siempre', ola == '2019' | ola == '2021')

g8.17 <- datos.g8.17 %>% 
  ggplot(aes(y = porcentaje, x = quintil, fill = ola, 
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Dodge') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, .5)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .85, direction = -1, option = 'viridis') +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75)
g8.17
```

## Distanciamiento y comportamiento prosocial en pandemia

### Distanciamiento social

```{r dist-total, fig.align='center', fig.cap='¿En qué medida usted ha seguido la recomendación de quedarse en su hogar, manteniendo el aislamiento social? (2021).'}
datos.8.18 <- elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & ola %in% c(5) & !c48 %in% c(-888, -999)) %>% 
  mutate(dis_soc = factor(car::recode(c48, "c(1,2) = 1; c(3) = 2; c(4,5) = 3"),
                               levels = c(1,2,3),
                               labels= c("Nunca o casi nunca", "A veces",
                                         "Frecuentemente o\nmuy frecuentemente"))) %>%
  prop(x = dis_soc, na.rm = TRUE)

g8.18 <- datos.8.18 %>% 
  ggplot(aes(y = prop, x = dis_soc, fill = dis_soc, 
             label = as.character(scales::percent(prop, accuracy = .1)))) +
  theme_bw() + 
  geom_col(position = 'Dodge') +
  scale_y_continuous(labels = scales::percent,
                      limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .85, direction = -1, option = 'viridis') +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75) +
  theme(legend.position = 'none', 
        legend.title = element_blank())
g8.18
```

```{r dist-quintil, fig.align='center', fig.cap='¿En qué medida usted ha seguido la recomendación de quedarse en su hogar, manteniendo el aislamiento social? según quintil de ingreso (2021).'}
datos.g8.19 <- 
  data.frame((svytable(~aislamiento + quintil + ola, elsoc_diseno, round = F))) %>%
  group_by(quintil, ola) %>% mutate(porcentaje = Freq/sum(Freq)) %>% 
  filter(ola == '2021', aislamiento == 'Frecuentemente o muy frecuentemente') %>% 
  drop_na()

g8.19 <- 
  datos.g8.19 %>% 
  ggplot(aes(y = porcentaje, x = quintil, fill = aislamiento, 
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) + 
  theme_bw() + 
  geom_col() +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .22, direction = 1, option = 'viridis') +
  geom_text(position = position_stack(vjust = .5),
            size= 2.75, color = 'white') + 
  theme(legend.position = 'none',
        legend.title = element_blank())
g8.19
```


```{r dist-edad, fig.align='center', fig.cap='¿En qué medida usted ha seguido la recomendación de quedarse en su hogar, manteniendo el aislamiento social? según edad (2021).'}
datos.8.20 <- elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & ola %in% c(5) & !c48 %in% c(-888, -999)) %>% 
  mutate(dis_soc = factor(car::recode(c48, "c(1,2) = 1; c(3) = 2; c(4,5) = 3"),
                               levels = c(1,2,3),
                               labels= c("Nunca o\ncasi nunca", "A veces",
                                         "Frecuentemente o\nmuy frecuentemente")),
         edadt = factor(car::recode(m0_edad, "18:29=1; 30:49=2; 50:64=3 ;65:150=4"),
                        levels = c(1,2,3,4), labels = c('18-29', '30-49', '50-64', '65 o más'))) %>%
  prop(x = dis_soc, by = edadt, na.rm = TRUE)

g8.20 <- datos.8.20 %>%
  ggplot(aes(y = prop, x = edadt, fill = dis_soc, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .99, direction = -1, option = 'viridis') +
  geom_text(position = position_stack(vjust = .5),
            size= 2.75, color = rep.int(c( 'black','black','white'), 4)) + 
  theme(legend.position = 'top',
        legend.title = element_blank())
g8.20
```

```{r dist-estrato, fig.align='center', fig.cap='¿En qué medida usted ha seguido la recomendación de quedarse en su hogar, manteniendo el aislamiento social? según estrato muestral (2021).'}
datos.8.21 <- elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & ola %in% c(5) & !c48 %in% c(-888, -999)) %>% 
  mutate(dis_soc = factor(car::recode(c48, "c(1,2) = 1; c(3) = 2; c(4,5) = 3"),
                               levels = c(1,2,3),
                               labels= c("Nunca o\ncasi nunca", "A veces",
                                         "Frecuentemente o\nmuy frecuentemente")),
         estrato = factor(estrato, levels = c(1,2,3,4,5,6),
                          labels = c('Gran\nSantiago', 'Gran\nValparaíso', 'Gran\nConcepción',
                                     'Ciudades\ngrandes', 'Ciudades\nmedianas', 'Ciudades\npequeñas'))) %>%
  prop(x = dis_soc, by = estrato, na.rm = TRUE)

g8.21 <- datos.8.21 %>%
  ggplot(aes(y = prop, x = estrato, fill = dis_soc, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .99, direction = -1, option = 'viridis') +
  geom_text(position = position_stack(vjust = .5),
            size= 2.75, color = rep.int(c( 'black','black','white'), 6)) + 
  theme(legend.position = 'top',
        legend.title = element_blank())
g8.21
```

```{r dist-telet, fig.align='center', fig.cap='¿En qué medida usted ha seguido la recomendación de quedarse en su hogar, manteniendo el aislamiento social? según tipo de trabajo en pandemia (2021).'}
datos.8.22 <- elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & ola %in% c(5) & !c48 %in% c(-888, -999) & !m60 %in% c(-888, -999)) %>% 
  mutate(dis_soc = factor(car::recode(c48, "c(1,2) = 1; c(3) = 2; c(4,5) = 3"),
                               levels = c(1,2,3),
                               labels= c("Nunca o\ncasi nunca", "A veces",
                                         "Frecuentemente o\nmuy frecuentemente")),
         trab_pandemia = factor(m60, labels = c('Trabajo de manera\ncompleta desde el hogar',
                                                'Trabajo de manera\nparcial desde el hogar',
                                                'Trabajo fuera\ndel hogar'))) %>%
  prop(x = dis_soc, by = trab_pandemia, na.rm = TRUE) %>% 
  drop_na()

g8.22 <- datos.8.22 %>%
  ggplot(aes(y = prop, x = trab_pandemia, fill = dis_soc, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .99, direction = -1, option = 'viridis') +
  geom_text(position = position_stack(vjust = .5),
            size= 2.75, color = rep.int(c( 'black','black','white'), 3)) + 
  theme(legend.position = 'top',
        legend.title = element_blank())
g8.22
```
### Comportamiento prosocial

```{r dist-prosocial, fig.align='center', fig.cap='Frecuencia de comportamientos pro-sociales, según ola de estudio. Porcentaje de respuestas de "Lo hizo mas de dos veces".'}

elsoc_panel_m1 <- elsoc_panel_m1 %>%
  mutate(frec_veci = factor(car::recode(c07_01, "1=1;2=2;3=3"),
                           labels = c('Nunca lo hizo', 'Lo hizo una o dos veces', 'Lo hizo mas de dos veces')),
         frec_visi = factor(car::recode(c07_03, "1=1;2=2;3=3"),
                               labels = c('Nunca lo hizo', 'Lo hizo una o dos veces', 'Lo hizo mas de dos veces')),
         frec_reun = factor(car::recode(c07_02, "1=1;2=2;3=3"),
                            labels = c('Nunca lo hizo', 'Lo hizo una o dos veces', 'Lo hizo mas de dos veces')),
         frec_conv = factor(car::recode(c07_07, "1=1;2=2;3=3"),
                          labels = c('Nunca lo hizo', 'Lo hizo una o dos veces', 'Lo hizo mas de dos veces')))

elsoc_diseno <- svydesign(ids = ~segmento, strata = ~estrato, weights = ~ponderador02, 
                             nest = TRUE, data = elsoc_panel_m1)

datos.fveci <- data.frame((svytable(~frec_veci + ola, elsoc_diseno, round = F))) %>%
  group_by(ola) %>% mutate(p_veci=Freq/sum(Freq))
datos.fveci$ola <- NULL

datos.fvisit <- data.frame((svytable(~frec_visi + ola, elsoc_diseno, round = F))) %>% 
  group_by(ola) %>% mutate(p_visi=Freq/sum(Freq))
datos.fvisit$ola <- NULL

datos.freu <- data.frame((svytable(~frec_reun + ola, elsoc_diseno, round = F))) %>% 
  group_by(ola) %>% mutate(p_reun=Freq/sum(Freq))
datos.freu$ola <- NULL

datos.fconv <- data.frame((svytable(~frec_conv + ola, elsoc_diseno, round = F))) %>% 
  group_by(ola) %>% mutate(p_conv=Freq/sum(Freq))

datos.g0.6 <- cbind(datos.fveci, datos.fvisit, datos.freu, datos.fconv)

#trasponer según variable
datos.g0.6a <- datos.g0.6 %>% 
  pivot_longer(cols = starts_with('frec_'))  %>%
  mutate(variable = factor(name,
                           labels = c('Visito casa\nde vecino', 
                                      'Amigos visitaron\nsu casa',
                                      'Asistio a reunion sobre temas\nde interes publico/comunitario',
                                      'Converso con persona\nen problemas o deprimida'))) %>%
  drop_na()

datos.g0.6a$porcentaje <- with(datos.g0.6a, case_when(
  variable == 'Visito casa\nde vecino' ~ p_veci,
  variable == 'Amigos visitaron\nsu casa' ~ p_visi,
  variable == 'Asistio a reunion sobre temas\nde interes publico/comunitario' ~ p_reun,
  variable == 'Converso con persona\nen problemas o deprimida' ~ p_conv))

#Paso 1.2: filtrar el subset manteniendo "De acuerdo o totalmente de acuerdo"
subset.g0.6 <- droplevels(subset(datos.g0.6a, value == 'Lo hizo mas de dos veces'))

g0.6 <- 
  ggplot(subset.g0.6, aes(y = porcentaje, x = ola, color = variable, group = variable,
                              label = as.character(scales::percent(porcentaje, accuracy = .1)))) +
  theme_bw() +   
  geom_line(size = 1) +
  geom_point(size = 1.8) +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0,1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = 0, end = .77, direction = 1, option = 'viridis') +
  ggrepel::geom_text_repel(position = position_dodge(width = .9),
                  size = 3) +
  theme(legend.position = 'top',
        legend.title = element_blank())

g0.6

```
 
```{r dist-barrio, fig.align='center', fig.cap='Percepción de conflictividad, empeligrosamiento e inseguridad en el barrio, según cumplimiento de aislamiento social (2021). Porcentaje de personas que responden "Muchas veces o siempre" o "Muy inseguro o inseguro".'}

confli.g0.7 <- data.frame((svytable(~confli_barrial_rec + aislamiento + ola,
                       elsoc_diseno, round = F))) %>%
  group_by(ola, aislamiento) %>% mutate(porcentaje = Freq/sum(Freq)) %>% drop_na() %>% 
  filter(confli_barrial_rec == 'Muchas veces o siempre' & ola == 2021) %>% 
  mutate(variable = 'Conflictividad barrial')

crim.g0.7 <- data.frame((svytable(~frec_crimen_rec + aislamiento + ola,
                       elsoc_diseno, round = F))) %>%
  group_by(ola, aislamiento) %>% mutate(porcentaje = Freq/sum(Freq)) %>% drop_na() %>% 
  filter(frec_crimen_rec == 'Muchas veces o siempre' & ola == 2021) %>% 
  mutate(variable = 'Empeligrosamiento barrial')

segur.g0.7 <- data.frame((svytable(~segur_barrio + aislamiento + ola,
                       elsoc_diseno, round = F))) %>%
  group_by(ola, aislamiento) %>% mutate(porcentaje = Freq/sum(Freq)) %>% drop_na() %>% 
  filter(segur_barrio == 'Muy inseguro o inseguro' & ola == 2021) %>% 
  mutate(variable = 'Inseguridad barrial')

datos.g0.7 <- rbind(confli.g0.7, crim.g0.7, segur.g0.7)

g0.7 <- datos.g0.7 %>% 
  ggplot(aes(y = porcentaje, x = variable, fill = aislamiento, 
             label = scales::percent(porcentaje, accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, .8)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .85, direction = -1, option = 'viridis') +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75)

g0.7
```
