## Aislamiento social (caracterízación)

```{r disenno-13, include=FALSE}
knitr::opts_chunk$set(cache=FALSE, 
                      warning = FALSE, 
                      message = FALSE) 

Sys.setlocale("LC_ALL","ES_ES.UTF-8")

rm(list = ls())
library(survey)
library(tidyverse)
library(ggrepel)
getwd()
load("1_input/datos_elsoc.RData")

elsoc_diseno <- svydesign(ids = ~segmento, strata = ~estrato, weights = ~ponderador02, 
                          nest = TRUE, data = elsoc_panel_m1)
```

```{r recode-aisl-soc, include=FALSE}

elsoc_panel_m1 <- elsoc_panel_m1 %>%
  mutate(frec_veci = factor(car::recode(c07_01, "1=1;2=2;3=3"),
                           labels = c('Nunca lo hizo', 'Lo hizo una o dos veces', 'Lo hizo mas de dos veces')),
         frec_visi = factor(car::recode(c07_03, "1=1;2=2;3=3"),
                               labels = c('Nunca lo hizo', 'Lo hizo una o dos veces', 'Lo hizo mas de dos veces')),
         frec_reun = factor(car::recode(c07_02, "1=1;2=2;3=3"),
                            labels = c('Nunca lo hizo', 'Lo hizo una o dos veces', 'Lo hizo mas de dos veces')),
         frec_conv = factor(car::recode(c07_07, "1=1;2=2;3=3"),
                          labels = c('Nunca lo hizo', 'Lo hizo una o dos veces', 'Lo hizo mas de dos veces')))

elsoc_diseno <- svydesign(ids = ~segmento, strata = ~estrato, weights = ~ponderador02, 
                             nest = TRUE, data = elsoc_panel_m1)
```


```{r aisl-total, fig.align='center', fig.cap='¿En qué medida usted ha seguido la recomendación de quedarse en su hogar, manteniendo el aislamiento social? (2021).'}
datos.g13.1 <- data.frame(svytable(~aislamiento, elsoc_diseno, round = F)) %>% 
  mutate(porcentaje = Freq/sum(Freq)) %>% 
  drop_na()

g13.1 <- datos.g13.1 %>% 
  ggplot(aes(y = porcentaje, x = aislamiento, fill = aislamiento, 
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) +
  theme_bw() + 
    geom_col() +
    scale_y_continuous(labels = scales::percent,
                       limits = c(0, 1)) +
    ylab(label = NULL) +
    xlab(label = NULL) +
    scale_fill_viridis_d(begin = 0, end = .85, direction = -1, option = 'viridis') +
    geom_text(vjust = -0.8,
              position = position_dodge(width = .9),
              size= 2.75) +
    theme(legend.position = 'none', 
          legend.title = element_blank())
g13.1
```

```{r aisl-quintil, fig.align='center', fig.cap='¿En qué medida usted ha seguido la recomendación de quedarse en su hogar, manteniendo el aislamiento social? según quintil de ingreso (2021).'}
datos.g13.2 <- 
  data.frame((svytable(~aislamiento + quintil + ola, elsoc_diseno, round = F))) %>%
  group_by(quintil, ola) %>% mutate(porcentaje = Freq/sum(Freq)) %>% 
  filter(ola == '2021') %>% 
  drop_na()

g13.2 <- 
  datos.g13.2 %>% 
  ggplot(aes(y = porcentaje, x = quintil, fill = aislamiento, 
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .99, direction = -1, option = 'viridis') +
  geom_text(position = position_stack(vjust = .5),
            size= 2.75, color = rep.int(c( 'black','black','white'), 5)) + 
  theme(legend.position = 'top',
        legend.title = element_blank())
g13.2
```

```{r aisl-edad, fig.align='center', fig.cap='¿En qué medida usted ha seguido la recomendación de quedarse en su hogar, manteniendo el aislamiento social? según edad (2021).'}
datos.g13.3 <- 
  data.frame((svytable(~aislamiento + edadt + ola, elsoc_diseno, round = F))) %>%
  group_by(edadt, ola) %>% mutate(porcentaje = Freq/sum(Freq)) %>% 
  filter(ola == '2021') %>% 
  drop_na()

g13.3 <- 
  datos.g13.3 %>% 
  ggplot(aes(y = porcentaje, x = edadt, fill = aislamiento, 
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .99, direction = -1, option = 'viridis') +
  geom_text(position = position_stack(vjust = .5),
            size= 2.75, color = rep.int(c( 'black','black','white'), 4)) + 
  theme(legend.position = 'top',
        legend.title = element_blank())
g13.3
```

```{r aisl-estrato, fig.align='center', fig.cap='¿En qué medida usted ha seguido la recomendación de quedarse en su hogar, manteniendo el aislamiento social? según estrato muestral (2021).'}
datos.g13.4 <- 
  data.frame((svytable(~aislamiento + estrato + ola, elsoc_diseno, round = F))) %>%
  group_by(estrato, ola) %>% mutate(porcentaje = Freq/sum(Freq)) %>% 
  filter(ola == '2021') %>% 
  drop_na()

g13.4 <- 
  datos.g13.4 %>% 
  ggplot(aes(y = porcentaje, x = estrato, fill = aislamiento, 
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .99, direction = -1, option = 'viridis') +
  geom_text(position = position_stack(vjust = .5),
            size= 2.75, color = rep.int(c( 'black','black','white'), 6)) + 
  theme(legend.position = 'top',
        legend.title = element_blank())
g13.4
```

```{r aisl-telet, fig.align='center', fig.cap='¿En qué medida usted ha seguido la recomendación de quedarse en su hogar, manteniendo el aislamiento social? según tipo de trabajo en pandemia (2021).'}
sjmisc::frq(elsoc_panel_m1$trab_pandemia)

elsoc_panel_m1 <- elsoc_panel_m1 %>%
  mutate(trab_pandemia = factor(m60, labels = c('Trabajo de manera completa desde el hogar',
                                                'Trabajo de manera parcial desde el hogar',
                                                'Trabajo fuera del hogar')))

elsoc_diseno <- svydesign(ids = ~segmento, strata = ~estrato, weights = ~ponderador02, 
                          nest = TRUE, data = elsoc_panel_m1)
datos.g13.5 <- 
  data.frame((svytable(~aislamiento + trab_pandemia + ola, elsoc_diseno, round = F))) %>%
  group_by(trab_pandemia, ola) %>% mutate(porcentaje = Freq/sum(Freq)) %>% 
  filter(ola == '2021') %>% 
  drop_na()

g13.5 <- 
  datos.g13.5 %>% 
  ggplot(aes(y = porcentaje, x = trab_pandemia, fill = aislamiento, 
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .99, direction = -1, option = 'viridis') +
  geom_text(position = position_stack(vjust = .5),
            size= 2.75, color = rep.int(c( 'black','black','white'), 3)) + 
  theme(legend.position = 'top',
        legend.title = element_blank())
g13.5
```
## Efecto de aislamiento social

```{r aisl-prosocial, fig.align='center', fig.cap='Frecuencia de comportamientos pro-sociales, según ola de estudio. Porcentaje de respuestas de "Lo hizo mas de dos veces".'}

datos.fveci <- data.frame((svytable(~frec_veci + ola, elsoc_diseno, round = F))) %>%
  group_by(ola) %>% mutate(p_veci=Freq/sum(Freq))
datos.fveci$ola <- NULL

datos.fvisit <- data.frame((svytable(~frec_visi + ola, elsoc_diseno, round = F))) %>% 
  group_by(ola) %>% mutate(p_visi=Freq/sum(Freq))
datos.fvisit$ola <- NULL

datos.freu <- data.frame((svytable(~frec_reun + ola, elsoc_diseno, round = F))) %>% 
  group_by(ola) %>% mutate(p_reun=Freq/sum(Freq))
datos.freu$ola <- NULL

datos.fconv <- data.frame((svytable(~frec_conv + ola, elsoc_diseno, round = F))) %>% 
  group_by(ola) %>% mutate(p_conv=Freq/sum(Freq))

datos.g0.6 <- cbind(datos.fveci, datos.fvisit, datos.freu, datos.fconv)

#trasponer según variable
datos.g0.6a <- datos.g0.6 %>% 
  pivot_longer(cols = starts_with('frec_'))  %>%
  mutate(variable = factor(name,
                           labels = c('Visito casa de vecino', 
                                      'Amigos visitaron su casa',
                                      'Asistio a reunion sobre temas de interes publico/comunitario',
                                      'Converso con persona en problemas o deprimida'))) %>%
  drop_na()

datos.g0.6a$porcentaje <- with(datos.g0.6a, case_when(
  variable == 'Visito casa de vecino' ~ p_veci,
  variable == 'Amigos visitaron su casa' ~ p_visi,
  variable == 'Asistio a reunion sobre temas de interes publico/comunitario' ~ p_reun,
  variable == 'Converso con persona en problemas o deprimida' ~ p_conv))

#Paso 1.2: filtrar el subset manteniendo "De acuerdo o totalmente de acuerdo"
subset.g0.6 <- droplevels(subset(datos.g0.6a, value == 'Lo hizo mas de dos veces'))

g0.6 <- 
  ggplot(subset.g0.6, aes(y = porcentaje, x = ola, color = variable, group = variable,
                              label = as.character(scales::percent(porcentaje, accuracy = .1)))) +
  theme_bw() +   
  geom_line(size = 1) +
  geom_point(size = 1.8) +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0,1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = 0, end = .77, direction = 1, option = 'viridis') +
  geom_text_repel(posilinetion = position_dodge(width = .9),
                  size = 3) +
  theme(legend.position = 'top',
        legend.title = element_blank())

g0.6

```
 
```{r aisl-barrio, fig.align='center', fig.cap='Percepción de conflictividad, empeligrosamiento e inseguridad en el barrio, según cumplimiento de aislamiento social (2021). Porcentaje de personas que responden "Muchas veces o siempre" o "Muy inseguro o inseguro".'}

confli.g0.7 <- data.frame((svytable(~confli_barrial_rec + aislamiento + ola,
                       elsoc_diseno, round = F))) %>%
  group_by(ola, aislamiento) %>% mutate(porcentaje = Freq/sum(Freq)) %>% drop_na() %>% 
  filter(confli_barrial_rec == 'Muchas veces o siempre' & ola == 2021) %>% 
  mutate(variable = 'Conflictividad barrial')

crim.g0.7 <- data.frame((svytable(~frec_crimen_rec + aislamiento + ola,
                       elsoc_diseno, round = F))) %>%
  group_by(ola, aislamiento) %>% mutate(porcentaje = Freq/sum(Freq)) %>% drop_na() %>% 
  filter(frec_crimen_rec == 'Muchas veces o siempre' & ola == 2021) %>% 
  mutate(variable = 'Empeligrosamiento barrial')

segur.g0.7 <- data.frame((svytable(~segur_barrio + aislamiento + ola,
                       elsoc_diseno, round = F))) %>%
  group_by(ola, aislamiento) %>% mutate(porcentaje = Freq/sum(Freq)) %>% drop_na() %>% 
  filter(segur_barrio == 'Muy inseguro o inseguro' & ola == 2021) %>% 
  mutate(variable = 'Inseguridad barrial')

datos.g0.7 <- rbind(confli.g0.7, crim.g0.7, segur.g0.7)

g0.7 <- datos.g0.7 %>% 
  ggplot(aes(y = porcentaje, x = variable, fill = aislamiento, 
             label = scales::percent(porcentaje, accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, .8)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .85, direction = -1, option = 'viridis') +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75)

g0.7
```

