# Distanciamiento y comportamiento prosocial en pandemia

## Distanciamiento social

```{r dist-total, fig.align='center', fig.cap='¿En qué medida usted ha seguido la recomendación de quedarse en su hogar, manteniendo el aislamiento social? (2021).'}

datos.9.1 <- elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & ola %in% c(5) & !c48 %in% c(-888, -999)) %>% 
  mutate(dis_soc = factor(car::recode(c48, "c(1,2) = 1; c(3) = 2; c(4,5) = 3"),
                               levels = c(1,2,3),
                               labels= c("Nunca o casi nunca", "A veces",
                                         "Frecuentemente o\nmuy frecuentemente"))) %>%
  prop(x = dis_soc, na.rm = TRUE)

g9.1 <- datos.9.1 %>% 
  ggplot(aes(y = prop, x = dis_soc, fill = dis_soc, 
             label = as.character(scales::percent(prop, accuracy = .1)))) +
  theme_bw() + 
  geom_col(position = 'Dodge') +
  scale_y_continuous(labels = scales::percent,
                      limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .85, direction = -1, option = 'viridis') +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75) +
  theme(legend.position = 'none', 
        legend.title = element_blank())
g9.1
```

```{r dist-quintil, fig.align='center', fig.cap='¿En qué medida usted ha seguido la recomendación de quedarse en su hogar, manteniendo el aislamiento social? según quintil de ingreso. Suma de respuestas "Frecuente o "Muy frecuentemente" (2021).'}
datos.9.2 <- elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & ola %in% c(5) & !t01 %in% c(-888, -999)) %>% 
  mutate(dis_soc = factor(car::recode(c48, "c(1,2) = 1; c(3) = 2; c(4,5) = 3"),
                               levels = c(1,2,3), labels= c("Nunca o casi nunca", "A veces",
                                         "Frecuentemente o\nmuy frecuentemente")),
         m30 = as.numeric(car::recode(m30,"1=110000;2=251000;3=305000;4=355000;5=400000;6=445000;
                                           7=490000;8=535000;9=585000;10=640000;11=700000;12=765000;
                                           13=845000;14=935000;15=1040000;16=1180000;17=1375000;
                                           18=1670000;19=2275000;20=2700000;NA=NA")),
         m29_imp = ifelse(!is.na(m29),m29, m30),
         n_hogar = case_when(ola == 1 ~ nhogar1, ola == 2 ~ m46_nhogar,
                             ola == 3 ~ m54, ola == 4 ~ m54, ola == 5 ~ m54)) %>%
  mutate(ing_pc = (m29_imp/n_hogar)) %>%
  sjlabelled::as_label(ola) %>% 
  group_by(ola) %>% 
  mutate(quintil = factor(ntile(-desc(ing_pc), 5), levels = c(1,2,3,4,5),
         labels = c('Q1', 'Q2', 'Q3', 'Q4', 'Q5'))) %>% 
  prop(x = dis_soc, by = c(ola, quintil), na.rm = TRUE) %>% 
  filter(dis_soc == "Frecuentemente o\nmuy frecuentemente")

g9.2 <- 
  datos.9.2 %>% 
  ggplot(aes(y = prop, x = quintil, fill = quintil, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Dodge') +
  scale_y_continuous(labels = scales::percent,
                      limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .99, direction = -1, option = 'viridis') +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75) + 
  theme(legend.position = 'none',
        legend.title = element_blank())
g9.2
```


```{r dist-edad, fig.align='center', fig.cap='¿En qué medida usted ha seguido la recomendación de quedarse en su hogar, manteniendo el aislamiento social? según edad. Suma de respuestas "Frecuente o "Muy frecuentemente" (2021).'}
datos.9.3 <- elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & ola %in% c(5) & !c48 %in% c(-888, -999)) %>% 
  mutate(dis_soc = factor(car::recode(c48, "c(1,2) = 1; c(3) = 2; c(4,5) = 3"),
                               levels = c(1,2,3),
                               labels= c("Nunca o\ncasi nunca", "A veces",
                                         "Frecuentemente o\nmuy frecuentemente")),
         edadt = factor(car::recode(m0_edad, "18:29=1; 30:49=2; 50:64=3 ;65:150=4"),
                        levels = c(1,2,3,4), labels = c('18-29', '30-49', '50-64', '65 o más'))) %>%
  prop(x = dis_soc, by = edadt, na.rm = TRUE) %>% 
  filter(dis_soc == "Frecuentemente o\nmuy frecuentemente")

g9.3 <- 
  datos.9.3 %>% 
  ggplot(aes(y = prop, x = edadt, fill = edadt, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Dodge') +
  scale_y_continuous(labels = scales::percent,
                      limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .99, direction = -1, option = 'viridis') +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75) + 
  theme(legend.position = 'none',
        legend.title = element_blank())
g9.3
```

```{r dist-estrato, fig.align='center', fig.cap='¿En qué medida usted ha seguido la recomendación de quedarse en su hogar, manteniendo el aislamiento social? según estrato muestral (2021).'}
datos.9.4 <- elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & ola %in% c(5) & !c48 %in% c(-888, -999)) %>% 
  mutate(dis_soc = factor(car::recode(c48, "c(1,2) = 1; c(3) = 2; c(4,5) = 3"),
                               levels = c(1,2,3),
                               labels= c("Nunca o\ncasi nunca", "A veces",
                                         "Frecuentemente o\nmuy frecuentemente")),
         estrato = factor(estrato, levels = c(1,2,3,4,5,6),
                          labels = c('Gran\nSantiago', 'Gran\nValparaíso', 'Gran\nConcepción',
                                     'Ciudades\ngrandes', 'Ciudades\nmedianas', 'Ciudades\npequeñas'))) %>%
  prop(x = dis_soc, by = estrato, na.rm = TRUE)

g9.4 <- datos.9.4 %>%
  ggplot(aes(y = prop, x = estrato, fill = dis_soc, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .99, direction = -1, option = 'viridis') +
  geom_text(position = position_stack(vjust = .5),
            size= 2.75, color = rep.int(c( 'black','black','white'), 6)) + 
  theme(legend.position = 'top',
        legend.title = element_blank())
g9.4
```

```{r dist-telet, fig.align='center', fig.cap='¿En qué medida usted ha seguido la recomendación de quedarse en su hogar, manteniendo el aislamiento social? según tipo de trabajo en pandemia. Suma de respuestas "Frecuente o "Muy frecuentemente" (2021).'}
datos.9.5 <- elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & ola %in% c(5) & !c48 %in% c(-888, -999) & !m60 %in% c(-888, -999)) %>% 
  mutate(dis_soc = factor(car::recode(c48, "c(1,2) = 1; c(3) = 2; c(4,5) = 3"),
                               levels = c(1,2,3),
                               labels= c("Nunca o\ncasi nunca", "A veces",
                                         "Frecuentemente o\nmuy frecuentemente")),
         trab_pandemia = factor(m60, labels = c('Trabajo de manera\ncompleta desde el hogar',
                                                'Trabajo de manera\nparcial desde el hogar',
                                                'Trabajo fuera\ndel hogar'))) %>%
  prop(x = dis_soc, by = trab_pandemia, na.rm = TRUE) %>% 
  filter(dis_soc == "Frecuentemente o\nmuy frecuentemente") %>% 
  drop_na()

g9.5 <- 
  datos.9.5 %>% 
  ggplot(aes(y = prop, x = trab_pandemia, fill = trab_pandemia, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Dodge') +
  scale_y_continuous(labels = scales::percent,
                      limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .99, direction = -1, option = 'viridis') +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75) + 
  theme(legend.position = 'none',
        legend.title = element_blank())
g9.5
```
```{r dist-covid, fig.align='center', fig.cap='¿En qué medida usted ha seguido la recomendación de quedarse en su hogar, manteniendo el aislamiento social? según diagnóstico con coronavirus. Suma de respuestas "Frecuente o "Muy frecuentemente" (2021).'}
datos.9.6 <- elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & ola %in% c(5) & !c48 %in% c(-888, -999) & !s31 %in% c(-888, -999)) %>% 
  mutate(dis_soc = factor(car::recode(c48, "c(1,2) = 1; c(3) = 2; c(4,5) = 3"),
                               levels = c(1,2,3),
                               labels= c("Nunca o\ncasi nunca", "A veces",
                                         "Frecuentemente o\nmuy frecuentemente")),
         covid = factor(s31, labels = c('Si','No'))) %>%
  prop(x = dis_soc, by = covid, na.rm = TRUE) %>% 
  filter(dis_soc == "Frecuentemente o\nmuy frecuentemente") %>% 
  drop_na()

g9.6 <- 
  datos.9.6 %>% 
  ggplot(aes(y = prop, x = covid, fill = covid, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Dodge') +
  scale_y_continuous(labels = scales::percent,
                      limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .77, direction = -1, option = 'viridis') +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75) + 
  theme(legend.position = 'none',
        legend.title = element_blank())
g9.6
```
## Efecto del distanciamiento social 

### Comportamiento pro-social

```{r dist-pros, fig.align='center', fig.cap='Frecuencia de comportamientos pro-sociales, según ola de estudio. Porcentaje de respuestas de "Lo hizo mas de dos veces".'}

datos.9.7 <- elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1) %>%  
  select(c07_01, c07_03, c07_02, c07_07, ola, ponderador02, segmento_disenno, estrato_disenno) %>% 
  pivot_longer(cols = c(c07_01, c07_03, c07_02, c07_07)) %>% 
  filter(!value %in% c(-888, -999)) %>% 
  prop(value == 3, by = c(ola, name), na.rm = TRUE) %>% 
  mutate(name = factor(name,
                       levels = c('c07_01', 'c07_03', 'c07_02', 'c07_07'),
                       labels = c('Visito casa\nde vecino',
                               'Amigos visitaron\nsu casa',
                               'Asistio a reunion sobre temas\nde interes publico/comunitario',
                               'Converso con persona\nen problemas o deprimida')))

g9.7 <- datos.9.7 %>% 
  ggplot(aes(y = prop, x = ola, color = name, group = name,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() +   
  geom_line(size = 1) +
  geom_point(size = 1.8) +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0,1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = 0, end = .77, direction = -1, option = 'viridis') +
  ggrepel::geom_text_repel(size= 2.75) +
  theme(legend.position = 'top',
        legend.title = element_blank())
g9.7
```
```{r dist-pros2, fig.align='center', fig.cap='Frecuencia de comportamientos pro-sociales, según cumplimiento de distanciamiento social (2021). Porcentaje de respuestas de "Lo hizo mas de dos veces".'}
datos.9.8 <- elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & ola == 5 & !c48 %in% c(-888,-999)) %>%  
  select(c07_01, c07_03, c07_02, c07_07,c48, ola, ponderador02, segmento_disenno, estrato_disenno) %>% 
  mutate(dis_soc = factor(car::recode(c48, "c(1,2) = 1; c(3) = 2; c(4,5) = 3"),
                               levels = c(1,2,3), labels= c("Nunca o\ncasi nunca", "A veces",
                                         "Frecuentemente o\nmuy frecuentemente"))) %>%
  pivot_longer(cols = c(c07_01, c07_03, c07_02, c07_07)) %>% 
  filter(!value %in% c(-888, -999)) %>% 
  prop(value == 3, by = c(name, dis_soc), na.rm = TRUE) %>% 
  mutate(name = factor(name,
                       levels = c('c07_01', 'c07_03', 'c07_02', 'c07_07'),
                       labels = c('Visito casa\nde vecino',
                               'Amigos visitaron\nsu casa',
                               'Asistio a reunion\nsobre temas de\ninteres publico/comunitario',
                               'Converso con persona en\nproblemas o deprimida')))

g9.8 <- datos.9.8 %>% 
  ggplot(aes(y = prop, x = name, fill = dis_soc, 
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, .8)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .85, direction = -1, option = 'viridis') +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75)
g9.8
```

### Percepción de conflictividad y criminalidad barrial
```{r dist-barrio, fig.align='center', fig.cap='Percepción de conflictividad y criminalidad barrial, según cumplimiento de distanciamiento social (2021). Porcentaje de personas que responden "Muchas veces o siempre".'}
datos.9.9 <- elsoc_long_2016_2021 %>%
  filter(tipo_atricion == 1 & muestra == 1 & ola == 5 & 
           !t11_01 %in% c(-888, -999) & !t11_02 %in% c(-888, -999) & !t11_03 %in% c(-888, -999) &
           !t11_04 %in% c(-888, -999) &
           !t09_01 %in% c(-888, -999) & !t09_02 %in% c(-888, -999) & !t09_03 %in% c(-888, -999) & 
           !c48 %in% c(-888, -999)) %>%
  mutate(barrio_confli = (t11_01 + t11_03 + t11_03 + t11_04)/4,
         barrio_crim = (t09_01 + t09_02 + t09_03)/3) %>%
  mutate(barrio_confli_rec = factor(cut(barrio_confli, breaks = c(0,1,2.75,5)),
                                    labels = c("Nunca","Pocas o algunas veces","Muchas veces o siempre")),
         barrio_crim_rec = factor(cut(barrio_crim, breaks = c(0,1,2.67,5)),
                                  labels = c("Nunca","Pocas o algunas veces","Muchas veces o siempre")),
         dis_soc = factor(car::recode(c48, "c(1,2) = 1; c(3) = 2; c(4,5) = 3"),
                               levels = c(1,2,3), labels= c("Nunca o\ncasi nunca", "A veces",
                                         "Frecuentemente o\nmuy frecuentemente"))) %>%
  select(barrio_confli_rec,barrio_crim_rec, estrato_disenno, segmento_disenno, ponderador02, dis_soc) %>%
  pivot_longer(cols = c(barrio_confli_rec, barrio_crim_rec)) %>% 
  prop(value == 'Muchas veces o siempre', by = c(name, dis_soc), na.rm = TRUE) %>% 
  mutate(name = factor(name, levels = c('barrio_confli_rec', 'barrio_crim_rec'), 
                       labels = c('Conflictividad barrial', 'Criminalidad barrial'))) %>% 
  sjlabelled::as_label(dis_soc)

g9.9 <- datos.9.9 %>% 
  ggplot(aes(y = prop, x = name, fill = dis_soc, 
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, .8)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .85, direction = -1, option = 'viridis') +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75)
g9.9
```
