# Estatus subjetivo y Percepción de Mérito
```{r disenno-15, include=FALSE}
knitr::opts_chunk$set(cache=FALSE, 
                      warning = FALSE, 
                      message = FALSE) 
Sys.setlocale("LC_ALL","ES_ES.UTF-8")

#devtools::install_github('edgardo-cerda/elsoc', force = TRUE)
library(elsoc)
library(tidyverse)
library(sjlabelled)
library(ggrepel)

load(file.path('1_input', 'ELSOC_Long_2016_2021_v1.00_R.RData'))

library(survey)
load("1_input/datos_elsoc.RData")
elsoc_diseno <- svydesign(ids = ~segmento, strata = ~estrato, weights = ~ponderador02, 
                          nest = TRUE, data = elsoc_panel_m1)
```

## Estatus subjetivo

```{r recode-ess-merit, include=FALSE}
elsoc_panel_m1 <- elsoc_panel_m1 %>% 
  mutate(mov_interg = d01_03 - d01_01, #estatus futuro hijos menos estatus propio
         mov_relativa = d01_01 - d01_02) #estatus propio vs estatus padres

sjmisc::frq(elsoc_panel_m1$mov_interg)
elsoc_panel_m1 <- elsoc_panel_m1 %>% 
  mutate(mov_interg_rec = factor(car::recode(mov_interg, "-8:-1=1;0=2;1:10=3"),
                           labels = c("Movilidad social descendente", "Inmovilidad social",
                                      "Movilidad social ascendente")),
         mov_interg_rec2 = factor(cut(mov_interg, breaks = c(-8,-1,1,10))))

sjmisc::frq(elsoc_panel_m1$mov_interg_rec)
sjmisc::frq(elsoc_panel_m1$mov_interg_rec2)

elsoc_panel_m1 <- elsoc_panel_m1 %>%
  mutate(merit_esfu = factor(car::recode(c18_09, "c(1,2)=1;c(3)=2;c(4,5)=3"),
                           labels = c('En desacuendo o totalmente en desacuerdo', 
                                      'Ni de acuerdo ni en desacuerdo', 'De acuerdo o totalmente de acuerdo')),
         merit_inte = factor(car::recode(c18_10, "c(1,2)=1;c(3)=2;c(4,5)=3"),
                               labels = c('En desacuendo o totalmente en desacuerdo', 
                                          'Ni de acuerdo ni en desacuerdo', 'De acuerdo o totalmente de acuerdo')),
         merit_educ = factor(car::recode(d05_02, "c(1,2)=1;c(3)=2;c(4,5)=3"),
                            labels = c('En desacuendo o totalmente en desacuerdo', 
                                       'Ni de acuerdo ni en desacuerdo', 'De acuerdo o totalmente de acuerdo')),
         merit_trab = factor(car::recode(d05_04, "c(1,2)=1;c(3)=2;c(4,5)=3"),
                          labels = c('En desacuendo o totalmente en desacuerdo', 
                                     'Ni de acuerdo ni en desacuerdo', 'De acuerdo o totalmente de acuerdo')))

elsoc_diseno <- svydesign(ids = ~segmento, strata = ~estrato, weights = ~ponderador02, 
                             nest = TRUE, data = elsoc_panel_m1)

```

<!-- ### 11.1 En nuestra sociedad, hay grupos que tienden a ubicarse en los niveles más altos y grupos que tienden a ubicarse en los niveles más bajos de la sociedad ¿Dónde se ubicaría usted?, según ola de estudio. -->
```{r essind-ola, fig.align='center',fig.cap='En nuestra sociedad, hay grupos que tienden a ubicarse en los niveles más altos y grupos que tienden a ubicarse en los niveles más bajos de la sociedad ¿Dónde se ubicaría usted?, según ola de estudio.'}
datos11.1 <- elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & ola %in% c(1,2,3,4,5) & !d01_01 %in% c(-888, -999)) %>% 
  mutate(clase_sub = factor(car::recode(d01_01, "c(0,1,2,3)=1; c(4, 5)=2; c(6,7,8,9,10)=3;else=NA"), 
                            levels = c(1,2,3), labels = c("Baja y media baja", "Media", "Alta y media alta"))) %>% 
  sjlabelled::as_label(ola) %>% 
  prop(x = clase_sub, by = ola, na.rm = T)

g11.1 <- datos11.1 %>% 
  ggplot(aes(y = prop, x = ola, fill = clase_sub, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .11, end = .88, direction = 1, option = 'viridis') +
  geom_text(position = position_stack(vjust = .5),
            size= 2.75, color = rep.int(c('white', 'black', 'black'), 5)) + 
  theme(legend.position = 'top',
        legend.title = element_blank())
g11.1
```


<!-- ### 11.2 Cambios de Clase social subjetiva entre 2016, 2019 y 2021 -->
```{r ess-wave, fig.align='center',fig.cap='Cambios de Clase social subjetiva entre 2016, 2019 y 2021'}

datos.g11.2 <- data.frame((svytable(~clase.sub + ola + idencuesta, elsoc_diseno, round = F))) %>% 
  group_by(ola) %>% mutate(porcentaje=Freq/sum(Freq)) %>%
  filter(Freq>0, ola == '2016'| ola == '2019' | ola == '2021') %>%
  drop_na()

etiquetas.g11.2 <- data.frame((svytable(~clase.sub + ola, elsoc_diseno, round = F))) %>% 
  group_by(ola) %>% mutate(porcentaje=Freq/sum(Freq)) %>% mutate(idencuesta = 1) %>% 
  filter(Freq>0, ola == '2016'| ola == '2019' | ola == '2021') %>% 
  drop_na()

g11.2 <- 
  ggplot(datos.g11.2, aes(x = ola, fill = clase.sub, stratum = clase.sub, 
                          alluvium = idencuesta, y = porcentaje)) +
  ggalluvial::geom_flow(alpha = .66) + 
  ggalluvial::geom_stratum(linetype = 0) +
  scale_y_continuous(labels = scales::percent) + 
  ylab(label = NULL) +
  xlab(label = NULL) + 
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  scale_fill_viridis_d(begin = .11, end = .88, direction = 1, option = 'viridis') +
  geom_text(data = etiquetas.g11.2, 
            aes(label = ifelse(porcentaje > 0.03 , scales::percent(porcentaje, accuracy = .1),"")),
            position = position_stack(vjust = .5),
            show.legend = FALSE,
            size = 2.75,
            color = rep.int(c('white', 'white', 'black'),3))

g11.2
```
```{r}

```

<!-- ### 11.3 Clase social subjetiva, según quintiles de ingreso (2021) -->
```{r ess-quintil, fig.align='center',fig.cap='Clase social subjetiva, según quintiles de ingreso (2021)'}

datos.11.3 <- elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & ola %in% c(5) & !t01 %in% c(-888, -999)) %>% 
  mutate(clase_sub = factor(car::recode(d01_01, "c(0,1,2,3)=1; c(4,5)=2; c(6,7,8,9,10)=3;else=NA"), 
                            levels = c(1,2,3), 
                            labels = c("Baja y media baja", "Media", "Alta y media alta")),
         m30 = as.numeric(car::recode(m30,"1=110000;2=251000;3=305000;4=355000;5=400000;
                                           6=445000;7=490000;8=535000;9=585000;10=640000;11=700000;12=765000;
                                           13=845000;14=935000;15=1040000;16=1180000;17=1375000;18=1670000;
                                           19=2275000;20=2700000;NA=NA")),
         m29_imp = ifelse(!is.na(m29),m29, m30),
         n_hogar = case_when(ola == 1 ~ nhogar1, ola == 2 ~ m46_nhogar,
                             ola == 3 ~ m54, ola == 4 ~ m54, ola == 5 ~ m54)) %>%
  mutate(ing_pc = (m29_imp/n_hogar)) %>%
  sjlabelled::as_label(ola) %>% 
  group_by(ola) %>% 
  mutate(quintil = factor(ntile(-desc(ing_pc), 5), levels = c(1,2,3,4,5),
         labels = c('Q1', 'Q2', 'Q3', 'Q4', 'Q5'))) %>% 
  prop(x = clase_sub, by = c(ola, quintil), na.rm = TRUE)

g11.3 <- 
  datos.11.3 %>% 
  ggplot(aes(y = prop, x = quintil, fill = clase_sub, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .99, direction = -1, option = 'viridis') +
  geom_text(position = position_stack(vjust = .5),
            size= 2.75, color = rep.int(c( 'black','black','white'), 5)) + 
  theme(legend.position = 'top',
        legend.title = element_blank())
g11.3
```

<!-- ### 11.4  Si usted tiene actualmente hijos o si los tuviera en el futuro, ¿dónde cree usted que se ubicarían ellos?, según Clase social subjetiva (2021) -->
```{r esshijos-ess, fig.align='center',fig.cap='Si usted tiene actualmente hijos o si los tuviera en el futuro, ¿dónde cree usted que se ubicarían ellos?, según Clase social subjetiva (2021)'}
datos11.4 <- elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & ola == 5 & 
         !d01_01 %in% c(-888, -999) & !d01_03 %in% c(-888, -999)) %>% 
  mutate(clase_sub = factor(car::recode(d01_01, "c(0,1,2,3)=1; c(4,5)=2; c(6,7,8,9,10)=3;else=NA"), 
                            levels = c(1,2,3), 
                            labels = c("Baja y media baja", "Media", "Alta y media alta")),
         clase_sub_hijo = factor(car::recode(d01_03, "c(0,1,2,3)=1; c(4,5)=2; c(6,7,8,9,10)=3;else=NA"),
                                 levels = c(1,2,3), 
                                 labels = c("Baja y media baja", "Media", "Alta y media alta"))) %>% 
  sjlabelled::as_label(ola) %>% 
  prop(x = clase_sub_hijo, by = c(ola, clase_sub), na.rm = T)

g11.4 <- datos11.4 %>% 
  ggplot(aes(y = prop, x = clase_sub, fill = clase_sub_hijo, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  ylab(label = NULL) +
  xlab(label = 'Clase social subjetiva propia') +
  scale_fill_viridis_d(begin = .11, end = .88, direction = 1, option = 'viridis') +
  geom_text(position = position_stack(vjust = .5),
            size= 2.75, color = rep.int(c('white', 'white', 'black'), 3)) + 
  theme(legend.position = 'top',
        legend.title = element_blank())
g11.4
```
## Movilidad social

<!-- ### 11.5  Perspectiva de movilidad social, según ola.  -->
```{r mov-soc-rec, fig.align='center',fig.cap='Perspectiva de movilidad social, según ola. '}
datos.11.5 <- elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & ola == c(1,2,3,4,5) & 
         !d01_01 %in% c(-888, -999) & !d01_03 %in% c(-888, -999)) %>% 
  mutate(mov_interg = d01_03 - d01_01) %>% 
  mutate(mov_interg_rec = factor(car::recode(mov_interg, "-8:-1=1;0=2;1:10=3;else=NA"), 
                            levels = c(1,2,3), 
                            labels = c("Perpectiva de\nmovilidad descendente", "Perspectiva de\ninmovilidad social",
                                       "Perspectiva de\nmovilidad ascendente"))) %>% 
  sjlabelled::as_label(ola) %>% 
  prop(x = mov_interg_rec, by = ola, na.rm = T)

g11.5 <- 
  datos.11.5 %>% 
  ggplot(aes(y = prop, x = ola, fill = mov_interg_rec, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .11, end = .99, direction = -1, option = 'viridis') +
  geom_text(position = position_stack(vjust = .5),
            size= 2.75, color = rep.int(c('black', 'white', 'white'), 5)) + 
  theme(legend.position = 'top',
        legend.title = element_blank())

g11.5
```

```{r}
datos.11.6e <- elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & ola == c(1,2,3,4,5) & !ola %in% c(-888, -999) &
         !d01_01 %in% c(-888, -999) & !d01_02 %in% c(-888,-999) & !d01_03 %in% c(-888, -999)) %>%
  sjlabelled::as_label(ola) %>% 
  mutate(mov_interg = d01_03 - d01_01,
         mov_relativa = d01_01 - d01_02) %>% 
  group_by(ola) %>% 
  summarise(m_interg = weighted.mean(mov_interg, ponderador02 ,na.rm = T),
            m_relativa = weighted.mean(mov_relativa, ponderador02 ,na.rm = T),
            m_estatus = weighted.mean(d01_01, ponderador02 ,na.rm = T),
            conteo = n()) %>% 
  mutate(var_interg = 'Perspectiva de\nmovilidad social',
         var_relativa = 'Movilidad social\nrelativa',
         var_estatus = 'Estatus social\nactual') %>% 
  pivot_longer(cols = starts_with('var_'))  %>%
  mutate(m_mov_social = case_when(
    value == 'Perspectiva de\nmovilidad social' ~ m_interg,
    value == 'Movilidad social\nrelativa' ~ m_relativa,
    value == 'Estatus social\nactual' ~ m_estatus)) 

datos.11.6e$m_mov_social <- round(datos.11.6e$m_mov_social, digits = 2) 

g11.6e <- datos.11.6e %>% 
  ggplot(aes(y = m_mov_social, x = ola, group = value, color = value,
             label = m_mov_social)) +
  theme_bw() +
  geom_line(size = 1) +
  geom_point(size = 1.8) +
  scale_y_continuous(limits = c(0,6)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .11, end = .55, direction = 1, option = 'viridis') +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.8,  size= 3.5)
g11.6e
```

<!-- ### 11.6  Estatus subjetivo y tipo de movilidad social, nivel promedio según ola.  -->
```{r mov-soc, fig.align='center',fig.cap='Estatus subjetivo y tipo de movilidad social, nivel promedio según ola'}

datos11.6 <- elsoc_panel_m1 %>%
  group_by(ola) %>% 
  summarise(m_interg = weighted.mean(mov_interg, ponderador02 ,na.rm = T),
            m_relativa = weighted.mean(mov_relativa, ponderador02 ,na.rm = T),
            m_estatus = weighted.mean(d01_01, ponderador02 ,na.rm = T),
            conteo = n()) %>% 
  mutate(var_interg = 'Perspectiva de\nmovilidad social',
         var_relativa = 'Movilidad social\nrelativa',
         var_estatus = 'Estatus social\nactual') %>% 
  pivot_longer(cols = starts_with('var_'))  %>%
  mutate(m_mov_social = case_when(
    value == 'Perspectiva de\nmovilidad social' ~ m_interg,
    value == 'Movilidad social\nrelativa' ~ m_relativa,
    value == 'Estatus social\nactual' ~ m_estatus))

datos11.6$m_mov_social <- round(datos11.6$m_mov_social, digits = 2) 

g11.6 <- 
  ggplot(datos11.6, aes(y = m_mov_social, x = ola, group = value, color = value,
                              label = m_mov_social)) +
  theme_bw() +
  geom_line(size = 1) +
  geom_point(size = 1.8) +
  scale_y_continuous(limits = c(0,6)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .11, end = .55, direction = 1, option = 'viridis') +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.8,  size= 3.5)
g11.6
```
## Percepción de meritocracia

<!-- ### 11.7  Percepción de importancia y recompensas del mérito, según ola de estudio. Porcentaje de Respuestas "De acuerdo" y ”Totalmente de acuerdo".  -->
```{r merit-wave, fig.align='center',fig.cap='Percepción de importancia y recompensas del mérito, según ola de estudio. Porcentaje de Respuestas "De acuerdo" y ”Totalmente de acuerdo".'}

datos.esfu <- data.frame((svytable(~merit_esfu + ola, elsoc_diseno, round = F))) %>%
  group_by(ola) %>% mutate(p_esfu=Freq/sum(Freq))
datos.esfu$ola <- NULL

datos.inte <- data.frame((svytable(~merit_inte + ola, elsoc_diseno, round = F))) %>% 
  group_by(ola) %>% mutate(p_inte=Freq/sum(Freq))
datos.inte$ola <- NULL

datos.educ <- data.frame((svytable(~merit_educ + ola, elsoc_diseno, round = F))) %>% 
  group_by(ola) %>% mutate(p_educ=Freq/sum(Freq))
datos.educ$ola <- NULL

datos.trab <- data.frame((svytable(~merit_trab + ola, elsoc_diseno, round = F))) %>% 
  group_by(ola) %>% mutate(p_trab=Freq/sum(Freq))

datos.11.7 <- cbind(datos.esfu, datos.inte, datos.educ, datos.trab)

#trasponer según variable
datos.11.7 <- datos.11.7 %>%
  pivot_longer(cols = starts_with('merit_')) %>%
  mutate(porcentaje = case_when(
    name == 'merit_esfu' ~ p_esfu,
    name == 'merit_inte' ~ p_inte,
    name == 'merit_educ' ~ p_educ,
    name == 'merit_trab' ~ p_trab)) %>% 
  filter(value == 'De acuerdo o totalmente de acuerdo') %>% 
  mutate(variable = factor(name, labels = 
                             c('Personas son\nrecompensadas\npor su esfuerzo',
                               'Personas son\nrecompensadas\npor su inteligencia',
                               'Educación es\nimportante para\nsurgir en la vida',
                               'Trabajo duro\nes importante para\nsurgir en la vida')))

g11.7 <- datos.11.7 %>% 
  ggplot(aes(y = porcentaje, x = ola, color = variable, group = variable,
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) +
  theme_bw() +   
  geom_line(size = 1) +
  geom_point(size = 1.8) +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0,1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = 0, end = .66, direction = 1, option = 'viridis') +
  geom_text(vjust = -0.8,
            size= 2.75) +
  theme(legend.position = 'top',
        legend.title = element_blank())
g11.7
```

