---
output:
  pdf_document: default
  html_document: default
---
# Género


## Sexismo hostil y benevolente


```{r objetos, include=FALSE}
#Escala sexismo
elsoc_panel$sexismo <- c( as.numeric(elsoc_panel$g01_01) + as.numeric(elsoc_panel$g01_02) +
                          as.numeric(elsoc_panel$g01_03) + as.numeric(elsoc_panel$g01_04)) /4

elsoc_panel$sexismo_benevolo <- c( as.numeric(elsoc_panel$g01_01) + as.numeric(elsoc_panel$g01_02))/2
elsoc_panel$sexismo_benevolo <- factor(car::recode(as.numeric(elsoc_panel$sexismo_benevolo), 'c(1,1.5,2)=1;c(2.5, 3, 3.5)=2;c(4,4.5, 5)= 3; else=NA', 
                                             as.factor = TRUE), levels = c(1,2,3),
                                labels = c('Debil', 'Medio', 'Fuerte'))
elsoc_panel$sexismo_benevolo <- na.replace(elsoc_panel$sexismo_benevolo, "NS/NR") #recode NA en categoría "NS/NR"
elsoc_panel$sexismo_hostil <- c(as.numeric(elsoc_panel$g01_03) + as.numeric(elsoc_panel$g01_04))/2
elsoc_panel$sexismo_hostil <- factor(car::recode(as.numeric(elsoc_panel$sexismo_hostil), 'c(1,1.5,2)=1;c(2.5, 3, 3.5)=2;c(4,4.5, 5)= 3; else=NA', 
                                             as.factor = TRUE), levels = c(1,2,3),
                                labels = c('Debil', 'Medio', 'Fuerte'))
elsoc_panel$sexismo_hostil <- na.replace(elsoc_panel$sexismo_hostil, "NS/NR") #recode NA en categoría "NS/NR"

elsoc_panel$g01_01_rec <- factor(car::recode(as.numeric(elsoc_panel$g01_01), 'c(1,2)=1;c(3)=2;c(4,5)= 3; else=NA', 
                                             as.factor = TRUE), levels = c(1,2,3),
                                labels = c('Desacuerdo', 'Ni acuerdo ni desacuerdo', 'De Acuerdo'))
elsoc_panel$g01_02_rec <- factor(car::recode(as.numeric(elsoc_panel$g01_02), 'c(1,2)=1;c(3)=2;c(4,5)= 3; else=NA', as.factor = TRUE),
                                levels = c(1,2,3),
                                labels = c('Desacuerdo', 'Ni acuerdo ni desacuerdo', 'De Acuerdo'))

elsoc_panel$g01_03_rec <- factor(car::recode(as.numeric(elsoc_panel$g01_03), 'c(1,2)=1;c(3)=2;c(4,5)= 3; else=NA', as.factor = TRUE),
                                levels = c(1,2,3),
                                labels = c('Desacuerdo', 'Ni acuerdo ni desacuerdo', 'De Acuerdo'))

elsoc_panel$g01_04_rec <- factor(car::recode(as.numeric(elsoc_panel$g01_04), 'c(1,2)=1;c(3)=2;c(4,5)= 3; else=NA', as.factor = TRUE),
                                levels = c(1,2,3),
                                labels = c('Desacuerdo', 'Ni acuerdo ni desacuerdo', 'De Acuerdo'))



elsoc_panel$c19_01_rec <- factor(car::recode(as.numeric(elsoc_panel$c19_01), 'c(1,2)=1;c(3)=2;c(4,5)= 3; else="NS/NR"', 
                                             as.factor = TRUE), levels = c(1,2,3),
                                labels = c('Desacuerdo', 'Ni acuerdo ni desacuerdo', 'De Acuerdo'))


elsoc_panel$c19_02_rec <- factor(car::recode(as.numeric(elsoc_panel$c19_02), 'c(1,2)=1;c(3)=2;c(4,5)= 3; else="NS/NR"', as.factor = TRUE),
                                levels = c(1,2,3),
                                labels = c('Desacuerdo', 'Ni acuerdo ni desacuerdo', 'De Acuerdo'))

elsoc_panel$c19_03_rec <- factor(car::recode(as.numeric(elsoc_panel$c19_03), 'c(1,2)=1;c(3)=2;c(4,5)= 3; else="NS/NR"', as.factor = TRUE),
                                levels = c(1,2,3),
                                labels = c('Desacuerdo', 'Ni acuerdo ni desacuerdo', 'De Acuerdo'))

elsoc_panel$c19_04_rec <- factor(car::recode(as.numeric(elsoc_panel$c19_04), 'c(1,2)=1;c(3)=2;c(4,5)= 3; else="NS/NR"', as.factor = TRUE),
                                levels = c(1,2,3),
                                labels = c('Desacuerdo', 'Ni acuerdo ni desacuerdo', 'De Acuerdo'))


elsoc_diseno_2 <- svydesign(ids = ~segmento,
                          strata = ~estrato, 
                          weights = ~ponderador02,
                          nest = TRUE,
                          data = elsoc_panel)

```

```{r sexismo-ben, fig.align='center', fig.cap='Cambio en Sexismo benévolo, según ola y sexo .'}

#1
datos.grafico <- data.frame((svytable(~sexismo_benevolo + ola + idencuesta + 
                                        m0_sexo, elsoc_diseno_2, round = F))) %>% 
  dplyr::filter(Freq>0)  %>% 
  group_by(ola,m0_sexo) %>% 
  mutate(porcentaje=Freq/sum(Freq)) %>% na.omit()

#1.1
subset.grafico <- droplevels(subset(datos.grafico, datos.grafico$ola == '2019' | datos.grafico$ola == '2021'))

#2
etiquetas.grafico <- data.frame((svytable(~sexismo_benevolo + ola + m0_sexo, 
                                          elsoc_diseno_2, round = F))) %>% 
  group_by(ola, m0_sexo) %>% 
  mutate(porcentaje=Freq/sum(Freq)) %>% 
  na.omit() %>% 
  mutate(idencuesta = 1)

#Paso 2.2: crear un subset sólo para los años
etiquetas.grafico <- droplevels(subset(etiquetas.grafico, 
                     etiquetas.grafico$ola == '2019' | etiquetas.grafico$ola == '2021'))

gr.16.1 <- ggplot(subset.grafico, aes(x = ola, fill = sexismo_benevolo, stratum = sexismo_benevolo, 
                              alluvium = idencuesta, y = porcentaje)) +
  theme_bw() +
  ggalluvial::geom_flow(alpha = .66) + 
  ggalluvial::geom_stratum(linetype = 0) +
  scale_y_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  scale_fill_viridis_d(begin = 0, end = .9, direction = -1, option = 'viridis') +
  facet_wrap(.~m0_sexo)+
  geom_text(data = etiquetas.grafico, 
            aes(label = ifelse(porcentaje > 0.05 , scales::percent(porcentaje, accuracy = .1),"")),
            position = position_stack(vjust = .5),
            show.legend = FALSE,
            size= 2.75, color = rep.int(c('black','white', 'white'), 4))

gr.16.1
```

```{r sexismo-host, fig.align='center', fig.cap='Sexismo hostil, según ola y sexo .'}

#1
datos.grafico <- data.frame((svytable(~sexismo_hostil + ola + idencuesta + 
                                        m0_sexo, elsoc_diseno_2, round = F))) %>% 
  dplyr::filter(Freq>0)  %>% 
  group_by(ola,m0_sexo) %>% 
  mutate(porcentaje=Freq/sum(Freq)) %>% na.omit()

#1.1
subset.grafico <- droplevels(subset(datos.grafico, datos.grafico$ola == '2019' | datos.grafico$ola == '2021'))

#2
etiquetas.grafico <- data.frame((svytable(~sexismo_hostil + ola + m0_sexo, 
                                          elsoc_diseno_2, round = F))) %>% 
  group_by(ola, m0_sexo) %>% 
  mutate(porcentaje=Freq/sum(Freq)) %>% 
  na.omit() %>% 
  mutate(idencuesta = 1)

#Paso 2.2: crear un subset sólo para los años
etiquetas.grafico <- droplevels(subset(etiquetas.grafico, 
                     etiquetas.grafico$ola == '2019' | etiquetas.grafico$ola == '2021'))

gr.16.2 <- ggplot(subset.grafico, aes(x = ola, fill = sexismo_hostil, stratum = sexismo_hostil, 
                              alluvium = idencuesta, y = porcentaje)) +
  theme_bw() +
  ggalluvial::geom_flow(alpha = .66) + 
  ggalluvial::geom_stratum(linetype = 0) +
  scale_y_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  scale_fill_viridis_d(begin = 0, end = .9, direction = -1, option = 'viridis') +
  facet_wrap(.~m0_sexo)+
  geom_text(data = etiquetas.grafico, 
            aes(label = ifelse(porcentaje > 0.05 , scales::percent(porcentaje, accuracy = .1),"")),
            position = position_stack(vjust = .5),
            show.legend = FALSE,
            size= 2.75, color = rep.int(c('black','white', 'white'), 4))

gr.16.2
```

<!-- ### 12.1 Sexismo benévolo y hostil, según sexo (2019). Porcentaje que responde "De acuerdo" o "Totalmente de acuerdo". -->
```{r sexismo-sexo, fig.align='center', fig.cap='Sexismo benévolo y hostil, según sexo (2021). Porcentaje que responde "De acuerdo" o "Totalmente de acuerdo".'}
datos.01 <- data.frame((svytable(~g01_01_rec + m0_sexo + ola, elsoc_diseno_2, round = F))) %>% group_by(ola, m0_sexo) %>% mutate(p_01=Freq/sum(Freq))
datos.01$ola <- NULL
datos.01$m0_sexo <- NULL
datos.02 <- data.frame((svytable(~g01_02_rec+m0_sexo +  ola, elsoc_diseno_2, round = F))) %>% group_by(ola, m0_sexo) %>% mutate(p_02=Freq/sum(Freq))
datos.02$ola <- NULL
datos.02$m0_sexo <- NULL
datos.03 <- data.frame((svytable(~g01_03_rec+m0_sexo +  ola, elsoc_diseno_2, round = F))) %>% group_by(ola, m0_sexo) %>% mutate(p_03=Freq/sum(Freq))
datos.03$ola <- NULL
datos.03$m0_sexo <- NULL
datos.04 <- data.frame((svytable(~g01_04_rec+m0_sexo +  ola, elsoc_diseno_2, round = F))) %>% group_by(ola, m0_sexo) %>% mutate(p_04=Freq/sum(Freq))

datos.grafico1<- cbind(datos.01, datos.02, datos.03, datos.04)

subset.grafico <- droplevels(subset(datos.grafico1, datos.grafico1$ola == '2021' & 
                                      g01_01_rec == 'De Acuerdo' & 
                                      g01_02_rec == 'De Acuerdo' &
                                      g01_03_rec == 'De Acuerdo' & 
                                      g01_04_rec == 'De Acuerdo'))

#trasponer según variable
datos.grafico <- subset.grafico %>% 
  pivot_longer(cols = starts_with('g01'))  %>%
  mutate(variable = factor(name, labels = c('Mujeres son más refinadas y con mejor gusto que los hombres',
                     'Mujeres debieran ser queridas y protegidas por los hombres',
                     'Mujeres consiguen privilegios en nombre de igualdad',
                     'Cuando mujeres son derrotadas limpiamente, se quejan de discriminación'))) %>% 
  drop_na()

datos.grafico$porcentaje <- with(datos.grafico, case_when(
  variable == 'Mujeres son más refinadas y con mejor gusto que los hombres' ~ p_01,
  variable == 'Mujeres debieran ser queridas y protegidas por los hombres' ~ p_02,
  variable == 'Mujeres consiguen privilegios en nombre de igualdad' ~ p_03,
  variable == 'Cuando mujeres son derrotadas limpiamente, se quejan de discriminación' ~ p_04))

#graficamos

gr.16.1 <-datos.grafico %>% 
  ggplot(aes(y = porcentaje, x = variable, fill = m0_sexo, 
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) +
  theme_bw() + 
  geom_col(position = "dodge2") +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1, option = 'viridis') + 
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75)  +
  theme(legend.position = 'top',
        legend.title = element_blank())

gr.16.1

```


<!-- ### 12.4 Sexismo benévolo y hostil, según nivel educacional (2019). Porcentaje que responde "De acuerdo" o "Totalmente de acuerdo". -->

```{r sexismo-educ, fig.align='center',fig.cap='Sexismo benévolo y hostil, según nivel educacional (2021). Porcentaje que responde "De acuerdo" o "Totalmente de acuerdo".'}
datos.01 <- data.frame((svytable(~g01_01_rec + educ + ola, elsoc_diseno_2, round = F))) %>% group_by(ola, educ) %>% mutate(p_01=Freq/sum(Freq))
datos.01$ola <- NULL
datos.01$educ <- NULL
datos.02 <- data.frame((svytable(~g01_02_rec+educ +  ola, elsoc_diseno_2, round = F))) %>% group_by(ola, educ) %>% mutate(p_02=Freq/sum(Freq))
datos.02$ola <- NULL
datos.02$educ <- NULL
datos.03 <- data.frame((svytable(~g01_03_rec+educ +  ola, elsoc_diseno_2, round = F))) %>% group_by(ola, educ) %>% mutate(p_03=Freq/sum(Freq))
datos.03$ola <- NULL
datos.03$educ <- NULL
datos.04 <- data.frame((svytable(~g01_04_rec+educ +  ola, elsoc_diseno_2, round = F))) %>% group_by(ola, educ) %>% mutate(p_04=Freq/sum(Freq))

datos.grafico1<- cbind(datos.01, datos.02, datos.03, datos.04)

subset.grafico <- droplevels(subset(datos.grafico1, datos.grafico1$ola == '2021' & 
                                      g01_01_rec == 'De Acuerdo' & 
                                      g01_02_rec == 'De Acuerdo' &
                                      g01_03_rec == 'De Acuerdo' & 
                                      g01_04_rec == 'De Acuerdo'))

#trasponer según variable
datos.grafico <- subset.grafico %>% 
  pivot_longer(cols = starts_with('g01'))  %>%
  mutate(variable = factor(name, labels = c('Mujeres son más refinadas y con mejor gusto que los hombres',
                     'Mujeres debieran ser queridas y protegidas por los hombres',
                     'Mujeres consiguen privilegios en nombre de igualdad',
                     'Cuando mujeres son derrotadas limpiamente, se quejan de discriminación'))) %>% 
  drop_na()

datos.grafico$porcentaje <- with(datos.grafico, case_when(
  variable == 'Mujeres son más refinadas y con mejor gusto que los hombres' ~ p_01,
  variable == 'Mujeres debieran ser queridas y protegidas por los hombres' ~ p_02,
  variable == 'Mujeres consiguen privilegios en nombre de igualdad' ~ p_03,
  variable == 'Cuando mujeres son derrotadas limpiamente, se quejan de discriminación' ~ p_04))

#graficamos

gr.16.2 <-datos.grafico %>% 
  ggplot(aes(y = porcentaje, x = variable, fill = educ, 
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) +
  theme_bw() + 
  geom_col(position = "dodge2") +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1, option = 'viridis') + 
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75)  +
  theme(legend.position = 'top',
        legend.title = element_blank())

gr.16.2
```

## Roles de Género
```{r c19_01, fig.align='center', fig.cap='Sexismo hostil, según ola y sexo .'}

#1
datos.grafico <- data.frame((svytable(~c19_01_rec + ola + idencuesta + 
                                        m0_sexo, elsoc_diseno_2, round = F))) %>% 
  dplyr::filter(Freq>0)  %>% 
  group_by(ola, m0_sexo) %>% 
  mutate(porcentaje=Freq/sum(Freq)) %>% na.omit()

#1.1
subset.grafico <- droplevels(subset(datos.grafico, datos.grafico$ola == '2016' |  datos.grafico$ola == '2018' | datos.grafico$ola == '2021'))

#2
etiquetas.grafico <- data.frame((svytable(~c19_01_rec + ola + m0_sexo, 
                                          elsoc_diseno_2, round = F))) %>% 
  group_by(ola, m0_sexo) %>% 
  mutate(porcentaje=Freq/sum(Freq)) %>% 
  na.omit() %>% 
  mutate(idencuesta = 1)

#Paso 2.2: crear un subset sólo para los años
etiquetas.grafico <- droplevels(subset(etiquetas.grafico, etiquetas.grafico$ola == '2016' | etiquetas.grafico$ola == '2018' | etiquetas.grafico$ola == '2021'))

gr.16.3 <- ggplot(subset.grafico, aes(x = ola, fill = c19_01_rec, stratum = c19_01_rec, 
                              alluvium = idencuesta, y = porcentaje)) +
  theme_bw() +
  ggalluvial::geom_flow(alpha = .66) + 
  ggalluvial::geom_stratum(linetype = 0) +
  scale_y_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  scale_fill_viridis_d(begin = 0, end = .9, direction = -1, option = 'viridis') +
  facet_wrap(.~m0_sexo)+
  geom_text(data = etiquetas.grafico, 
            aes(label = ifelse(porcentaje > 0.05 , scales::percent(porcentaje, accuracy = .1),"")),
            position = position_stack(vjust = .5),
            show.legend = FALSE,
            size= 2.75, color = rep.int(c('black', 'white', 'white'), 6))

gr.16.3
```


```{r c19_02, fig.align='center', fig.cap='Sexismo hostil, según ola y sexo .'}

#1
datos.grafico <- data.frame((svytable(~c19_02_rec + ola + idencuesta + 
                                        m0_sexo, elsoc_diseno_2, round = F))) %>% 
  dplyr::filter(Freq>0)  %>% 
  group_by(ola, m0_sexo) %>% 
  mutate(porcentaje=Freq/sum(Freq)) %>% na.omit()

#1.1
subset.grafico <- droplevels(subset(datos.grafico, datos.grafico$ola == '2016' |  datos.grafico$ola == '2018' | datos.grafico$ola == '2021'))

#2
etiquetas.grafico <- data.frame((svytable(~c19_02_rec + ola + m0_sexo, 
                                          elsoc_diseno_2, round = F))) %>% 
  group_by(ola, m0_sexo) %>% 
  mutate(porcentaje=Freq/sum(Freq)) %>% 
  na.omit() %>% 
  mutate(idencuesta = 1)

#Paso 2.2: crear un subset sólo para los años
etiquetas.grafico <- droplevels(subset(etiquetas.grafico, etiquetas.grafico$ola == '2016' | etiquetas.grafico$ola == '2018' | etiquetas.grafico$ola == '2021'))

gr.16.4 <- ggplot(subset.grafico, aes(x = ola, fill = c19_02_rec, stratum = c19_02_rec, 
                              alluvium = idencuesta, y = porcentaje)) +
  theme_bw() +
  ggalluvial::geom_flow(alpha = .66) + 
  ggalluvial::geom_stratum(linetype = 0) +
  scale_y_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  scale_fill_viridis_d(begin = 0, end = .9, direction = -1, option = 'viridis') +
  facet_wrap(.~m0_sexo)+
  geom_text(data = etiquetas.grafico, 
            aes(label = ifelse(porcentaje > 0.05 , scales::percent(porcentaje, accuracy = .1),"")),
            position = position_stack(vjust = .5),
            show.legend = FALSE,
            size= 2.75, color = rep.int(c('black', 'white', 'white'), 6))

gr.16.4
```

```{r c19_03, fig.align='center', fig.cap='Sexismo hostil, según ola y sexo .'}

#1
datos.grafico <- data.frame((svytable(~c19_03_rec + ola + idencuesta + 
                                        m0_sexo, elsoc_diseno_2, round = F))) %>% 
  dplyr::filter(Freq>0)  %>% 
  group_by(ola, m0_sexo) %>% 
  mutate(porcentaje=Freq/sum(Freq)) %>% na.omit()

#1.1
subset.grafico <- droplevels(subset(datos.grafico, datos.grafico$ola == '2016' |  datos.grafico$ola == '2018' | datos.grafico$ola == '2021'))

#2
etiquetas.grafico <- data.frame((svytable(~c19_03_rec + ola + m0_sexo, 
                                          elsoc_diseno_2, round = F))) %>% 
  group_by(ola, m0_sexo) %>% 
  mutate(porcentaje=Freq/sum(Freq)) %>% 
  na.omit() %>% 
  mutate(idencuesta = 1)

#Paso 2.2: crear un subset sólo para los años
etiquetas.grafico <- droplevels(subset(etiquetas.grafico, etiquetas.grafico$ola == '2016' | etiquetas.grafico$ola == '2018' | etiquetas.grafico$ola == '2021'))

gr.16.5 <- ggplot(subset.grafico, aes(x = ola, fill = c19_03_rec, stratum = c19_03_rec, 
                              alluvium = idencuesta, y = porcentaje)) +
  theme_bw() +
  ggalluvial::geom_flow(alpha = .66) + 
  ggalluvial::geom_stratum(linetype = 0) +
  scale_y_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  scale_fill_viridis_d(begin = 0, end = .9, direction = -1, option = 'viridis') +
  facet_wrap(.~m0_sexo)+
  geom_text(data = etiquetas.grafico, 
            aes(label = ifelse(porcentaje > 0.05 , scales::percent(porcentaje, accuracy = .1),"")),
            position = position_stack(vjust = .5),
            show.legend = FALSE,
            size= 2.75, color = rep.int(c('black', 'white', 'white'), 6))

gr.16.5
```

```{r c19_04, fig.align='center', fig.cap='Sexismo hostil, según ola y sexo .'}

#1
datos.grafico <- data.frame((svytable(~c19_04_rec + ola + idencuesta + 
                                        m0_sexo, elsoc_diseno_2, round = F))) %>% 
  dplyr::filter(Freq>0)  %>% 
  group_by(ola, m0_sexo) %>% 
  mutate(porcentaje=Freq/sum(Freq)) %>% na.omit()

#1.1
subset.grafico <- droplevels(subset(datos.grafico, datos.grafico$ola == '2016' |  datos.grafico$ola == '2018' | datos.grafico$ola == '2021'))

#2
etiquetas.grafico <- data.frame((svytable(~c19_04_rec + ola + m0_sexo, 
                                          elsoc_diseno_2, round = F))) %>% 
  group_by(ola, m0_sexo) %>% 
  mutate(porcentaje=Freq/sum(Freq)) %>% 
  na.omit() %>% 
  mutate(idencuesta = 1)

#Paso 2.2: crear un subset sólo para los años
etiquetas.grafico <- droplevels(subset(etiquetas.grafico, etiquetas.grafico$ola == '2016' | etiquetas.grafico$ola == '2018' | etiquetas.grafico$ola == '2021'))

gr.16.6 <- ggplot(subset.grafico, aes(x = ola, fill = c19_04_rec, stratum = c19_04_rec, 
                              alluvium = idencuesta, y = porcentaje)) +
  theme_bw() +
  ggalluvial::geom_flow(alpha = .66) + 
  ggalluvial::geom_stratum(linetype = 0) +
  scale_y_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  scale_fill_viridis_d(begin = 0, end = .9, direction = -1, option = 'viridis') +
  facet_wrap(.~m0_sexo)+
  geom_text(data = etiquetas.grafico, 
            aes(label = ifelse(porcentaje > 0.05 , scales::percent(porcentaje, accuracy = .1),"")),
            position = position_stack(vjust = .5),
            show.legend = FALSE,
            size= 2.75, color = rep.int(c('black', 'white', 'white'), 6))

gr.16.6
```

## Trabajo y género

<!-- ### 12.7 Porcentaje de trabajadores y trabajadoras por situación ocupacional (2019), según sexo del entrevistado -->
```{r ocup-sexo, fig.align='center',fig.cap='Porcentaje de trabajadores y trabajadoras por situación ocupacional (2021), según sexo del entrevistado'}
elsoc_diseno <- svydesign(ids = ~segmento, #muestreo por conglomerado a nivel de manzanas (segmento)
                          strata = ~estrato, #muestreo estratificado a nivel ciudad (estato)
                          weights = ~ponderador02, #ponderador de corte transversal
                          nest = TRUE,
                          data = elsoc_panel_m1)

datos.grafico <- data.frame((svytable(~m0_sexo + ola + empleo, 
                                      elsoc_diseno, round = F))) %>% 
  group_by(ola, m0_sexo) %>% 
  mutate(porcentaje=Freq/sum(Freq)) %>%
  drop_na()

datos.subset <- droplevels(subset(datos.grafico, datos.grafico$ola == '2018' | datos.grafico$ola == '2021' ))

gr.16.7 <- datos.subset %>% 
  ggplot(aes(y = porcentaje, x = m0_sexo, fill = empleo, 
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  facet_wrap(.~ola)+
  scale_fill_viridis_d(begin = .13, end = .85, direction = -1, option = 'viridis') +
  #cambiar geom_text tal que: Stack y cambio colores
  geom_text(aes(label = ifelse(porcentaje > 0.03 , scales::percent(porcentaje, accuracy = .1),"")), position = position_stack(vjust = .5),
            show.legend = FALSE,
            size = 2.75,
            color = rep('black')) + 
  theme(legend.position = 'top',
        legend.title = element_blank())

gr.16.7

```


<!-- ### 12.8 Porcentaje de trabajadores y trabajadoras no remunerados, según ola y sexo del entrevistado -->
```{r ocup-sexo-ola, fig.align='center',fig.cap='Porcentaje de trabajadores y trabajadoras no remunerados, según ola y sexo del entrevistado'}
#1
elsoc_long$empleo <- na.replace(elsoc_long$empleo, "NS/NR") #recode NA en categoría "NS/NR"

elsoc_diseno_2 <- svydesign(ids = ~segmento, strata = ~estrato, 
                          weights = ~ponderador02, nest = TRUE, data = elsoc_panel)

datos.grafico <- data.frame((svytable(~empleo + ola + idencuesta + 
                                        m0_sexo, elsoc_diseno_2, round = F))) %>% 
  dplyr::filter(Freq>0)  %>% 
  group_by(ola,m0_sexo) %>% 
  mutate(porcentaje=Freq/sum(Freq)) %>% na.omit()

#1.1
subset.grafico <- droplevels(subset(datos.grafico, datos.grafico$ola == '2018' | datos.grafico$ola == '2021'))

#2
etiquetas.grafico <- data.frame((svytable(~empleo + ola + m0_sexo, 
                                          elsoc_diseno, round = F))) %>% 
  group_by(ola, m0_sexo) %>% 
  mutate(porcentaje=Freq/sum(Freq)) %>% 
  na.omit() %>% 
  mutate(idencuesta = 1)

#Paso 2.2: crear un subset sólo para los años 2017 y 2019
etiquetas.grafico <- droplevels(subset(etiquetas.grafico, 
                     etiquetas.grafico$ola == '2018' | etiquetas.grafico$ola == '2021'))

gr.16.8 <- ggplot(subset.grafico, aes(x = ola, fill = empleo, stratum = empleo, 
                              alluvium = idencuesta, y = porcentaje)) +
  theme_bw() +
  ggalluvial::geom_flow(alpha = .66) + 
  ggalluvial::geom_stratum(linetype = 0) +
  scale_y_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  scale_fill_viridis_d(begin = 0, end = .9, direction = -1, option = 'viridis') +
  facet_wrap(.~m0_sexo)+
  geom_text(data = etiquetas.grafico, 
            aes(label = ifelse(porcentaje > 0.03 , scales::percent(porcentaje, accuracy = .1),"")),
            position = position_stack(vjust = .5),
            show.legend = FALSE,
            size = 2.75,
            color = rep('white'))

gr.16.8
```

