---
editor_options: 
  markdown: 
    wrap: 72
---

# Salud mental y bienestar

```{r recode-var}
elsoc_panel_m1$depr_rec <- car::recode(elsoc_panel_m1$suma_dep,
                               "c(0,1,2,3,4)='1';
c(5,6,7,8,9)='2';
c(10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27)='3'")

elsoc_panel_m1$m43_rec <- car::recode(elsoc_panel_m1$m43,
                               "c(1,2)='Nada o Poco Sobrecargado';
c(3)='Algo Sobrecargado';
c(4,5)='Bastante o Muy Sobrecargado'")

elsoc_panel_m1$s03_rec <- car::recode(elsoc_panel_m1$s03,
                               "c(1,2)='Mala o Regular';
c(3)='Buena';
c(4,5)='Muy buena o Excelente'")

elsoc_diseno <- svydesign(ids = ~segmento, strata = ~estrato, 
                          weights = ~ponderador02, nest = TRUE, data = elsoc_panel_m1)

elsoc_panel$depr_rec <- car::recode(elsoc_panel$suma_dep,
                               "c(0,1,2,3,4)='1';
c(5,6,7,8,9)='2';
c(10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27)='3'")

elsoc_panel$m43_rec <- car::recode(elsoc_panel$m43,
                               "c(1,2)='Nada o Poco Sobrecargado';
c(3)='Algo Sobrecargado';
c(4,5)='Bastante o Muy Sobrecargado'")

elsoc_diseno_2 <- svydesign(ids = ~segmento, strata = ~estrato, 
                          weights = ~ponderador02, nest = TRUE, data = elsoc_panel)
```

```{r depre-wave, echo=FALSE, fig.align='center', fig.cap= 'Síntomas de Depresión, según Ola del Estudio'}
datos.g17.1 <- elsoc_long_2016_2021 %>% 
  mutate(s11_01_rec = as.numeric(car::recode(s11_01, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_02_rec = as.numeric(car::recode(s11_02, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_03_rec = as.numeric(car::recode(s11_03, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_04_rec = as.numeric(car::recode(s11_04, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_05_rec = as.numeric(car::recode(s11_05, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_06_rec = as.numeric(car::recode(s11_06, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_07_rec = as.numeric(car::recode(s11_07, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_08_rec = as.numeric(car::recode(s11_08, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_09_rec = as.numeric(car::recode(s11_09, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")), suma_dep = (s11_01_rec + s11_02_rec + s11_03_rec + s11_04_rec + 
                              s11_05_rec + s11_06_rec + s11_07_rec + s11_08_rec + s11_09_rec),
         depr = factor(car::recode(suma_dep,"c(0,1,2,3,4)='Sin sintomas o Minima';c(5,6,7,8,9)='Depresion Media'; c(10,11,12,13,14)='Depresion Moderada';c(15,16,17,18,19,20,21,22,23,24,25,26,27)='Depresion Moderada Severa a Severa'"), levels = c('Sin sintomas o Minima','Depresion Media','Depresion Moderada', 'Depresion Moderada Severa a Severa'))) %>%
  dplyr::filter(tipo_atricion == 1 & !is.na(depr)) %>% 
  prop(depr, by = c(ola), na.rm = TRUE, vartype = NULL) %>% 
  sjlabelled::as_label(depr, ola) 

g17.1 <- datos.g17.1 %>% 
  ggplot(aes(y = prop, x = ola, fill = depr, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .85, direction = -1, option = 'viridis') +
  #cambiar geom_text tal que: Stack y cambio colores
  geom_text(position = position_stack(vjust = .5),
            size= 2.75, color = rep.int(c('black', 'black', 'white', 'white'), 5)) + 
  theme(legend.position = 'top',
        legend.title = element_blank())
g17.1
```

```{r N5, include=FALSE}
N<-round(sum(datos.grafico$Freq),0)
```

```{r depre-deuda-wave, echo=FALSE, fig.align='center', fig.cap="Síntomas de Depresión, según Ola del Estudio y Sobrecarga de Deuda"}
datos.g17.2 <- elsoc_long_2016_2021 %>% 
  mutate(m43_rec = factor(car::recode(m43,"c(1,2)='Nada o Poco Sobrecargado'; c(3)='Algo Sobrecargado';
c(4,5)='Bastante o Muy Sobrecargado'", levels = c('Nada o Poco Sobrecargado','Algo Sobrecargado', 'Bastante o Muy Sobrecargado'))),
    s11_01_rec = as.numeric(car::recode(s11_01, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_02_rec = as.numeric(car::recode(s11_02, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_03_rec = as.numeric(car::recode(s11_03, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_04_rec = as.numeric(car::recode(s11_04, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_05_rec = as.numeric(car::recode(s11_05, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_06_rec = as.numeric(car::recode(s11_06, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_07_rec = as.numeric(car::recode(s11_07, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_08_rec = as.numeric(car::recode(s11_08, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_09_rec = as.numeric(car::recode(s11_09, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")), suma_dep = (s11_01_rec + s11_02_rec + s11_03_rec + s11_04_rec + 
                              s11_05_rec + s11_06_rec + s11_07_rec + s11_08_rec + s11_09_rec),
         depr = factor(car::recode(suma_dep,"c(0,1,2,3,4)='Sin sintomas o Minima';c(5,6,7,8,9)='Depresion Media'; c(10,11,12,13,14)='Depresion Moderada';c(15,16,17,18,19,20,21,22,23,24,25,26,27)='Depresion Moderada Severa a Severa'"), levels = c('Sin sintomas o Minima','Depresion Media','Depresion Moderada', 'Depresion Moderada Severa a Severa'))) %>%
  dplyr::filter(tipo_atricion == 1 & !m43_rec %in% c(-888, -999) & !is.na(depr) & !is.na(m43_rec)) %>% 
  prop(depr, by = c(ola, m43_rec), na.rm = TRUE, vartype = NULL) %>% 
  sjlabelled::as_label(depr, ola, m43_rec) 


g17.2 <- datos.g17.2 %>% 
  ggplot(aes(y = prop, x = ola, fill = depr, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .85, direction = -1, option = 'viridis') +
  #cambiar geom_text tal que: Stack y cambio colores
  geom_text(position = position_stack(vjust = .5),
            size= 2.75, color = rep.int(c('black', 'black', 'white', 'white'), 9)) + 
  facet_grid(~factor(m43_rec, levels=c('Nada o Poco Sobrecargado','Algo Sobrecargado','Bastante o Muy Sobrecargado'))) +
  theme(legend.position = 'top',
        legend.title = element_blank()) 

g17.2

```

```{r deuda-phq, fig.align='center',fig.cap="Deuda según ola y Sintomas Depresivos"}
#este grafico no logra nada... eliminarlo
datos.01 <- data.frame((svytable(~deuda_01 + ola + phq, elsoc_diseno, round = F))) %>% group_by(phq,ola) %>% mutate(p_01=Freq/sum(Freq))
datos.01$phq <- NULL
datos.01$ola <- NULL
datos.02 <- data.frame((svytable(~deuda_02 + ola + phq, elsoc_diseno, round = F))) %>% group_by(phq,ola) %>% mutate(p_02=Freq/sum(Freq))
datos.02$phq <- NULL
datos.02$ola <- NULL
datos.03 <- data.frame((svytable(~deuda_03 + ola + phq, elsoc_diseno, round = F))) %>% group_by(phq,ola) %>% mutate(p_03=Freq/sum(Freq))
datos.03$phq <- NULL
datos.03$ola <- NULL
datos.04 <- data.frame((svytable(~deuda_04  + ola + phq, elsoc_diseno, round = F))) %>% group_by(phq,ola) %>% mutate(p_04=Freq/sum(Freq))

datos.grafico1<- cbind(datos.01, datos.02, datos.03, datos.04)

subset.grafico <- droplevels(subset(datos.grafico1,
                                      deuda_01 == 'Si' & 
                                      deuda_02== 'Si' &
                                      deuda_03 == 'Si' & 
                                      deuda_04 == 'Si'))
#trasponer según variable
datos.grafico <- subset.grafico %>% 
  pivot_longer(cols = starts_with('deuda_'))  %>%
  mutate(variable = factor(name, labels = c('Deuda Casa Comercial',
                     'Deuda Banco',
                     'Deuda Pariente',
                     'Otras Deudas'))) %>% 
  drop_na()

datos.grafico$porcentaje <- with(datos.grafico, case_when(
  variable == 'Deuda Casa Comercial' ~ p_01,
  variable == 'Deuda Banco' ~ p_02,
  variable == 'Deuda Pariente' ~ p_03,
  variable == 'Otras Deudas' ~ p_04))

#graficamos

g17.3 <-datos.grafico %>% 
  ggplot(aes(y = porcentaje, x = variable, fill = ola, 
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) +
  theme_bw() + 
  geom_col(position = "dodge2") +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1, option = 'viridis') + 
  facet_wrap(.~phq)+
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75)  +
  theme(legend.position = 'top',
        legend.title = element_blank())

g17.3
```

## Brecha de género en Salud Mental

```{r depre-year-sexo, echo=FALSE, fig.align='center', fig.cap= 'Sintomatología Depresiva por año, según sexo. Porcentaje con síntomas de “Depresion Moderada” o “Depresion Moderada Severa a Severa”.'}
####me da muy distinto

datos.g17.4 <- elsoc_long_2016_2021 %>% 
  mutate(s11_01_rec = as.numeric(car::recode(s11_01, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_02_rec = as.numeric(car::recode(s11_02, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_03_rec = as.numeric(car::recode(s11_03, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_04_rec = as.numeric(car::recode(s11_04, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_05_rec = as.numeric(car::recode(s11_05, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_06_rec = as.numeric(car::recode(s11_06, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_07_rec = as.numeric(car::recode(s11_07, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_08_rec = as.numeric(car::recode(s11_08, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_09_rec = as.numeric(car::recode(s11_09, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")), suma_dep = (s11_01_rec + s11_02_rec + s11_03_rec + s11_04_rec + 
                              s11_05_rec + s11_06_rec + s11_07_rec + s11_08_rec + s11_09_rec),
         phq = factor(car::recode(suma_dep,"c(0,1,2,3,4,5,6,7,8,9)='Sin Sintomas Depresivos';c(10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27)='Con Sintomas Depresivos'"), levels = c('Sin Sintomas Depresivos','Con Sintomas Depresivos'))) %>%
  dplyr::filter(tipo_atricion == 1 & muestra == 1 & !phq %in% c(-888, -999, NA)) %>% 
  prop(phq=='Con Sintomas Depresivos', by = c(ola, m0_sexo), na.rm = TRUE, vartype = NULL) %>% 
  sjlabelled::as_label(phq, ola, m0_sexo) 

g17.4 <- ggplot(datos.g17.4, 
               aes(y = prop, x = ola, 
                   color = m0_sexo, group = m0_sexo,
              label = as.character(scales::percent(prop, accuracy = .1)))) +
  theme_bw() +   
  geom_line(size = 1) +
  geom_point(size = 1.8) +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0,0.5)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .33, end = .55, direction = 1, option = 'viridis') +
  geom_text_repel(posilinetion = position_dodge(width = .9),
                  size= 2.25) + 
  theme(legend.position = 'top',
        legend.title = element_blank()) 

g17.4
 
```
```{r N6, include=FALSE}
N<-round(sum(datos.grafico$Freq),0)
```

```{r depre-sexo, echo=FALSE, fig.align='center', fig.cap= 'Cambios en Síntomas de depresión entre años 2018 y 2021, según sexo'}

#1
elsoc_panel$depr <- na.replace(elsoc_panel$depr, "NS/NR") #recode NA en categoría "NS/NR"

elsoc_diseno_2 <- svydesign(ids = ~segmento, strata = ~estrato, 
                          weights = ~ponderador02, nest = TRUE, data = elsoc_panel)

datos.grafico <- data.frame((svytable(~depr + ola + idencuesta + 
                                        m0_sexo, elsoc_diseno_2, round = F))) %>% 
  dplyr::filter(Freq>0)  %>% 
  group_by(ola,m0_sexo) %>% 
  mutate(porcentaje=Freq/sum(Freq)) %>% na.omit()

#1.1
subset.grafico <- droplevels(subset(datos.grafico, datos.grafico$ola == '2018' | datos.grafico$ola == '2021'))

#2
etiquetas.grafico <- data.frame((svytable(~depr + ola + m0_sexo, 
                                          elsoc_diseno, round = F))) %>% 
  group_by(ola, m0_sexo) %>% 
  mutate(porcentaje=Freq/sum(Freq)) %>% 
  na.omit() %>% 
  mutate(idencuesta = 1)

#Paso 2.2: crear un subset sólo para los años 2017 y 2019
etiquetas.grafico <- droplevels(subset(etiquetas.grafico, 
                     etiquetas.grafico$ola == '2018' | etiquetas.grafico$ola == '2021'))

g17.5 <- ggplot(subset.grafico, aes(x = ola, fill = depr, stratum = depr, 
                              alluvium = idencuesta, y = porcentaje)) +
  theme_bw() +
  ggalluvial::geom_flow(alpha = .66) + 
  ggalluvial::geom_stratum(linetype = 0) +
  scale_y_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  scale_fill_viridis_d(begin = 0, end = .9, direction = -1, option = 'viridis') +
  facet_wrap(.~m0_sexo)+
  geom_text(data = etiquetas.grafico, 
            aes(label = ifelse(porcentaje > 0.1 , scales::percent(porcentaje, accuracy = .1),"")),
            position = position_stack(vjust = .5),
            show.legend = FALSE,
            size = 2.75,
            color = rep('white'))

g17.5

```

```{r N7, include=FALSE}
N<-round(sum(datos.grafico$Freq),0)
```

```{r depre-edad-sexo, echo=FALSE, fig.align='center', fig.cap='Síntomas de Depresión según tramos de edad y sexo (2021). Porcentaje con síntomas de “Depresion Moderada” o “Depresion Moderada Severa a Severa'}
####me da muy distinto
datos.g17.6 <- elsoc_long_2016_2021 %>% 
  mutate(s11_01_rec = as.numeric(car::recode(s11_01, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_02_rec = as.numeric(car::recode(s11_02, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_03_rec = as.numeric(car::recode(s11_03, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_04_rec = as.numeric(car::recode(s11_04, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_05_rec = as.numeric(car::recode(s11_05, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_06_rec = as.numeric(car::recode(s11_06, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_07_rec = as.numeric(car::recode(s11_07, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_08_rec = as.numeric(car::recode(s11_08, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_09_rec = as.numeric(car::recode(s11_09, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")), suma_dep = (s11_01_rec + s11_02_rec + s11_03_rec + s11_04_rec + 
                              s11_05_rec + s11_06_rec + s11_07_rec + s11_08_rec + s11_09_rec),
         phq = factor(car::recode(suma_dep,"c(0,1,2,3,4,5,6,7,8,9)='Sin Sintomas Depresivos';c(10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27)='Con Sintomas Depresivos'"), levels = c('Sin Sintomas Depresivos','Con Sintomas Depresivos')),
         edadt = factor(car::recode(m0_edad, "18:29 = 1; 30:49 = 2; 50:64 = 3; 65:150 = 4"),
                           labels = c('18-29', '30-49', '50-64', '65 o más'))) %>%
  dplyr::filter(ola==5 & tipo_atricion == 1 & muestra == 1 & !phq %in% c(-888, -999, NA)) %>% 
  prop(phq=='Con Sintomas Depresivos', by = c(edadt,m0_sexo), na.rm = TRUE) %>% 
  sjlabelled::as_label(phq, edadt,m0_sexo)


g17.6 <- ggplot(datos.g17.6, 
               aes(y = prop, x = edadt, 
                   color = m0_sexo, group = m0_sexo,
                   label = as.character(scales::percent(prop, accuracy = .1)))) +
  theme_bw() +   
  geom_line(size = 1) +
  geom_point(size = 1.8) +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0,0.5)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .33, end = .55, direction = 1, option = 'viridis') +
  geom_text_repel(posilinetion = position_dodge(width = .9),
                  size= 2.25) + 
  theme(legend.position = 'top',
        legend.title = element_blank())

g17.6

```

```{r N8, include=FALSE}
N<-round(sum(datos.grafico$Freq),0)
``` 

## Sintomatología depresiva, sexo y ocupación

```{r depre-labstat, echo=FALSE, fig.align='center', fig.cap='Síntomas de Depresión según sexo y situación ocupacional (2021). Porcentaje con síntomas PHQ-9>10'}
####me da muy distinto
datos.g17.7 <- elsoc_long_2016_2021 %>% 
  mutate(s11_01_rec = as.numeric(car::recode(s11_01, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_02_rec = as.numeric(car::recode(s11_02, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_03_rec = as.numeric(car::recode(s11_03, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_04_rec = as.numeric(car::recode(s11_04, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_05_rec = as.numeric(car::recode(s11_05, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_06_rec = as.numeric(car::recode(s11_06, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_07_rec = as.numeric(car::recode(s11_07, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_08_rec = as.numeric(car::recode(s11_08, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_09_rec = as.numeric(car::recode(s11_09, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")), suma_dep = (s11_01_rec + s11_02_rec + s11_03_rec + s11_04_rec + 
                              s11_05_rec + s11_06_rec + s11_07_rec + s11_08_rec + s11_09_rec),
         phq = factor(car::recode(suma_dep,"c(0,1,2,3,4,5,6,7,8,9)='Sin Sintomas Depresivos';c(10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27)='Con Sintomas Depresivos'"), levels = c('Sin Sintomas Depresivos','Con Sintomas Depresivos')),
         empleo = factor(car::recode(m02, "c(1,2,3) = 'Trabajo remunerado'; 7 = 'Trabajo doméstico no remunerado'; 6 = 'Desempleado/a'; 5 = 'Jubilado/a o pensionado/a'; c(4, 8, 9) = 'Otras categorías'"), levels = c("Trabajo remunerado", "Trabajo doméstico no remunerado", "Desempleado/a", "Jubilado/a o pensionado/a", "Otras categorías"))) %>%
  dplyr::filter(ola==5 & tipo_atricion == 1 & !phq %in% c(-888, -999, NA)) %>% 
  prop(phq=='Con Sintomas Depresivos', by = c(empleo,m0_sexo)) %>% 
  sjlabelled::as_label(phq,empleo,m0_sexo)


datos.grafico <- data.frame((svytable(~phq + ola + m0_sexo + empleo, 
                                      elsoc_diseno, round = F))) %>% 
  group_by(ola, m0_sexo, empleo) %>% 
  mutate(porcentaje=Freq/sum(Freq)) %>% 
  filter(ola==2021)

g17.7 <- datos.g17.7 %>% 
  ggplot(aes(y = prop, x = empleo, fill = m0_sexo, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, .5)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .65, direction = -1, option = 'viridis') +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75) +
  theme(legend.position = 'top',
        legend.title = element_blank()) 

g17.7
```

En 2021 no hay hombres en la categoría Trabajo doméstico no remunerado $^{*}$

```{r N9, include=FALSE}
N<-round(sum(datos.grafico$Freq),0)
```

## COVID - 19
```{r covid-sexo, fig.align='center', fig.cap= 'Sí fue diagnosticado con COVID-19, según sexo'}
datos.g17.8 <- elsoc_long_2016_2021 %>% 
  dplyr::filter(ola == 5 & tipo_atricion == 1 & !s31 %in% c(-888, -999, NA)) %>% 
  prop(s31==1, by=m0_sexo, na.rm = TRUE, vartype = NULL) %>% 
  sjlabelled::as_label(s31,m0_sexo)


g17.8 <- datos.g17.8 %>% 
  ggplot(aes(y = prop, x = m0_sexo, 
             label = as.character(scales::percent(prop, accuracy = .1)))) +
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 0.2)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1, option = 'viridis') +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75)  + 
  theme(legend.position = 'top',
        legend.title = element_blank())

g17.8
```

```{r depre-s03, echo=FALSE, fig.align='center', fig.cap='Síntomas de Depresión según Estado de Salud y ola de estudio. Porcentaje con síntomas PHQ-9>10'}
datos.g17.9 <- elsoc_long_2016_2021 %>% 
  mutate(s11_01_rec = as.numeric(car::recode(s11_01, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_02_rec = as.numeric(car::recode(s11_02, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_03_rec = as.numeric(car::recode(s11_03, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_04_rec = as.numeric(car::recode(s11_04, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_05_rec = as.numeric(car::recode(s11_05, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_06_rec = as.numeric(car::recode(s11_06, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_07_rec = as.numeric(car::recode(s11_07, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_08_rec = as.numeric(car::recode(s11_08, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_09_rec = as.numeric(car::recode(s11_09, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")), suma_dep = (s11_01_rec + s11_02_rec + s11_03_rec + s11_04_rec + 
                              s11_05_rec + s11_06_rec + s11_07_rec + s11_08_rec + s11_09_rec),
         phq = factor(car::recode(suma_dep,"c(0,1,2,3,4,5,6,7,8,9)='Sin Sintomas Depresivos';c(10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27)='Con Sintomas Depresivos'"), levels = c('Sin Sintomas Depresivos','Con Sintomas Depresivos')),
         s03_rec = factor(car::recode(s03, "c(1) = 'Mala'; c(2,3) = 'Regular o Buena'; c(3,4) = 'Muy Buena o Excelente'"),
                           levels = c('Mala', 'Regular o Buena', 'Muy Buena o Excelente'))) %>%
  dplyr::filter(tipo_atricion == 1 & !phq %in% c(-888, -999, NA) & !is.na(s03_rec)) %>% 
  prop(phq=='Con Sintomas Depresivos', by = c(s03_rec, ola), na.rm = TRUE) %>% 
  sjlabelled::as_label(phq, s03_rec, ola)


g17.9 <- datos.g17.9  %>% 
  ggplot(aes(y =prop, x = ola, fill = s03_rec, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, .5)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .65, direction = -1, option = 'viridis') +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75) +
  theme(legend.position = 'top',
        legend.title = element_blank()) 

g17.9
```

## Salud Mental en COVID-19

```{r depre-teletrabajo, echo=FALSE, fig.align='center', fig.cap='Síntomas de Depresión, según Modalidad de Trabajo'}
datos.g17.10 <- elsoc_long_2016_2021 %>% 
  mutate(s11_01_rec = as.numeric(car::recode(s11_01, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_02_rec = as.numeric(car::recode(s11_02, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_03_rec = as.numeric(car::recode(s11_03, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_04_rec = as.numeric(car::recode(s11_04, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_05_rec = as.numeric(car::recode(s11_05, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_06_rec = as.numeric(car::recode(s11_06, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_07_rec = as.numeric(car::recode(s11_07, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_08_rec = as.numeric(car::recode(s11_08, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_09_rec = as.numeric(car::recode(s11_09, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")), suma_dep = (s11_01_rec + s11_02_rec + s11_03_rec + s11_04_rec + 
                              s11_05_rec + s11_06_rec + s11_07_rec + s11_08_rec + s11_09_rec),
         depr = factor(car::recode(suma_dep,"c(0,1,2,3,4)='Sin sintomas o Minima';c(5,6,7,8,9)='Depresion Media'; c(10,11,12,13,14)='Depresion Moderada';c(15,16,17,18,19,20,21,22,23,24,25,26,27)='Depresion Moderada Severa a Severa'"), levels = c('Sin sintomas o Minima','Depresion Media','Depresion Moderada', 'Depresion Moderada Severa a Severa'))) %>%
  dplyr::filter(tipo_atricion == 1 & !depr %in% c(-888, -999, NA) & !m60 %in% c(-888, -999, NA)) %>% 
  prop(depr, by = c(ola, m60), na.rm = TRUE, vartype = NULL) %>% 
  sjlabelled::as_label(depr, m60) 


g17.10 <- datos.g17.10 %>% 
  ggplot(aes(y = prop, x = m60, fill = depr, 
             label = as.character(scales::percent(prop, accuracy = .1)))) +
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1, option = 'viridis') +
  geom_text(position = position_stack(vjust = .5),
            size= 2.75)  + 
  theme(legend.position = 'top',
        legend.title = element_blank())

g17.10
```

```{r depre-beneficios, echo=FALSE, fig.align='center', fig.cap='Síntomas de Depresión (2021), según sexo y acceso a beneficios'}
datos.g17.11 <- elsoc_long_2016_2021 %>% 
  mutate(s11_01_rec = as.numeric(car::recode(s11_01, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_02_rec = as.numeric(car::recode(s11_02, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_03_rec = as.numeric(car::recode(s11_03, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_04_rec = as.numeric(car::recode(s11_04, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_05_rec = as.numeric(car::recode(s11_05, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_06_rec = as.numeric(car::recode(s11_06, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_07_rec = as.numeric(car::recode(s11_07, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_08_rec = as.numeric(car::recode(s11_08, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_09_rec = as.numeric(car::recode(s11_09, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")), suma_dep = (s11_01_rec + s11_02_rec + s11_03_rec + s11_04_rec + 
                              s11_05_rec + s11_06_rec + s11_07_rec + s11_08_rec + s11_09_rec),
         depr = factor(car::recode(suma_dep,"c(0,1,2,3,4)='Sin sintomas o Minima';c(5,6,7,8,9)='Depresion Media'; c(10,11,12,13,14)='Depresion Moderada';c(15,16,17,18,19,20,21,22,23,24,25,26,27)='Depresion Moderada Severa a Severa'"), levels = c('Sin sintomas o Minima','Depresion Media','Depresion Moderada', 'Depresion Moderada Severa a Severa'))) %>%
  dplyr::filter(tipo_atricion == 1 & !depr %in% c(-888, -999, NA) & !m63_01 %in% c(-888, -999, NA)) %>% 
  prop(depr, by = c(m63_01, m0_sexo), na.rm = TRUE, vartype = NULL) %>% 
  sjlabelled::as_label(depr, m63_01, m0_sexo) 

g17.11 <- datos.g17.11 %>% 
  ggplot(aes(y = prop, x = m63_01, fill = depr, 
             label = as.character(scales::percent(prop, accuracy = .1)))) +
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = 0, end = .85, direction = -1, option = 'viridis') +
  #Agrego facer_wrap para hacer un Gráfico para cada sexo
  facet_wrap(datos.subset$m0_sexo) +
  geom_text(position = position_stack(vjust = .5),
            size= 2.75, color = rep.int(c('black', 'black', 'white', 'white'), 4)) + 
  theme(legend.position = 'top',
        legend.title = element_blank())

g17.11
```

```{r depre clase.sub, echo=FALSE, fig.align='center', fig.cap='Síntomas de Depresión, según Clase Subjetiva y ola. Porcentaje con síntomas PHQ-9>10'}
datos.g17.12 <- elsoc_long_2016_2021 %>% 
  mutate(s11_01_rec = as.numeric(car::recode(s11_01, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_02_rec = as.numeric(car::recode(s11_02, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_03_rec = as.numeric(car::recode(s11_03, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_04_rec = as.numeric(car::recode(s11_04, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_05_rec = as.numeric(car::recode(s11_05, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_06_rec = as.numeric(car::recode(s11_06, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_07_rec = as.numeric(car::recode(s11_07, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_08_rec = as.numeric(car::recode(s11_08, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")) , s11_09_rec = as.numeric(car::recode(s11_09, " '1' = 0; '2' = 1; '3' = 2; c('5', '4') = 3")), suma_dep = (s11_01_rec + s11_02_rec + s11_03_rec + s11_04_rec + 
                              s11_05_rec + s11_06_rec + s11_07_rec + s11_08_rec + s11_09_rec),
         phq = factor(car::recode(suma_dep,"c(0,1,2,3,4,5,6,7,8,9)='Sin Sintomas Depresivos';c(10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27)='Con Sintomas Depresivos'"), levels = c('Sin Sintomas Depresivos','Con Sintomas Depresivos')),
         clase.sub = factor(car::recode(d01_01, "c(0,1,2,3)='Baja y media baja'; c(4, 5)='Media'; c(6,7,8,9,10)='Alta y media alta'"),
                           levels = c("Baja y media baja", "Media", "Alta y media alta"))) %>%
  dplyr::filter(tipo_atricion == 1 & !phq %in% c(-888, -999, NA) & !is.na(clase.sub)) %>% 
  prop(phq=='Con Sintomas Depresivos', by = c(clase.sub, ola), na.rm = TRUE) %>% 
  sjlabelled::as_label(phq, clase.sub, ola)


g17.12 <- datos.g17.12 %>% 
  ggplot(aes(y = prop, x = ola, fill = clase.sub, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, .5)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1, option = 'viridis') +
  #cambiar geom_text tal que: Stack y cambio colores
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75) +
  theme(legend.position = 'top',
        legend.title = element_blank())

g17.12

```

