---
editor_options: 
  markdown: 
    wrap: 72
---
```{r variables-covid, include=FALSE}
#Análisis de Cuarentenas por comuna en base a datos del Ministerio de Ciencia (@MinCiencia)
library(readr)
library(dplyr)
library(scales)
library(ggplot2)
library(reshape2)
library(leaflet)
library(ggplot2)
library(data.table)
library(tidyr)
library(stringr)
library(lubridate)

#abrir bases de datos necesarias
load(file.path('1_input', 'ELSOC_Long_2016_2021_v1.00_R.RData'))

## DATA CUARENTENA ---------
# Url para descarga directa de datos desde el Github del Ministerio de Ciencia
url <- "https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output"

## Cuarentenas desde 2020/07/28 al día actualizado.
df_pasos <- read_csv(paste(url,"producto74","paso_a_paso_std.csv", sep="/"))
df_pasos$Fecha<-as.Date(df_pasos$Fecha)
df_pasos$dia <- weekdays(as.Date(df_pasos$Fecha))

#new variable dias_cuarentena
df_pasos$cuarentena <- case_when(df_pasos$Paso==1 ~ 1,
                                 df_pasos$Paso==2 & df_pasos$dia=="Saturday" ~ 1,
                                 df_pasos$Paso==2 & df_pasos$dia=="Sunday" ~ 1,
                                 TRUE ~ 0)
df_pasos <- df_pasos %>% 
  filter(zona=="Urbana" | zona=="Total")

#cuarentena acomulada del 2020/07/27 a la fecha de entrevista
df_pasos2 <- df_pasos %>% 
  group_by(codigo_comuna, zona) %>% 
  mutate(csum = cumsum(cuarentena)) %>% 
  mutate(ola=5)

#crear variable fecha entrevista
elsoc_long_2016_2021$fecha_entr <- as.Date(with(elsoc_long_2016_2021, paste(annio_entr, mes_entr, dia_entr ,sep="-")), "%Y-%m-%d")

#unir bbdd
els_long <- merge(x = elsoc_long_2016_2021, 
                  y = df_pasos2[ , c("Fecha","codigo_comuna", "csum", "ola")], 
                   by.x=c("fecha_entr", "comuna_cod", "ola"), 
                   by.y=c("Fecha", "codigo_comuna", "ola"), all.x = T)

## Cuarentenas desde 2021/03 hasta 2020/07/28 
pre_27jul <- read_csv(paste(url,"producto29","Cuarentenas-Totales.csv", sep="/"))
names(pre_27jul) <- names(pre_27jul) %>% str_to_lower() %>% str_replace_all(" ","_")
pre_27jul$fecha_de_inicio <- as.Date(pre_27jul$fecha_de_inicio)
pre_27jul$fecha_de_término <- as.Date(pre_27jul$fecha_de_término)

# cortar en fecha 2020/07/27 
pre_27jul$fecha_de_termino2 <- ifelse(pre_27jul$fecha_de_término>"2020-07-27",
                                      date("2020-07-27"),
                                      pre_27jul$fecha_de_término)

pre_27jul$fecha_termino <- as.Date(pre_27jul$fecha_de_termino2, 
                                   origin = "1970-01-01")
#filtrar fecha_inicio > 2020/07/27 
pre_27jul <- pre_27jul %>% filter(fecha_de_inicio<"2020/07/27")
#calcular dias en cuarentena
pre_27jul$dias <- as.Date(pre_27jul$fecha_termino) - 
  as.Date(pre_27jul$fecha_de_inicio)

pre_27jul$dias <- as.numeric(pre_27jul$dias, units="days")

## Unir fechas
pre_27jul <- pre_27jul %>% 
  group_by(código_cut_comuna) %>% 
  summarise(cuarentena_pre_27jul = sum(dias))  %>% 
  mutate(ola=5)

els_long2 <- merge(x = els_long, y = pre_27jul, 
                   by.x=c("ola", "comuna_cod"), 
                   by.y=c("ola", "código_cut_comuna"), all.x = T)
els_long2$cuarentena_pre_27jul[is.na(els_long2$cuarentena_pre_27jul)] <- 0
#VARIABLE 1: cuarentena en els_long3 acomulada
els_long2$ccum <- els_long2$cuarentena_pre_27jul + els_long2$csum

#VARIABLE 2: dummy de cuarentena en els_long3
elsoc_covid <- merge(x = els_long2, y = df_pasos, 
                   by.x=c("fecha_entr", "comuna_cod"), 
                   by.y=c("Fecha", "codigo_comuna"), all.x = T)


elsoc_covid$ccum <- as.numeric(as.character(elsoc_covid$ccum))

elsoc_covid$cuarentena <- factor(elsoc_covid$cuarentena,
                            levels = c(0,1),
                            labels = c("Sin Cuarentena", "Con Cuarentena"))

elsoc_covid$ccum_t <- factor(car::recode(elsoc_covid$ccum, "0='0 Dias';1:99='1-99 Dias';
                                        100:149='100-149 Dias';150:500='150 o más Dias'"),
                           levels = c('0 Dias', '1-99 Dias', '100-149', '150 o más Dias'))

elsoc_covid_panel <- elsoc_covid %>% filter(tipo_atricion == 1 | 
                                            tipo_atricion == 17 )

```

# Pandemia Covid-19

## Cuarentenas 
```{r hist-fecha-2021, fig.align='center', fig.cap="Histograma Fechas de Entrevistas"}
datos.g19.1 <- elsoc_covid_panel %>% 
  dplyr::filter(ola==5) %>% 
  prop(fecha_entr, by = c(comuna_cod), na.rm = TRUE, vartype = NULL) %>% 
  sjlabelled::as_label(comuna_cod) 

g19.1 <- datos.g19.1 %>% 
  ggplot(mapping = aes(x = fecha_entr)) +
  theme_bw() + 
  geom_histogram(bins = 9,
                 stat="count") +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_x_date(date_breaks = "1 month", date_labels = "%d %b %Y")

g19.1
```

```{r ccum-heter, fig.align='center', fig.cap="Heterogeneidad de Cuarentena Acumulada en el Panel"}
g19.2 <- elsoc_covid_panel %>% 
  ggplot(aes(x=ccum)) + 
  geom_histogram(aes(y = ..density..), bins=30) + 
  geom_density() +
  theme_bw() +
  ylab(label = NULL) +
  xlab(label = "Tiempo (Nº de Días)")

g19.2
```

```{r ccum-zona, fig.align='center', fig.cap='Días de Cuarentena Acumulada al momento de la entrevista, según Zona'}
datos.g19.3 <- elsoc_covid_panel %>% 
  mutate(zona1 = factor(car::recode(region_cod, "c(1,2,3,4,15)='Norte'; c(5,6,7,8,16)='Centro'; c(9,10,11,12,14)='Sur'; 13='Metropolitana'", levels = c("Norte","Centro","Sur","Metropolitana"))))  %>% 
  dplyr::filter(ola==5 & !is.na(ccum_t))   %>% 
  prop(ccum_t, by = c(zona1), na.rm = TRUE, vartype = NULL) %>% 
  sjlabelled::as_label(zona1) 
  

g19.3 <- datos.g19.3 %>% 
  ggplot(aes(y = prop, x = zona1, fill = ccum_t, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .85, direction = -1, option = 'viridis') +
  #cambiar geom_text tal que: Stack y cambio colores
  geom_text(position = position_stack(vjust = .5),
            size= 2.75) + 
  theme(legend.position = 'top',
        legend.title = element_blank()) 

g19.3
```

```{r ccum-edad, fig.align='center', fig.cap='Días de Cuarentena Acumulada al momento de la entrevista, según Tramo Etario'}
datos.grafico <- data.frame((svytable(~ccum_t + edadt, 
                                      elsoc_diseno_3, round = F))) %>% 
  group_by(edadt) %>% 
  mutate(porcentaje=Freq/sum(Freq))

g19.4 <- datos.grafico %>% 
  ggplot(aes(y = porcentaje, x = edadt, fill = ccum_t, 
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .85, direction = -1, option = 'viridis') +
  #cambiar geom_text tal que: Stack y cambio colores
  geom_text(position = position_stack(vjust = .5),
            size= 2.75, color = rep.int(c('black', 'black', 'white', 'white'), 4)) + 
  theme(legend.position = 'top',
        legend.title = element_blank())

g19.4
```

```{r ccum-aislamiento, fig.align='center', fig.cap='Cumplimiento de Aislamiento Social, según Días de Cuarentena Acumulada al momento de la entrevista'}
datos.grafico <- data.frame((svytable(~c48 + ccum_t, 
                                      elsoc_diseno_3, round = F))) %>% 
  group_by(ccum_t) %>% 
  mutate(porcentaje=Freq/sum(Freq))

g19.5 <- datos.grafico %>% 
  ggplot(aes(y = porcentaje, x = ccum_t, fill = c48, 
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .85, direction = -1, option = 'viridis') +
  #cambiar geom_text tal que: Stack y cambio colores
  geom_text(position = position_stack(vjust = .5),
            size= 2.75, color = rep.int(c('black', 'black', 'white', 'white', 'white'), 4)) + 
  theme(legend.position = 'top',
        legend.title = element_blank())

g19.5
```

```{r ccum-depr, fig.align='center', fig.cap= 'Sintomatología Depresiva, según Días de Cuarentena Acumulada al momento de la entrevista'}
datos.grafico <- data.frame((svytable(~depr + ccum_t + ola, 
                                      elsoc_diseno_3, round = F))) %>% 
  group_by(ccum_t, ola) %>% 
  mutate(porcentaje=Freq/sum(Freq))%>%
  filter(ola==2021)

g19.6 <- datos.grafico %>% 
  ggplot(aes(y = porcentaje, x = ccum_t, fill = depr, 
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .85, direction = -1, option = 'viridis') +
  #cambiar geom_text tal que: Stack y cambio colores
  geom_text(position = position_stack(vjust = .5),
            size= 2.75, color = rep.int(c('black', 'black', 'white', 'white'), 4)) + 
  theme(legend.position = 'top',
        legend.title = element_blank())
g19.6
```

```{r ccum-sit_ocup, fig.align='center', fig.cap= 'Situación Ocupacional, según Días de Cuarentena Acumulada al momento de la entrevista'}
datos.grafico <- data.frame((svytable(~empleo + ccum_t, 
                                      elsoc_diseno_3, round = F))) %>% 
  group_by(ccum_t) %>% 
  mutate(porcentaje=Freq/sum(Freq))

g19.7 <- datos.grafico %>% 
  ggplot(aes(y = porcentaje, x = ccum_t, fill = empleo, 
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .85, direction = -1, option = 'viridis') +
  #cambiar geom_text tal que: Stack y cambio colores
  geom_text(position = position_stack(vjust = .5),
            size= 2.75, color = rep.int(c('black', 'black', 'white', 'white'), 5)) + 
  theme(legend.position = 'top',
        legend.title = element_blank())

g19.7
```

```{r ccum-ahorro, fig.align='center', fig.cap= 'Nivel de Ahorro, según Días de Cuarentena Acumulada al momento de la entrevista'}
elsoc_covid_panel$m44_rec <- car::recode(elsoc_covid_panel$m44,
                               "c(1,2)='Nada o Pocos Ahorros';
c(3)='Algo de Ahorros';
c(4,5)='Bastante o Muchos Ahorros'")

elsoc_diseno_3 <- svydesign(ids = ~segmento, strata = ~estrato, 
                          weights = ~ponderador02, nest = TRUE, data = elsoc_covid_panel)

datos.grafico <- data.frame((svytable(~m44_rec + ccum_t, 
                                      elsoc_diseno_3, round = F))) %>% 
  group_by(ccum_t) %>% 
  mutate(porcentaje=Freq/sum(Freq))

g19.8 <- datos.grafico %>% 
  ggplot(aes(y = porcentaje, x = ccum_t, fill = m44_rec, 
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .85, direction = -1, option = 'viridis') +
  #cambiar geom_text tal que: Stack y cambio colores
  geom_text(position = position_stack(vjust = .5),
            size= 2.75, color = rep.int(c('black', 'black', 'white', 'white'), 3)) + 
  theme(legend.position = 'top',
        legend.title = element_blank()) 

g19.8
```

```{r cuarentena-etario, fig.align='center', fig.cap= 'Encuestados en Cuarentena según Tramo Etario'}
datos.grafico <- data.frame((svytable(~cuarentena + edadt + ola, 
                                      elsoc_diseno_3, round = F))) %>% 
  group_by(edadt + ola) %>% 
  mutate(porcentaje=Freq/sum(Freq)) %>% 
  filter(ola==2021)

g19.9 <- datos.grafico %>% 
  ggplot(aes(y = porcentaje, x = cuarentena, fill = edadt, 
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) +
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1, option = 'viridis') +
  geom_text(position = position_stack(vjust = .5),
            size= 2.75) +
  theme(legend.position = 'top',
        legend.title = element_blank())

g19.9
```

## Estrés Financiero
```{r satisfaccion-wave, echo=FALSE, fig.align='center', fig.cap= 'Satisfacción con el Ingreso por Ola'}
elsoc_diseno <- svydesign(ids = ~segmento, strata = ~estrato, 
                          weights = ~ponderador02, nest = TRUE, data = elsoc_panel_m1)

datos.grafico <- data.frame((svytable(~m43 + ola, 
                                      elsoc_diseno, round = F))) %>% 
  group_by(ola) %>% 
  mutate(porcentaje=Freq/sum(Freq)) %>%
  drop_na()

g19.10 <- datos.grafico %>% 
  ggplot(aes(y = porcentaje, x = ola, fill = m43, 
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .85, direction = -1, option = 'viridis') +
  #cambiar geom_text tal que: Stack y cambio colores
  geom_text(position = position_stack(vjust = .5),
            size= 2.75, color = rep.int(c('black', 'black','white', 'white','white' ), 3)) + 
  theme(legend.position = 'top',
        legend.title = element_blank()) 
g19.10
```

```{r satisfaccion-retiro, echo=FALSE, fig.align='center', fig.cap= 'Satisfacción con el Ingreso según Retiro AFP'}
datos.grafico <- data.frame((svytable(~m16 + m63_02, 
                                      elsoc_diseno, round = F))) %>% 
  group_by(m63_02) %>% 
  mutate(porcentaje=Freq/sum(Freq))

g19.11 <- datos.grafico %>% 
  ggplot(aes(y = porcentaje, x = m63_02, fill = m16, 
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .85, direction = -1, option = 'viridis') +
  #cambiar geom_text tal que: Stack y cambio colores
  geom_text(position = position_stack(vjust = .5),
            size= 2.75) + 
  theme(legend.position = 'top',
        legend.title = element_blank()) 

g19.11
```

```{r clase.sub-benef.estatal, echo=FALSE, fig.align='center', fig.cap='Satisfacción con el Ingreso según Acceso a Beneficios'}
elsoc_diseno_2 <- svydesign(ids = ~segmento,
                          strata = ~estrato, 
                          weights = ~ponderador02,
                          nest = TRUE,
                          data = elsoc_panel)

datos.grafico <- data.frame((svytable(~clase.sub + m63_01, 
                                      elsoc_diseno_2, round = F))) %>% 
  group_by(m63_01) %>% 
  mutate(porcentaje=Freq/sum(Freq)) %>%
  drop_na()

g19.12 <- datos.grafico %>% 
  ggplot(aes(y = porcentaje, x = m63_01, fill = clase.sub, 
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .85, direction = -1, option = 'viridis') +
  #cambiar geom_text tal que: Stack y cambio colores
  geom_text(position = position_stack(vjust = .5),
            size= 2.75) + 
  theme(legend.position = 'top',
        legend.title = element_blank()) 

g19.12
```

```{r clase.sub.hij-1erretiro, echo=FALSE, fig.align='center', fig.cap='Clase Social Subjetiva de Hijo según Primer Retiro AFP'}
datos.grafico <- data.frame((svytable(~clase.sub.hijos + m63_02, 
                                      elsoc_diseno_2, round = F))) %>% 
  group_by(m63_02) %>% 
  mutate(porcentaje=Freq/sum(Freq)) %>%
  drop_na()

g19.13 <- datos.grafico %>% 
  ggplot(aes(y = porcentaje, x = m63_02, fill = clase.sub.hijos, 
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .85, direction = -1, option = 'viridis') +
  #cambiar geom_text tal que: Stack y cambio colores
  geom_text(position = position_stack(vjust = .5),
            size= 2.75) + 
  theme(legend.position = 'top',
        legend.title = element_blank())

g19.13
```

```{r endeud-1retiro, echo=FALSE, fig.align='center', fig.cap='Sobrecarga de Deuda según Primer Retiro AFP'}
datos.grafico <- data.frame((svytable(~m43 + m63_02, 
                                      elsoc_diseno_2, round = F))) %>% 
  group_by(m63_02) %>% 
  mutate(porcentaje=Freq/sum(Freq)) %>%
  drop_na()

g19.14 <- datos.grafico %>% 
  ggplot(aes(y = porcentaje, x = m63_02, fill = m43, 
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .85, direction = -1, option = 'viridis') +
  #cambiar geom_text tal que: Stack y cambio colores
  geom_text(position = position_stack(vjust = .5),
            size= 2.75) + 
  theme(legend.position = 'top',
        legend.title = element_blank())

g19.14
```

```{r endeud-2retiro, echo=FALSE, fig.align='center', fig.cap='Sobrecarga de Deuda según Primer Retiro AFP'}
datos.grafico <- data.frame((svytable(~m43 + m63_03, 
                                      elsoc_diseno_2, round = F))) %>% 
  group_by(m63_03) %>% 
  mutate(porcentaje=Freq/sum(Freq)) %>%
  drop_na()

g19.15 <- datos.grafico %>% 
  ggplot(aes(y = porcentaje, x = m63_03, fill = m43, 
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .85, direction = -1, option = 'viridis') +
  #cambiar geom_text tal que: Stack y cambio colores
  geom_text(position = position_stack(vjust = .5),
            size= 2.75) + 
  theme(legend.position = 'top',
        legend.title = element_blank()) 
g19.15
```

```{r deuda-retiro1, fig.align='center',fig.cap="Primer retiro de AFP, según deuda"}
datos.01 <- data.frame((svytable(~deuda_01  + retiro1, elsoc_diseno_2, round = F))) %>% group_by(retiro1) %>% mutate(p_01=Freq/sum(Freq))
datos.01$retiro1 <- NULL
datos.02 <- data.frame((svytable(~deuda_02  + retiro1, elsoc_diseno_2, round = F))) %>% group_by(retiro1) %>% mutate(p_02=Freq/sum(Freq))
datos.02$retiro1 <- NULL
datos.03 <- data.frame((svytable(~deuda_03 + retiro1, elsoc_diseno_2, round = F))) %>% group_by(retiro1) %>% mutate(p_03=Freq/sum(Freq))
datos.03$retiro1 <- NULL
datos.04 <- data.frame((svytable(~deuda_04 + retiro1, elsoc_diseno_2, round = F))) %>% group_by(retiro1) %>% mutate(p_04=Freq/sum(Freq))

datos.grafico1<- cbind(datos.01, datos.02, datos.03, datos.04)

subset.grafico <- droplevels(subset(datos.grafico1,
                                      deuda_01 == 'Si' & 
                                      deuda_02== 'Si' &
                                      deuda_03 == 'Si' & 
                                      deuda_04 == 'Si'))
#trasponer según variable
datos.grafico <- subset.grafico %>% 
  pivot_longer(cols = starts_with('deuda_'))  %>%
  mutate(variable = factor(name, labels = c('Deuda Casa Comercial',
                     'Deuda Banco',
                     'Deuda Pariente',
                     'Otras Deudas'))) %>% 
  drop_na()

datos.grafico$porcentaje <- with(datos.grafico, case_when(
  variable == 'Deuda Casa Comercial' ~ p_01,
  variable == 'Deuda Banco' ~ p_02,
  variable == 'Deuda Pariente' ~ p_03,
  variable == 'Otras Deudas' ~ p_04))

#graficamos

g19.16 <-datos.grafico %>% 
  ggplot(aes(y = porcentaje, x = variable, fill = retiro1, 
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) +
  theme_bw() + 
  geom_col(position = "dodge2") +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1, option = 'viridis') + 
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75)  +
  theme(legend.position = 'top',
        legend.title = element_blank())

g19.16
```

```{r deuda-retiro2, fig.align='center',fig.cap="Segundo retiro de AFP, según deuda"}
datos.01 <- data.frame((svytable(~deuda_01  + retiro2, elsoc_diseno_2, round = F))) %>% group_by(retiro2) %>% mutate(p_01=Freq/sum(Freq))
datos.01$retiro2 <- NULL
datos.02 <- data.frame((svytable(~deuda_02  + retiro2, elsoc_diseno_2, round = F))) %>% group_by(retiro2) %>% mutate(p_02=Freq/sum(Freq))
datos.02$retiro2 <- NULL
datos.03 <- data.frame((svytable(~deuda_03 + retiro2, elsoc_diseno_2, round = F))) %>% group_by(retiro2) %>% mutate(p_03=Freq/sum(Freq))
datos.03$retiro2 <- NULL
datos.04 <- data.frame((svytable(~deuda_04 + retiro2, elsoc_diseno_2, round = F))) %>% group_by(retiro2) %>% mutate(p_04=Freq/sum(Freq))

datos.grafico1<- cbind(datos.01, datos.02, datos.03, datos.04)

subset.grafico <- droplevels(subset(datos.grafico1,
                                      deuda_01 == 'Si' & 
                                      deuda_02== 'Si' &
                                      deuda_03 == 'Si' & 
                                      deuda_04 == 'Si'))
#trasponer según variable
datos.grafico <- subset.grafico %>% 
  pivot_longer(cols = starts_with('deuda_'))  %>%
  mutate(variable = factor(name, labels = c('Deuda Casa Comercial',
                     'Deuda Banco',
                     'Deuda Pariente',
                     'Otras Deudas'))) %>% 
  drop_na()

datos.grafico$porcentaje <- with(datos.grafico, case_when(
  variable == 'Deuda Casa Comercial' ~ p_01,
  variable == 'Deuda Banco' ~ p_02,
  variable == 'Deuda Pariente' ~ p_03,
  variable == 'Otras Deudas' ~ p_04))

#graficamos

g19.17 <-datos.grafico %>% 
  ggplot(aes(y = porcentaje, x = variable, fill = retiro2, 
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) +
  theme_bw() + 
  geom_col(position = "dodge2") +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1, option = 'viridis') + 
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75)  +
  theme(legend.position = 'top',
        legend.title = element_blank())

g19.17
```

```{r deuda-benef, fig.align='center',fig.cap="Beneficios Estatales, según deuda"}
datos.01 <- data.frame((svytable(~deuda_01  + benef_estado, elsoc_diseno_2, round = F))) %>% group_by(benef_estado) %>% mutate(p_01=Freq/sum(Freq))
datos.01$benef_estado <- NULL
datos.02 <- data.frame((svytable(~deuda_02  + benef_estado, elsoc_diseno_2, round = F))) %>% group_by(benef_estado) %>% mutate(p_02=Freq/sum(Freq))
datos.02$benef_estado <- NULL
datos.03 <- data.frame((svytable(~deuda_03 + benef_estado, elsoc_diseno_2, round = F))) %>% group_by(benef_estado) %>% mutate(p_03=Freq/sum(Freq))
datos.03$benef_estado <- NULL
datos.04 <- data.frame((svytable(~deuda_04 + benef_estado, elsoc_diseno_2, round = F))) %>% group_by(benef_estado) %>% mutate(p_04=Freq/sum(Freq))

datos.grafico1<- cbind(datos.01, datos.02, datos.03, datos.04)

subset.grafico <- droplevels(subset(datos.grafico1,
                                      deuda_01 == 'Si' & 
                                      deuda_02== 'Si' &
                                      deuda_03 == 'Si' & 
                                      deuda_04 == 'Si'))
#trasponer según variable
datos.grafico <- subset.grafico %>% 
  pivot_longer(cols = starts_with('deuda_'))  %>%
  mutate(variable = factor(name, labels = c('Deuda Casa Comercial',
                     'Deuda Banco',
                     'Deuda Pariente',
                     'Otras Deudas'))) %>% 
  drop_na()

datos.grafico$porcentaje <- with(datos.grafico, case_when(
  variable == 'Deuda Casa Comercial' ~ p_01,
  variable == 'Deuda Banco' ~ p_02,
  variable == 'Deuda Pariente' ~ p_03,
  variable == 'Otras Deudas' ~ p_04))

#graficamos

g19.17 <-datos.grafico %>% 
  ggplot(aes(y = porcentaje, x = variable, fill = benef_estado, 
             label = as.character(scales::percent(porcentaje, accuracy = .1)))) +
  theme_bw() + 
  geom_col(position = "dodge2") +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1, option = 'viridis') + 
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size= 2.75)  +
  theme(legend.position = 'top',
        legend.title = element_blank())

g19.17
```

