--- 
title: "Estudio Longitudinal Social de Chile"
subtitle: "Resultados longitudinales 2016-2021"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: ["book.bib"]
csl: "inputs/bib/apa-no-ampersand.csl"
biblio-style: apalike
link-citations: yes
linkcolor: blue
geometry: "left=4cm, right=3cm, top=2.5cm, bottom=2.5cm"
fontsize: 12pt
linestretch: 1.5
toc-depth: 1
lof: True
lot: True
github-repo: "edgardo-cerda/reporte-elsoc-2021"
url: "https://edgardo-cerda.github.io/reporte-elsoc-2021/"
always_allow_html: true
editor_options: 
  markdown: 
    wrap: 72
    
---


```{r packages, message=FALSE, warning=FALSE, include=FALSE}

library(knitr)
library(kableExtra)
library(gridExtra)
library(tidyverse)
library(sjmisc)
library(sjlabelled)
library(ggrepel)
library(ggalluvial)
library(survey)
library(spatstat)
library(gtools)
library(sf)
library(chilemapas)
library(elsoc)
library(lubridate)
library(viridis)
library(treemapify)

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=FALSE, warning=FALSE, message=FALSE, echo=FALSE, fig.topcaption = TRUE, fig.align = 'center')

Sys.setlocale("LC_ALL","ES_ES.UTF-8")
```

```{r formats, include=FALSE }
table_format = if (is_html_output()) {
  "html"
} else if (is_latex_output()) {
  "latex" 
}

fullw = if (is_html_output()) {TRUE} else if (is_latex_output()) {FALSE}
fsize = if (is_html_output()) {14} else if(is_latex_output()) {8}

ggplot2::theme_set(new = theme_test(base_family = "serif"))
options(knitr.kable.NA = '')

```

```{r cargar-datos, eval=FALSE}

remove(list = ls())
# 
# load(file.path('..', '..', '..', '2_Bases_de_Datos', '10_Combinacion_de_Olas_ELSOC', '0E_Bases_de_Datos_Resultantes_2016_2021', 'ELSOC_Long_2016_2021_v1.00_R.RData'))
# 
# load(file.path('..', '..', '..', '2_Bases_de_Datos', '10_Combinacion_de_Olas_ELSOC', '0E_Bases_de_Datos_Resultantes_2016_2021', 'ELSOC_Wide_2016_2021_v1.00_R.RData'))

load(file.path('inputs', 'cuarentenas_acum.RData'))

```

```{r datos-elsoc}

# bases de datos ELSOC
elsoc::load_elsoc(format = 'long')
elsoc::load_elsoc(format = 'wide')

```

```{r datos-cuarentenas, eval=FALSE}

## DATA CUARENTENA ---------
# Url para descarga directa de datos desde el Github del Ministerio de Ciencia
url <- "https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output"

## Cuarentenas desde 2020/03 hasta 2020/07/28 
cuarentenas1_bruto <- readr::read_csv(paste(url, "producto29", "Cuarentenas-Totales.csv", sep = "/"))

cuarentenas1_acum <- cuarentenas1_bruto %>% 
  janitor::clean_names() %>% 
  mutate(fecha_de_inicio = as_date(fecha_de_inicio),
         fecha_de_termino = as_date(fecha_de_termino),
         # cortar en fecha 2020/07/27 
         fecha_de_termino = as_date(ifelse(fecha_de_termino > '2020/07/27', 
                                           make_date(2020, 07, 27),
                                           fecha_de_termino)),
         csum1 = as.numeric(fecha_de_termino - fecha_de_inicio, units = 'days')) %>% 
  filter(fecha_de_inicio < '2020/07/27') %>% 
  rename(comuna_cod = codigo_cut_comuna) %>%
  group_by(comuna_cod) %>% 
  summarise(csum1 = mean(csum1, na.rm = TRUE)) %>% 
  ungroup()

## Cuarentenas desde 2020/07/28 al último día actualizado
cuarentenas2_bruto <- read_csv(paste(url, 'producto74', "paso_a_paso_std.csv", sep="/"))

cuarentenas2 <- cuarentenas2_bruto %>% 
  janitor::clean_names() %>% 
  mutate(fecha = as_date(fecha),
         dia = weekdays(fecha),
         cuarentena = case_when(paso == 1 ~ 1,
                                paso == 2 & dia %in% c('Saturday', 'Sunday') ~ 1,
                                TRUE ~ 0)) %>% 
  filter(zona %in% c('Urbana', 'Total'))

# Cuarentena acumulada desde el 2020/07/27 a la fecha respectiva:
cuarentenas2_acum <- cuarentenas2 %>% 
  group_by(codigo_comuna, zona) %>% 
  mutate(csum2 = cumsum(cuarentena),
         comuna_cod = as.numeric(codigo_comuna)) %>% 
  ungroup() %>% 
  select(fecha, comuna_cod, csum2)

# Cuarentenas acumuladas por comuna y fecha desde inicio de las cuarentenas:
cuarentenas_acum <- full_join(cuarentenas1_acum,
                              cuarentenas2_acum,
                              by = 'comuna_cod') %>% 
  rowwise() %>% 
  mutate(cuarentena_acum = sum(csum1, csum2, na.rm = TRUE)) %>% 
  select(comuna_cod, fecha, cuarentena_acum) %>%
  # Cuarentenas acumuladas en ventanas de tiempo
  arrange(comuna_cod, fecha) %>% 
  group_by(comuna_cod) %>% 
  mutate(cuarentena_acum.14 = cuarentena_acum - dplyr::lag(cuarentena_acum, n = 14),
         cuarentena_acum.30 = cuarentena_acum - dplyr::lag(cuarentena_acum, n = 30),
         cuarentena_acum.60 = cuarentena_acum - dplyr::lag(cuarentena_acum, n = 60),
         cuarentena_acum.90 = cuarentena_acum - dplyr::lag(cuarentena_acum, n = 90)
         )

### Pegar fechas de cuarentenas en distintas ventanas de tiempo a datos elsoc:
elsoc_long_cuarentenas <- elsoc_long_2016_2021 %>% 
  filter(ola == 5) %>% 
  mutate(fecha = make_date(year = annio_entr, month = mes_entr, day = dia_entr)) %>% 
  left_join(cuarentenas_acum, by = c('comuna_cod', 'fecha')) %>% 
  select(idencuesta, ola, starts_with('cuarentena_acum'))

```


```{r remover-datos-sin-uso}

rm(list = setdiff(ls(), c('elsoc_long_cuarentenas', 'elsoc_long_2016_2021', 'elsoc_wide_2016_2021')))

```
