## Movimientos Sociales y Acciones Colectivas

### Tipología de participación política

```{r tip-participacion}

# tip_par <- elsoc_wide_2016_2021[c("idencuesta", "c11_w01", "c11_w03", "c43_w05", "c08_02_w02", "c08_02_w03", "c08_02_w04")]
# 
# #Crear variables donde 2 es si participa a veces, frecuentemente o muy frecuentemente.
# tip_par$par_mov_w02<-1
# tip_par$par_mov_w02[tip_par$c08_02_w02>=3]<-2
# tip_par$par_mov_w03<-1
# tip_par$par_mov_w03[tip_par$c08_02_w03>=3]<-2
# tip_par$par_mov_w04<-1
# tip_par$par_mov_w04[tip_par$c08_02_w04>=3]<-2
#    
# tip_par$c11_w01[tip_par$c11_w01<=0 | tip_par$c11_w01==3]<-NA
# tip_par$c11_w03[tip_par$c11_w03<=0 | tip_par$c11_w03==3]<-NA
# tip_par$c43_w05[tip_par$c43_w05<=0 | tip_par$c43_w05==3]<-NA
# 
# tip_par <- tip_par %>%
# drop_na(c("c11_w01", "c11_w03", "c43_w05", "c08_02_w02", "c08_02_w03", "c08_02_w04"))
# 
# var <- cbind(c11_w01, c11_w03, c43_w05, par_mov_w02, par_mov_w03, par_mov_w04)~1
# 
# library(poLCA)
# tipos_part3 <- poLCA(var, tip_par, nclass=3, na.rm = T, maxiter = 5000, nrep=10)
# tip_par$class_part_3<- as.factor(tipos_part3$predclass)
# tabpart_3<-table(tip_par$class_part_3)
# tabpart_3
# prop.table(tabpart_3)
#  
# tipos_part4 <- poLCA(var, tip_par, nclass=4, na.rm = T, maxiter = 5000, nrep=10)
# tip_par$class_part_4<- as.factor(tipos_part4$predclass)
# tabpart_4<-table(tip_par$class_part_4)
# tabpart_4
# prop.table(tabpart_4)
#  
# tipos_part5 <- poLCA(var, tip_par, nclass=5, na.rm = T, maxiter = 5000, nrep=10)
# tip_par$class_part_5<- as.factor(tipos_part5$predclass)
# tabpart_5<-table(tip_par$class_part_5)
# tabpart_5
# prop.table(tabpart_5)
# 
# #Guardar base especial.
# write.csv(tip_par, file="participacion_tipos4.csv", row.names = F, fileEncoding = "UTF-8")

#Gráfico 3 clases.
tip_par<-read.csv("participacion_tipos4.csv", sep=",", encoding="UTF-8")
tip_par <- tip_par[c("idencuesta", "class_part_3", "par_mov_w02", "par_mov_w03", "par_mov_w04")]
tip_par <- merge(tip_par, elsoc_wide_2016_2021, by="idencuesta") %>%
  survey_design_elsoc(weights = 'ponderador02_w05')
#tabpart_3<-table(tip_par$class_part_3)
#tabpart_3
#prop.table(tabpart_3)
tab1 <- tip_par %>% group_by(class_part_3, c11_w01) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 1) %>% rename(Clase=class_part_3, Participa=c11_w01)
tab2 <- tip_par %>% group_by(class_part_3, c11_w03) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 2) %>% rename(Clase=class_part_3, Participa=c11_w03)
tab3 <- tip_par %>% group_by(class_part_3, c43_w05) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 3) %>% rename(Clase=class_part_3, Participa=c43_w05)
tab5 <- tip_par %>% group_by(class_part_3, par_mov_w02) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 4) %>% rename(Clase=class_part_3, Participa=par_mov_w02)
tab6 <- tip_par %>% group_by(class_part_3, par_mov_w03) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 5) %>% rename(Clase=class_part_3, Participa=par_mov_w03)
tab7 <- tip_par %>% group_by(class_part_3, par_mov_w04) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 6) %>% rename(Clase=class_part_3, Participa=par_mov_w04)

tab_3 <- rbind(tab1, tab2, tab3, tab5, tab6, tab7)
rm(tab1, tab2, tab3, tab5, tab6, tab7)

tab_3$Clase  <- factor(tab_3$Clase, levels = c(1,2,3), labels = c("(16.84%)", "(53.03%)", "(30.13%)"))
tab_3$Participa  <- factor(tab_3$Participa, levels = c(1,2), labels = c("No participa", "Participa"))
tab_3$var  <- factor(tab_3$var, levels = c(1,2,3,4,5,6), labels = c("Elección 2013", "Elección 2017", "Plebiscito", "Marcha W2", "Marcha W3", "Marcha W4"))

tab_3 %>% 
  ggplot(aes(x = freq, y = var, fill = Participa)) + 
  geom_bar(stat = 'identity', position = 'stack') + 
  facet_grid(~ Clase) +
  labs(y="Evento", x="Proporción",
       title = "Perfiles de participación: 3 clases", fill = "") +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 5), limits=c(0, 1)) +
  theme_bw() + scale_fill_viridis_d(end = .85, option = 'viridis') +
  theme(axis.text.x = element_text(size = rel(.9)),
        legend.position = 'top',
        legend.title = element_blank())

#Gráfico 4 clases.
tip_par<-read.csv("participacion_tipos4.csv", sep=",", encoding="UTF-8")
tip_par <- tip_par[c("idencuesta", "class_part_4","par_mov_w02", "par_mov_w03", "par_mov_w04")]
tip_par <- merge(tip_par, elsoc_wide_2016_2021, by="idencuesta") %>%
  survey_design_elsoc(weights = 'ponderador02_w05')
#tabpart_4<-table(tip_par$class_part_4)
# tabpart_4
# prop.table(tabpart_4)
tab1 <- tip_par %>% group_by(class_part_4, c11_w01) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 1) %>% rename(Clase=class_part_4, Participa=c11_w01)
tab2 <- tip_par %>% group_by(class_part_4, c11_w03) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 2) %>% rename(Clase=class_part_4, Participa=c11_w03)
tab3 <- tip_par %>% group_by(class_part_4, c43_w05) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 3) %>% rename(Clase=class_part_4, Participa=c43_w05)
tab5 <- tip_par %>% group_by(class_part_4, par_mov_w02) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 4) %>% rename(Clase=class_part_4, Participa=par_mov_w02)
tab6 <- tip_par %>% group_by(class_part_4, par_mov_w03) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 5) %>% rename(Clase=class_part_4, Participa=par_mov_w03)
tab7 <- tip_par %>% group_by(class_part_4, par_mov_w04) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 6) %>% rename(Clase=class_part_4, Participa=par_mov_w04)

tab_4<- rbind(tab1, tab2, tab3, tab5, tab6, tab7)
rm(tab1, tab2, tab3, tab5, tab6, tab7)

tab_4$Clase  <- factor(tab_4$Clase, levels = c(1,2,3,4), labels = c("(4.43%)", "(27.61%)", "(60.74%)", "(7.23%)"))
tab_4$Participa  <- factor(tab_4$Participa, levels = c(1,2), labels = c("No participa", "Participa"))
tab_4$var  <- factor(tab_4$var, levels = c(1,2,3,4,5,6), labels = c("Elección 2013", "Elección 2017", "Plebiscito", "Marcha W2", "Marcha W3", "Marcha W4"))

tab_4 %>% 
  ggplot(aes(x = freq, y = var, fill = Participa)) + 
  geom_bar(stat = 'identity', position = 'stack') + 
  facet_grid(~ Clase) +
  labs(y="Evento", x="Proporción",
       title = "Perfiles de participación: 4 clases", fill = "") +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 5), limits=c(0, 1)) +
  theme_bw() + scale_fill_viridis_d(end = .85, option = 'viridis') +
  theme(axis.text.x = element_text(size = rel(.9)),
        legend.position = 'top',
        legend.title = element_blank())

#Gráfico 5 clases.
tip_par<-read.csv("participacion_tipos4.csv", sep=",", encoding="UTF-8")
tip_par <- tip_par[c("idencuesta", "class_part_5", "par_mov_w02", "par_mov_w03", "par_mov_w04")]
tip_par <- merge(tip_par, elsoc_wide_2016_2021, by="idencuesta") %>%
  survey_design_elsoc(weights = 'ponderador02_w05')
#tabpart_5<-table(tip_par$class_part_5)
# tabpart_5
# prop.table(tabpart_5)
tab1 <- tip_par %>% group_by(class_part_5, c11_w01) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 1) %>% rename(Clase=class_part_5, Participa=c11_w01)
tab2 <- tip_par %>% group_by(class_part_5, c11_w03) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 2) %>% rename(Clase=class_part_5, Participa=c11_w03)
tab3 <- tip_par %>% group_by(class_part_5, c43_w05) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 3) %>% rename(Clase=class_part_5, Participa=c43_w05)
tab5 <- tip_par %>% group_by(class_part_5, par_mov_w02) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 4) %>% rename(Clase=class_part_5, Participa=par_mov_w02)
tab6 <- tip_par %>% group_by(class_part_5, par_mov_w03) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 5) %>% rename(Clase=class_part_5, Participa=par_mov_w03)
tab7 <- tip_par %>% group_by(class_part_5, par_mov_w04) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 6) %>% rename(Clase=class_part_5, Participa=par_mov_w04)

tab_5<- rbind(tab1, tab2, tab3, tab5, tab6, tab7)
rm(tab1, tab2, tab3, tab5, tab6, tab7)

tab_5$Clase  <- factor(tab_5$Clase, levels = c(1,2,3,4,5), labels = c("(47.03%)", "(27.81%)", "(5.45%)", "(27.38%)", "(2.32%)"))
tab_5$Participa  <- factor(tab_5$Participa, levels = c(1,2), labels = c("No participa", "Participa"))
tab_5$var  <- factor(tab_5$var, levels = c(1,2,3,4,5,6), labels = c("Elección 2013", "Elección 2017", "Plebiscito", "Marcha W2", "Marcha W3", "Marcha W4"))

tab_5 %>% 
  ggplot(aes(x = freq, y = var, fill = Participa)) + 
  geom_bar(stat = 'identity', position = 'stack') + facet_grid(~ Clase) +
  labs(y="Evento", x="Proporción",
       title = "Perfiles de participación: 5 clases", fill = "") +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 5), limits=c(0, 1)) +
  theme_bw() + scale_fill_viridis_d(end = .85, option = 'viridis') +
  theme(axis.text.x = element_text(size = rel(.9)),
        legend.position = 'top',
        legend.title = element_blank())
rm(tab_3, tab_4, tab_5, tip_par)

```

```{r tip-participacion}

# tip_par <- elsoc_wide_2016_2021[c("idencuesta", "c11_w01", "c11_w03", "c43_w05", "c08_02_w01", "c08_02_w02", "c08_02_w03", "c08_02_w04","c08_02_w05")]
# 
# #Crear variables donde 2 es si participa frecuentemente o muy frecuentemente.
# tip_par$par_mov_w01<-1
# tip_par$par_mov_w01[tip_par$c08_02_w01>=4]<-2
# tip_par$par_mov_w02<-1
# tip_par$par_mov_w02[tip_par$c08_02_w02>=4]<-2
# tip_par$par_mov_w03<-1
# tip_par$par_mov_w03[tip_par$c08_02_w03>=4]<-2
# tip_par$par_mov_w04<-1
# tip_par$par_mov_w04[tip_par$c08_02_w04>=4]<-2
# tip_par$par_mov_w05<-1
# tip_par$par_mov_w05[tip_par$c08_02_w05>=4]<-2
#   
# tip_par$c11_w01[tip_par$c11_w01<=0 | tip_par$c11_w01==3]<-NA
# tip_par$c11_w03[tip_par$c11_w03<=0 | tip_par$c11_w03==3]<-NA
# tip_par$c43_w05[tip_par$c43_w05<=0 | tip_par$c43_w05==3]<-NA
# 
# tip_par <- tip_par %>%
# drop_na(c("c11_w01", "c11_w03", "c43_w05", "c08_02_w01", "c08_02_w02", "c08_02_w03", "c08_02_w04","c08_02_w05"))
# 
# var <- cbind(c11_w01, c11_w03, c43_w05, par_mov_w01, par_mov_w02, par_mov_w03, par_mov_w04, par_mov_w05)~1
# 
# library(poLCA)
# tipos_part3 <- poLCA(var, tip_par, nclass=3, na.rm = T, maxiter = 5000, nrep=10)
# tip_par$class_part_3<- as.factor(tipos_part3$predclass)
# tabpart_3<-table(tip_par$class_part_3)
# tabpart_3
# prop.table(tabpart_3)
#  
# tipos_part4 <- poLCA(var, tip_par, nclass=4, na.rm = T, maxiter = 5000, nrep=10)
# tip_par$class_part_4<- as.factor(tipos_part4$predclass)
# tabpart_4<-table(tip_par$class_part_4)
# tabpart_4
# prop.table(tabpart_4)
# 
# tipos_part5 <- poLCA(var, tip_par, nclass=5, na.rm = T, maxiter = 5000, nrep=10)
# tip_par$class_part_5<- as.factor(tipos_part5$predclass)
# tabpart_5<-table(tip_par$class_part_5)
# tabpart_5
# prop.table(tabpart_5)
#  
# #Guardar base especial.
# write.csv(tip_par, file="participacion_tipos2.csv", row.names = F, fileEncoding = "UTF-8")

#Gráfico 3 clases.
tip_par<-read.csv("participacion_tipos2.csv", sep=",", encoding="UTF-8")
tip_par <- tip_par[c("idencuesta", "class_part_3", "par_mov_w01", "par_mov_w02", "par_mov_w03", "par_mov_w04", "par_mov_w05")]
tip_par <- merge(tip_par, elsoc_wide_2016_2021, by="idencuesta") %>%
  survey_design_elsoc(weights = 'ponderador02_w05')
#tabpart_3<-table(tip_par$class_part_3)
#tabpart_3
#prop.table(tabpart_3)
tab1 <- tip_par %>% group_by(class_part_3, c11_w01) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 1) %>% rename(Clase=class_part_3, Participa=c11_w01)
tab2 <- tip_par %>% group_by(class_part_3, c11_w03) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 2) %>% rename(Clase=class_part_3, Participa=c11_w03)
tab3 <- tip_par %>% group_by(class_part_3, c43_w05) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 3) %>% rename(Clase=class_part_3, Participa=c43_w05)
tab4 <- tip_par %>% group_by(class_part_3, par_mov_w01) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 4) %>% rename(Clase=class_part_3, Participa=par_mov_w01)
tab5 <- tip_par %>% group_by(class_part_3, par_mov_w02) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 5) %>% rename(Clase=class_part_3, Participa=par_mov_w02)
tab6 <- tip_par %>% group_by(class_part_3, par_mov_w03) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 6) %>% rename(Clase=class_part_3, Participa=par_mov_w03)
tab7 <- tip_par %>% group_by(class_part_3, par_mov_w04) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 7) %>% rename(Clase=class_part_3, Participa=par_mov_w04)
tab8 <- tip_par %>% group_by(class_part_3, par_mov_w05) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 8) %>% rename(Clase=class_part_3, Participa=par_mov_w05)

tab_3 <- rbind(tab1, tab2, tab3, tab4, tab5, tab6, tab7, tab8)
rm(tab1, tab2, tab3, tab4, tab5, tab6, tab7, tab8)

tab_3$Clase  <- factor(tab_3$Clase, levels = c(1,2,3), labels = c("(26.99%)", "(2.93%)", "(70.07%)"))
tab_3$Participa  <- factor(tab_3$Participa, levels = c(1,2), labels = c("No participa", "Participa"))
tab_3$var  <- factor(tab_3$var, levels = c(1,2,3,4,5,6,7,8), labels = c("Elección 2013", "Elección 2017", "Plebiscito", "Marcha W1", "Marcha W2", "Marcha W3", "Marcha W4", "Marcha W5"))

tab_3 %>% 
  ggplot(aes(x = freq, y = var, fill = Participa)) + 
  geom_bar(stat = 'identity', position = 'stack') + 
  facet_grid(~ Clase) +
  labs(y="Evento", x="Proporción",
       title = "Perfiles de participación: 3 clases", fill = "") +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 5), limits=c(0, 1)) +
  theme_bw() + scale_fill_viridis_d(end = .85, option = 'viridis') +
  theme(axis.text.x = element_text(size = rel(.9)),
        legend.position = 'top',
        legend.title = element_blank())

#Gráfico 4 clases.
tip_par<-read.csv("participacion_tipos2.csv", sep=",", encoding="UTF-8")
tip_par <- tip_par[c("idencuesta", "class_part_4", "par_mov_w01", "par_mov_w02", "par_mov_w03", "par_mov_w04", "par_mov_w05")]
tip_par <- merge(tip_par, elsoc_wide_2016_2021, by="idencuesta") %>%
  survey_design_elsoc(weights = 'ponderador02_w05')
#tabpart_4<-table(tip_par$class_part_4)
# tabpart_4
# prop.table(tabpart_4)
tab1 <- tip_par %>% group_by(class_part_4, c11_w01) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 1) %>% rename(Clase=class_part_4, Participa=c11_w01)
tab2 <- tip_par %>% group_by(class_part_4, c11_w03) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 2) %>% rename(Clase=class_part_4, Participa=c11_w03)
tab3 <- tip_par %>% group_by(class_part_4, c43_w05) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 3) %>% rename(Clase=class_part_4, Participa=c43_w05)
tab4 <- tip_par %>% group_by(class_part_4, par_mov_w01) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 4) %>% rename(Clase=class_part_4, Participa=par_mov_w01)
tab5 <- tip_par %>% group_by(class_part_4, par_mov_w02) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 5) %>% rename(Clase=class_part_4, Participa=par_mov_w02)
tab6 <- tip_par %>% group_by(class_part_4, par_mov_w03) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 6) %>% rename(Clase=class_part_4, Participa=par_mov_w03)
tab7 <- tip_par %>% group_by(class_part_4, par_mov_w04) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 7) %>% rename(Clase=class_part_4, Participa=par_mov_w04)
tab8 <- tip_par %>% group_by(class_part_4, par_mov_w05) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 8) %>% rename(Clase=class_part_4, Participa=par_mov_w05)

tab_4<- rbind(tab1, tab2, tab3, tab4, tab5, tab6, tab7, tab8)
rm(tab1, tab2, tab3, tab4, tab5, tab6, tab7, tab8)

tab_4$Clase  <- factor(tab_4$Clase, levels = c(1,2,3,4), labels = c("Desafectados (51.87%)", "Movilizados (2.73%)", "Institucionales (16.02%)", "Reclutados Pleb. (29.38%)"))
tab_4$Participa  <- factor(tab_4$Participa, levels = c(1,2), labels = c("No participa", "Participa"))
tab_4$var  <- factor(tab_4$var, levels = c(1,2,3,4,5,6,7,8), labels = c("Elección 2013", "Elección 2017", "Plebiscito", "Marcha W1", "Marcha W2", "Marcha W3", "Marcha W4", "Marcha W5"))

tab_4 %>% 
  ggplot(aes(x = freq, y = var, fill = Participa)) + 
  geom_bar(stat = 'identity', position = 'stack') + 
  facet_grid(~ Clase) +
  labs(y="Evento", x="Proporción",
       title = "Perfiles de participación: 4 clases", fill = "") +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 5), limits=c(0, 1)) +
  theme_bw() + scale_fill_viridis_d(end = .85, option = 'viridis') +
  theme(axis.text.x = element_text(size = rel(.9)),
        legend.position = 'top',
        legend.title = element_blank())

#Gráfico 5 clases.
tip_par<-read.csv("participacion_tipos2.csv", sep=",", encoding="UTF-8")
tip_par <- tip_par[c("idencuesta", "class_part_5", "par_mov_w01", "par_mov_w02", "par_mov_w03", "par_mov_w04", "par_mov_w05")]
tip_par <- merge(tip_par, elsoc_wide_2016_2021, by="idencuesta") %>%
  survey_design_elsoc(weights = 'ponderador02_w05')
#tabpart_5<-table(tip_par$class_part_5)
# tabpart_5
# prop.table(tabpart_5)
tab1 <- tip_par %>% group_by(class_part_5, c11_w01) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 1) %>% rename(Clase=class_part_5, Participa=c11_w01)
tab2 <- tip_par %>% group_by(class_part_5, c11_w03) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 2) %>% rename(Clase=class_part_5, Participa=c11_w03)
tab3 <- tip_par %>% group_by(class_part_5, c43_w05) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 3) %>% rename(Clase=class_part_5, Participa=c43_w05)
tab4 <- tip_par %>% group_by(class_part_5, par_mov_w01) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 4) %>% rename(Clase=class_part_5, Participa=par_mov_w01)
tab5 <- tip_par %>% group_by(class_part_5, par_mov_w02) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 5) %>% rename(Clase=class_part_5, Participa=par_mov_w02)
tab6 <- tip_par %>% group_by(class_part_5, par_mov_w03) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 6) %>% rename(Clase=class_part_5, Participa=par_mov_w03)
tab7 <- tip_par %>% group_by(class_part_5, par_mov_w04) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 7) %>% rename(Clase=class_part_5, Participa=par_mov_w04)
tab8 <- tip_par %>% group_by(class_part_5, par_mov_w05) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 8) %>% rename(Clase=class_part_5, Participa=par_mov_w05)

tab_5<- rbind(tab1, tab2, tab3, tab4, tab5, tab6, tab7, tab8)
rm(tab1, tab2, tab3, tab4, tab5, tab6, tab7, tab8)

tab_5$Clase  <- factor(tab_5$Clase, levels = c(1,2,3,4,5), labels = c("(1.57%)", "(24.27%)", "(56.78%)", "(16.02%)", "(1.36%)"))
tab_5$Participa  <- factor(tab_5$Participa, levels = c(1,2), labels = c("No participa", "Participa"))
tab_5$var  <- factor(tab_5$var, levels = c(1,2,3,4,5,6,7,8), labels = c("Elección 2013", "Elección 2017", "Plebiscito", "Marcha W1", "Marcha W2", "Marcha W3", "Marcha W4", "Marcha W5"))

tab_5 %>% 
  ggplot(aes(x = freq, y = var, fill = Participa)) + 
  geom_bar(stat = 'identity', position = 'stack') + facet_grid(~ Clase) +
  labs(y="Evento", x="Proporción",
       title = "Perfiles de participación: 5 clases", fill = "") +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 5), limits=c(0, 1)) +
  theme_bw() + scale_fill_viridis_d(end = .85, option = 'viridis') +
  theme(axis.text.x = element_text(size = rel(.9)),
        legend.position = 'top',
        legend.title = element_blank())
rm(tab_3, tab_4, tab_5, tip_par)

```

```{r tip-participacion}

# tip_par <- elsoc_wide_2016_2021[c("idencuesta", "c11_w01", "c11_w03", "c43_w05", "c08_01_w01", "c08_02_w01", "c08_03_w01", "c08_04_w01",  "c08_01_w02", "c08_02_w02", "c08_03_w02", "c08_04_w02", "c08_01_w03", "c08_02_w03", "c08_03_w03", "c08_04_w03", "c08_01_w04", "c08_02_w04", "c08_03_w04", "c08_04_w04", "c08_05_w04", "c08_02_w05", "c08_04_w05", "c08_05_w05")]
# 
# #Crear variables donde 2 es si participa frecuentemente o muy frecuentemente.
# tip_par$par_mov_w01<-1
# tip_par$par_mov_w01[tip_par$c08_01_w01>=4 | tip_par$c08_02_w01>=4 | tip_par$c08_03_w01>=4 | tip_par$c08_04_w01>=4]<-2
# tip_par$par_mov_w02<-1
# tip_par$par_mov_w02[tip_par$c08_01_w02>=4 | tip_par$c08_02_w02>=4 | tip_par$c08_03_w02>=4 | tip_par$c08_04_w02>=4]<-2
# tip_par$par_mov_w03<-1
# tip_par$par_mov_w03[tip_par$c08_01_w03>=4 | tip_par$c08_02_w03>=4 | tip_par$c08_03_w03>=4 | tip_par$c08_04_w03>=4]<-2
# tip_par$par_mov_w04<-1
# tip_par$par_mov_w04[tip_par$c08_01_w04>=4 | tip_par$c08_02_w04>=4 | tip_par$c08_03_w04>=4 | tip_par$c08_04_w04>=4 | tip_par$c08_05_w04>=4]<-2
# tip_par$par_mov_w05<-1
# tip_par$par_mov_w05[tip_par$c08_02_w05>=4 | tip_par$c08_04_w05>=4 | tip_par$c08_05_w05>=4]<-2
#  
# tip_par$c11_w01[tip_par$c11_w01<=0 | tip_par$c11_w01==3]<-NA
# tip_par$c11_w03[tip_par$c11_w03<=0 | tip_par$c11_w03==3]<-NA
# tip_par$c43_w05[tip_par$c43_w05<=0 | tip_par$c43_w05==3]<-NA
# 
# tip_par <- tip_par %>%
# drop_na(c("c11_w01", "c11_w03", "c43_w05", "c08_01_w01", "c08_02_w01", "c08_03_w01", "c08_04_w01",  "c08_01_w02", "c08_02_w02", "c08_03_w02", "c08_04_w02", "c08_01_w03", "c08_02_w03", "c08_03_w03", "c08_04_w03", "c08_01_w04", "c08_02_w04", "c08_03_w04", "c08_04_w04", "c08_05_w04", "c08_02_w05", "c08_04_w05", "c08_05_w05"))
# 
# var <- cbind(c11_w01, c11_w03, c43_w05, par_mov_w01, par_mov_w02, par_mov_w03, par_mov_w04, par_mov_w05)~1
# 
# library(poLCA)
# tipos_part3 <- poLCA(var, tip_par, nclass=3, na.rm = T, maxiter = 5000, nrep=10)
# tip_par$class_part_3<- as.factor(tipos_part3$predclass)
#  
# tipos_part4 <- poLCA(var, tip_par, nclass=4, na.rm = T, maxiter = 5000, nrep=10)
# tip_par$class_part_4<- as.factor(tipos_part4$predclass)
# 
# tipos_part5 <- poLCA(var, tip_par, nclass=5, na.rm = T, maxiter = 5000, nrep=10)
# tip_par$class_part_5<- as.factor(tipos_part5$predclass)
#  
# #Guardar base especial.
# write.csv(tip_par, file="participacion_tipos.csv", row.names = F, fileEncoding = "UTF-8")

# #Gráfico 3 clases.
# tip_par<-read.csv("participacion_tipos.csv", sep=",", encoding="UTF-8")
# tip_par <- tip_par[c("idencuesta", "class_part_3", "par_mov_w01", "par_mov_w02", "par_mov_w03", "par_mov_w04", "par_mov_w05")]
# tip_par <- merge(tip_par, elsoc_wide_2016_2021, by="idencuesta") %>%
#   survey_design_elsoc(weights = 'ponderador02_w05')
# #tabpart_3<-table(tip_par$class_part_3)
# #tabpart_3
# #prop.table(tabpart_3)
# tab1 <- tip_par %>% group_by(class_part_3, c11_w01) %>%
#   summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
#   mutate(var = 1) %>% rename(Clase=class_part_3, Participa=c11_w01)
# tab2 <- tip_par %>% group_by(class_part_3, c11_w03) %>%
#   summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
#   mutate(var = 2) %>% rename(Clase=class_part_3, Participa=c11_w03)
# tab3 <- tip_par %>% group_by(class_part_3, c43_w05) %>%
#   summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
#   mutate(var = 3) %>% rename(Clase=class_part_3, Participa=c43_w05)
# tab4 <- tip_par %>% group_by(class_part_3, par_mov_w01) %>%
#   summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
#   mutate(var = 4) %>% rename(Clase=class_part_3, Participa=par_mov_w01)
# tab5 <- tip_par %>% group_by(class_part_3, par_mov_w02) %>%
#   summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
#   mutate(var = 5) %>% rename(Clase=class_part_3, Participa=par_mov_w02)
# tab6 <- tip_par %>% group_by(class_part_3, par_mov_w03) %>%
#   summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
#   mutate(var = 6) %>% rename(Clase=class_part_3, Participa=par_mov_w03)
# tab7 <- tip_par %>% group_by(class_part_3, par_mov_w04) %>%
#   summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
#   mutate(var = 7) %>% rename(Clase=class_part_3, Participa=par_mov_w04)
# tab8 <- tip_par %>% group_by(class_part_3, par_mov_w05) %>%
#   summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
#   mutate(var = 8) %>% rename(Clase=class_part_3, Participa=par_mov_w05)
# 
# tab_3 <- rbind(tab1, tab2, tab3, tab4, tab5, tab6, tab7, tab8)
# rm(tab1, tab2, tab3, tab4, tab5, tab6, tab7, tab8)
# 
# tab_3$Clase  <- factor(tab_3$Clase, levels = c(1,2,3), labels = c("(27.88%)", "(53.92%)", "(18.2%)"))
# tab_3$Participa  <- factor(tab_3$Participa, levels = c(1,2), labels = c("No participa", "Participa"))
# tab_3$var  <- factor(tab_3$var, levels = c(1,2,3,4,5,6,7,8), labels = c("Elección 2013", "Elección 2017", "Plebiscito", "Protesta W1", "Protesta W2", "Protesta W3", "Protesta W4", "Protesta W5"))
# 
# tab_3 %>% 
#   ggplot(aes(x = freq, y = var, fill = Participa)) + 
#   geom_bar(stat = 'identity', position = 'stack') + 
#   facet_grid(~ Clase) +
#   labs(y="Evento", x="Proporción",
#        title = "Perfiles de participación: 3 clases", fill = "") +
#   scale_x_continuous(breaks = scales::pretty_breaks(n = 5), limits=c(0, 1)) +
#   theme_bw() + 
#   theme(legend.position = "top", plot.title = element_text(size=14))  + 
#   scale_fill_viridis_d(begin = .33, end = .66, direction = -1, option = 'viridis')
# 
# #Gráfico 4 clases.
# tip_par<-read.csv("participacion_tipos.csv", sep=",", encoding="UTF-8")
# tip_par <- tip_par[c("idencuesta", "class_part_4", "par_mov_w01", "par_mov_w02", "par_mov_w03", "par_mov_w04", "par_mov_w05")]
# tip_par <- merge(tip_par, elsoc_wide_2016_2021, by="idencuesta") %>%
#   survey_design_elsoc(weights = 'ponderador02_w05')
# #tabpart_4<-table(tip_par$class_part_4)
# # tabpart_4
# # prop.table(tabpart_4)
# tab1 <- tip_par %>% group_by(class_part_4, c11_w01) %>%
#   summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
#   mutate(var = 1) %>% rename(Clase=class_part_4, Participa=c11_w01)
# tab2 <- tip_par %>% group_by(class_part_4, c11_w03) %>%
#   summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
#   mutate(var = 2) %>% rename(Clase=class_part_4, Participa=c11_w03)
# tab3 <- tip_par %>% group_by(class_part_4, c43_w05) %>%
#   summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
#   mutate(var = 3) %>% rename(Clase=class_part_4, Participa=c43_w05)
# tab4 <- tip_par %>% group_by(class_part_4, par_mov_w01) %>%
#   summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
#   mutate(var = 4) %>% rename(Clase=class_part_4, Participa=par_mov_w01)
# tab5 <- tip_par %>% group_by(class_part_4, par_mov_w02) %>%
#   summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
#   mutate(var = 5) %>% rename(Clase=class_part_4, Participa=par_mov_w02)
# tab6 <- tip_par %>% group_by(class_part_4, par_mov_w03) %>%
#   summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
#   mutate(var = 6) %>% rename(Clase=class_part_4, Participa=par_mov_w03)
# tab7 <- tip_par %>% group_by(class_part_4, par_mov_w04) %>%
#   summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
#   mutate(var = 7) %>% rename(Clase=class_part_4, Participa=par_mov_w04)
# tab8 <- tip_par %>% group_by(class_part_4, par_mov_w05) %>%
#   summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
#   mutate(var = 8) %>% rename(Clase=class_part_4, Participa=par_mov_w05)
# 
# tab_4<- rbind(tab1, tab2, tab3, tab4, tab5, tab6, tab7, tab8)
# rm(tab1, tab2, tab3, tab4, tab5, tab6, tab7, tab8)
# 
# tab_4$Clase  <- factor(tab_4$Clase, levels = c(1,2,3,4), labels = c("Movilizados (16.77%)", "Desafectados (58.9%)", "Reclutados (4.84%)", "Institucionales (19.5%)"))
# tab_4$Participa  <- factor(tab_4$Participa, levels = c(1,2), labels = c("No participa", "Participa"))
# tab_4$var  <- factor(tab_4$var, levels = c(1,2,3,4,5,6,7,8), labels = c("Elección 2013", "Elección 2017", "Plebiscito", "Protesta W1", "Protesta W2", "Protesta W3", "Protesta W4", "Protesta W5"))
# 
# tab_4 %>% 
#   ggplot(aes(x = freq, y = var, fill = Participa)) + 
#   geom_bar(stat = 'identity', position = 'stack') + 
#   facet_grid(~ Clase) +
#   labs(y="Evento", x="Proporción",
#        title = "Perfiles de participación: 4 clases", fill = "") +
#   scale_x_continuous(breaks = scales::pretty_breaks(n = 5), limits=c(0, 1)) +
#   theme_bw() + theme(legend.position = "top", 
#                      plot.title = element_text(size=14))  + 
#   scale_fill_viridis_d(begin = .33, end = .66, direction = -1, option = 'viridis')
# 
# #Gráfico 5 clases.
# tip_par<-read.csv("participacion_tipos.csv", sep=",", encoding="UTF-8")
# tip_par <- tip_par[c("idencuesta", "class_part_5", "par_mov_w01", "par_mov_w02", "par_mov_w03", "par_mov_w04", "par_mov_w05")]
# tip_par <- merge(tip_par, elsoc_wide_2016_2021, by="idencuesta") %>%
#   survey_design_elsoc(weights = 'ponderador02_w05')
# #tabpart_5<-table(tip_par$class_part_5)
# # tabpart_5
# # prop.table(tabpart_5)
# tab1 <- tip_par %>% group_by(class_part_5, c11_w01) %>%
#   summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
#   mutate(var = 1) %>% rename(Clase=class_part_5, Participa=c11_w01)
# tab2 <- tip_par %>% group_by(class_part_5, c11_w03) %>%
#   summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
#   mutate(var = 2) %>% rename(Clase=class_part_5, Participa=c11_w03)
# tab3 <- tip_par %>% group_by(class_part_5, c43_w05) %>%
#   summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
#   mutate(var = 3) %>% rename(Clase=class_part_5, Participa=c43_w05)
# tab4 <- tip_par %>% group_by(class_part_5, par_mov_w01) %>%
#   summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
#   mutate(var = 4) %>% rename(Clase=class_part_5, Participa=par_mov_w01)
# tab5 <- tip_par %>% group_by(class_part_5, par_mov_w02) %>%
#   summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
#   mutate(var = 5) %>% rename(Clase=class_part_5, Participa=par_mov_w02)
# tab6 <- tip_par %>% group_by(class_part_5, par_mov_w03) %>%
#   summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
#   mutate(var = 6) %>% rename(Clase=class_part_5, Participa=par_mov_w03)
# tab7 <- tip_par %>% group_by(class_part_5, par_mov_w04) %>%
#   summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
#   mutate(var = 7) %>% rename(Clase=class_part_5, Participa=par_mov_w04)
# tab8 <- tip_par %>% group_by(class_part_5, par_mov_w05) %>%
#   summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
#   mutate(var = 8) %>% rename(Clase=class_part_5, Participa=par_mov_w05)
# 
# tab_5<- rbind(tab1, tab2, tab3, tab4, tab5, tab6, tab7, tab8)
# rm(tab1, tab2, tab3, tab4, tab5, tab6, tab7, tab8)
# 
# tab_5$Clase  <- factor(tab_5$Clase, levels = c(1,2,3,4,5), labels = c("(23.52%)", "(3.61%)", "(8.79%)", "(46.01%)", "(18.06%)"))
# tab_5$Participa  <- factor(tab_5$Participa, levels = c(1,2), labels = c("No participa", "Participa"))
# tab_5$var  <- factor(tab_5$var, levels = c(1,2,3,4,5,6,7,8), labels = c("Elección 2013", "Elección 2017", "Plebiscito", "Protesta W1", "Protesta W2", "Protesta W3", "Protesta W4", "Protesta W5"))
# 
# tab_5 %>% 
#   ggplot(aes(x = freq, y = var, fill = Participa)) + 
#   geom_bar(stat = 'identity', position = 'stack') + facet_grid(~ Clase) +
#   labs(y="Evento", x="Proporción",
#        title = "Perfiles de participación: 5 clases", fill = "") +
#   scale_x_continuous(breaks = scales::pretty_breaks(n = 5), limits=c(0, 1)) +
#   theme_bw() + theme(legend.position = "top", 
#                      plot.title = element_text(size=14)) + 
#   scale_fill_viridis_d(begin = .33, end = .66, direction = -1, option = 'viridis')
# 
# rm(tab_3, tab_4, tab_5, tip_par)

```