
```{r packages, message=FALSE, warning=FALSE, include=FALSE}
library(poLCA)
library(knitr)
library(kableExtra)
library(gridExtra)
library(tidyverse)
library(sjmisc)
library(sjlabelled)
library(ggrepel)
library(ggalluvial)
library(survey)
library(spatstat)
library(gtools)
library(sf)
library(elsoc)
library(lubridate)
library(viridis)
library(treemapify)
library(statar)
library(metathis)

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=FALSE, warning=FALSE, message=FALSE, echo=FALSE, fig.topcaption = TRUE, fig.align = 'center')

Sys.setlocale("LC_ALL","ES_ES.UTF-8")
```

```{r formats, include=FALSE }
table_format <- if (is_html_output()) {
  "html"
} else if (is_latex_output()) {
  "latex" 
}

fullw <- if (is_html_output()) {TRUE} else if (is_latex_output()) {FALSE}
fsize <- if (is_html_output()) {14} else if(is_latex_output()) {8}

ggplot2::theme_set(new = theme_test(base_family = "serif"))
options(knitr.kable.NA = '')

```

```{r og-meta}

meta() %>%
  meta_viewport() %>% 
  meta_social(
    title = "Radiografía del Cambio Social 2016-2021",
    url = "https://radiografia-cambio-social-2021.netlify.app/",
    image = "../inputs/imagenes/prueba.png",
    og_type = "book"
  )

```

```{r datos-elsoc, message=FALSE, warning=FALSE, include=FALSE}

# bases de datos ELSOC
elsoc::load_elsoc('long')
elsoc::load_elsoc('wide')

# Datos territoriales ELSOC
elsoc::load_elsoc('territorial-2017')
territorial <- merge(elsoc_wide_2016_2021, elsoc_terr_2017, by="idencuesta")

# Datos generados de cuarentenas:
load(file.path('..', 'inputs', 'cuarentenas_acum.RData'))

# Datos asociados a modelo de clase latente de participación política 
load(file.path('..', 'inputs', 'participacion_tipos5.RData'))

# Datos asociados a modelo de clase latente de sintomatología depresiva
load(file = file.path('..', 'inputs', 'elsoc_depr_lca.RData'))

```

