--- 
title: "Radiografía del Cambio Social en Chile 2016-2021"
subtitle: "Estudio Longitudinal Social de Chile"
site: bookdown::bookdown_site
documentclass: book
bibliography: ["bib/book.bib"]
csl: "bib/apa-no-ampersand.csl"
biblio-style: apalike
link-citations: yes
linkcolor: blue
geometry: "left=4cm, right=3cm, top=2.5cm, bottom=2.5cm"
fontsize: 12pt
linestretch: 1.5
toc-depth: 1
lof: True
lot: True
# author: "González, Roberto; Bargsted, Matías; Figuereido, Ana; Miranda, Daniel; Cerda, Edgardo; Plaza, Alejandro; Salas-Lewin, Rocío"
description: "Resultados ELSOC 2016-2021"
github-repo: "edgardo-cerda/reporte-elsoc-2021"
url: 'https://radiografia-cambio-social-2016-2021.netlify.app/'
always_allow_html: true
editor_options: 
  markdown: 
    wrap: 72
---


# Introducción {-}

<div style="text-align: justify">

El Centro de Estudios de Conflicto y Cohesión Social ([COES](https://coes.cl/)) tiene el agrado de publicar el informe “Radiografía del Cambio Social”, el cual consolida los principales hallazgos longitudinales de cinco mediciones anuales del Estudio Longitudinal Social de Chile ([ELSOC](https://coes.cl/encuesta-panel/)).

ELSOC es una encuesta desarrollada para analizar longitudinalmente, en un estudio panel, la evolución del conflicto y cohesión social en la sociedad chilena, basándose en modelos conceptuales descritos en la literatura nacional e internacional de las disciplinas del ámbito de la Economía, Sociología, Psicología, Ciencia Política y Estudios Urbanos. Se orienta a examinar los principales antecedentes, factores moderadores y mediadores, así como las principales consecuencias asociadas al desarrollo de distintas formas de sociabilidad en Chile.

Durante los últimos años, Chile se ha visto remecido por importantes eventos que han alterado aspectos sociales, políticos y económicos de la vida nacional: la pandemia asociada al COVID-19, y las consecuencias del estallido social más grande de las últimas décadas, ocurrido a partir de octubre de 2019, el que ha desencadenado un proceso constituyente inédito en la historia de Chile.

Ambos fenómenos han significado un desafío para ELSOC y para la comunidad académica, ya que afecta tanto la forma en que son levantados los datos, como las temáticas que el estudio debe abordar. Sin embargo, ELSOC presenta una oportunidad única: la posibilidad de observar el efecto que éstos fenómenos tienen sobre la población chilena desde una perspectiva longitudinal, analizando el cambio y persistencia de comportamientos, creencias y percepciones presentes en la sociedad.

Este informe se centra en tres aspectos claves de la sociedad chilena que se han visto remecidos en el último tiempo: Política y ciudadanía, donde se exploran temáticas de identificación y participación política, cambios en la relación de la ciudadanía con la política institucional y la justificación de la violencia, entre otros; Salud mental y bienestar, abarcando aspectos de salud mental y bienestar, su relación con la economía y cómo se han visto afectados a raíz de la pandemia; y Cohesión Social, donde se analiza el cambio y estabilidad del conflicto y la cohesión desde una perspectiva territorial, las actitudes y creencias de la ciudadanía en torno a los fenómenos de la migración, del sexismo y la meritocracia; entre otros.


## Autores {-}

- Roberto González. *Profesor Titular Escuela de Psicología PUC. Investigador Principal COES. Coordinador estudio ELSOC*
- Matías Bargsted. *Profesor Asociado Instituto de Sociología PUC. Investigador Asociado COES*
- Ana Figuereido. *Profesora titular Escuela de Psicología PUC. Investigadora Asociada COES*
- Daniel Miranda. *Investigador Centro Medición MIDE UC. Investigador Asociado COES*
- Edgardo Cerda. *Asistente Técnico ELSOC*
- Alejandro Plaza. *Coordinador Técnico ELSOC*
- Rocío Salas-Lewin. *Asistente de investigación ELSOC*

### Investigadores colaboradores: {-}

- Fabián Duarte. *Profesor Asociado, Escuela de Economía UCH*
- Barbara Flores. *Investigadora postdoctoral COES y DESOC*
- Álvaro Jiménez. *Profesor adjunto, Escuela de Psicología UDP*
- Natalia Riquelme. *Coordinadora COES*
- Elisa Salas. *Practicante Economía PUC*
- Isidora Didier. *Practicante Sociología UCH*
- Cristobal Ortíz. *Practicante Sociologia UCH*
